### ISSUE TITLE
Type errors when setting `config.global.stubs.xxx`

### ISSUE THREAD

**Issue by posva** [vuejs/test-utils#1023]
On the latest release this started failing:

```ts
import { config } from '@vue/test-utils'
config.global.stubs.RouterLink = true
// Property 'RouterLink' does not exist on type 'Stubs'.
//  Property 'RouterLink' does not exist on type 'string[]'
```

I think the `config.global.stubs` should be marked as of type `Record<string, Stub>`.

**Comment by cexbrayat** [comment]
@xanf You recently updated the types of `stubs` to accept `Record<string, Stub> | Array<string>`, but it looks like it breaks the case reported by @posva . The obvious workaround is to cast as `Record<string, Stub>, but that's not ideal. Would you mind taking a look?

**Comment by xanf** [comment]
@cexbrayat @posva sorry for delay, taking a look on this one :)
