### ISSUE TITLE
shallowMount doesn't stub instances of the same component

### ISSUE THREAD

**Issue by victorborrasdev** [vuejs/test-utils#1162]
# Expected behavior

When using `shallowMount` on a component that contains itself, nested instances should be stubbed, so the output for the reproduction in the shared repo should be something like:

```
    <ul>
      <li>Option 1
        <!--v-if-->
      </li>
      <li>Option 2 <list-stub></list-stub>
      </li>
      <li>Option 3
        <!--v-if-->
      </li>
    </ul>
```

# Current behavior

Nested instances are being mounted as if we were using `mount`. Current output is:

```
    <ul>
      <li>Option 1
        <!--v-if-->
      </li>
      <li>Option 2 <ul>
          <li>Option 2.1
            <!--v-if-->
          </li>
          <li>Option 2.2
            <!--v-if-->
          </li>
        </ul>
      </li>
      <li>Option 3
        <!--v-if-->
      </li>
    </ul>
```

# Reproduction:

https://github.com/victorborrasdev/vue-test-utils-nested-stubs

Please let me know if you need any additional info. Thanks!

**Comment by cexbrayat** [comment]
@victorborrasdev Thank you for the repro 👍 I'm not sure how VTU should behave in that case, both seem acceptable.

@lmiller1990 @xanf WDYT about this?

**Comment by xanf** [comment]
Definitely an issue, I will take a look at it asap

**Comment by mateuszjanusz** [comment]
Any follow-up on this one? 🙏

**Comment by cexbrayat** [comment]
@mateuszjanusz I don't think someone looked into it. Any help is appreciated, feel free to take a look and open a PR to fix this if you want to, and we'll gladly merge
