### ISSUE TITLE
TypeError based on multiple tests: TypeError: Cannot redefine property: $route

### ISSUE THREAD

**Issue by ellismonva** [vuejs/test-utils#1217]
Vue version: "^3.2.4"
Vue router version: "4.0.12"
Vue test utils version: "^2.0.0-rc.15"

I am unsure if this is my code that is causing this, but I cannot see anything online so I figured would be best posting here.
- In my tests suite, I am registering the store in the plugins globally in a file that is in the setupFilesAfterEnv config in jest as follows: 
```

import { config } from '@vue/test-utils';
import store from "../store/store";
import router from "../router";

config.global.plugins = [store, router];
```

In my test, I am simply calling `router.push('my-test-url');` to navigate via vue router (and then calling `await router.isReady()`).

In my test file, I get an error **after the first test runs**. **It is fine for the first test with no errors**.

The error:
<img width="1483" alt="Screenshot 2022-01-05 at 11 46 32" src="https://user-images.githubusercontent.com/86981893/148212789-a885be8e-b07a-434c-8a65-db68fca28593.png">

Does anyone have any idea on this, please?

**Comment by cexbrayat** [comment]
Hi @ellismonva 

Your error does not ring a bell but without your component, test, and exact versions used, we won't be able to help.

Can you put together a minimal reproduction (with the minimum code possible) and push it to a Github repository?

**Comment by ellismonva** [comment]
Hi @cexbrayat 
This is not specific to any component, as I have got this error on multiple test suites (as in different test files and components). As stated though this error only happens after one test runs in each file. I will attempt to get this recreated in a sandbox for you though.

**Comment by cexbrayat** [comment]
@ellismonva Did you manage to reproduce your issue in a minimal example or can I close it?
