### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by Flsion** [vuejs/test-utils#1218]
### Basic Info
"vue": "^3.2.0",
"jest": "^26.6.3",
"vue-jest": "^5.0.0-alpha.10"
"@vue/test-utils": "^2.0.0-beta.14",

### Problem
When I set the `testEnvironment: 'node'` of jest, the `mount` function will report `ReferenceError: document is not defined`. How should I configure ssr?

### Config
```js
{
      transform: {
        '^.+\\.[jt]sx?$': require.resolve('babel-jest'),
        '^.+\\.vue$': require.resolve('vue-jest'),
      },
      testEnvironment: 'node',
}
```

### Test
```js
import { mount } from '@vue/test-utils';
import Button from '../index';

describe('Button', () => {
  test('should emit click event', () => {
    const wrapper = mount(Button);
    wrapper.find('button').trigger('click');

    expect(wrapper.emitted('click')).toHaveLength(1);
  });

  test('should not emit click event when disabled', () => {
    const wrapper = mount(Button, {
      props: {
        disabled: true,
      },
    });
    wrapper.find('button').trigger('click');

    expect(wrapper.emitted('click')).toBeUndefined();
  });
});

```

**Comment by lmiller1990** [comment]
We will need to implement something like https://vue-test-utils.vuejs.org/api/#rendertostring from VTU v1, I think. We don't have any test coverage or examples around SSR at all yet.

Is this something you'd like to explore? The [implementation](https://github.com/vuejs/vue-test-utils/tree/dev/packages/server-test-utils/src) in VTU v1 is pretty simple.

**Comment by cexbrayat** [comment]
Duplicates of #507
