### ISSUE TITLE
Cannot trigger a click with `:disabled="false"`

### ISSUE THREAD

**Issue by posva** [vuejs/test-utils#1221]
`trigger('click')` should also trigger when `disabled="false"`:

```vue
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  setup(props, { emit }) {
    function previousPage() {
      emit('update:currentPage', 1)
    }

    return { previousPage }
  },
})
</script>

<template>
  <button :disabled="false" @click="previousPage">Previous</button>
</template>
```

test:

```js
    const w2 = mount(TestVue)

    await w2.get('button').trigger('click')
    console.log(w2.emitted())
    expect(w2.emitted('update:currentPage')).toEqual([[1]])
```

**Comment by cexbrayat** [comment]
Right, it looks like there is a check on the attribute presence here https://github.com/vuejs/vue-test-utils-next/blob/3b0f7f5a8d1a8de59b9ea68e4a4748292b7a6342/src/baseWrapper.ts#L309

Should be an easy fix if someone wants to grab it.

**Comment by posva** [comment]
After further checking I'm not sure where the problem is because the attribute is set to the string false and that shouldn't happen (it doesn't happen in a normal vue app)...

In HTML, the attribute being set to any string makes the button disabled, so I think the current implementation to check for the button being disabled is correct

**Comment by posva** [comment]
Maybe it's fine to dispatch certain events when the element is disabled as [the browser seems to still not react to them](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY291bnQgPSByZWYoMClcbmNvbnN0IGRpc2FibGVkID0gcmVmKGZhbHNlKVxuY29uc3QgYnV0ID0gcmVmKClcblxuZnVuY3Rpb24gbWFudWFsVHJpZ2dlcigpIHtcbiAgY29uc3QgZXZlbnQgPSBuZXcgTW91c2VFdmVudCgnY2xpY2snKVxuICBidXQudmFsdWUuZGlzcGF0Y2hFdmVudChldmVudClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxsYWJlbD48aW5wdXQgdHlwZT1cImNoZWNrYm94XCIgdi1tb2RlbD1cImRpc2FibGVkXCI+IERpc2FibGVkPC9sYWJlbD5cbiAgPGJyPlxuICBcblx0PGJ1dHRvbiA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiIHJlZj1cImJ1dFwiIEBjbGljaz1cImNvdW50KytcIj5cbiAgICBIZXkge3sgY291bnQgfX1cbiAgPC9idXR0b24+XG4gIDxidXR0b24gQGNsaWNrPVwibWFudWFsVHJpZ2dlclwiPlxuICAgIE1hbnVhbCB0cmlnZ2VyXG4gIDwvYnV0dG9uPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=) but I can't tell for other events and the jsdom implementations

**Comment by lmiller1990** [comment]
Bit of a long shot but what happens if you add `attachTo: document`? I've noticed in jsdom, sometimes `trigger` does different things when elements are/are not attached to the document (for example. clicking a `<label>` will *not* toggle the relevant radio button if the element is not in the document, but will work if it is via `attachTo: true`.

**Comment by posva** [comment]
It's good to know about `attachTo: document.body` 😆 
It doesn't work for happy dom (https://github.com/capricorn86/happy-dom)

**Comment by cexbrayat** [comment]
Unless I'm missing something, this  now works with both happy-dom and jsdom

https://stackblitz.com/edit/vitest-dev-vitest-xcbiar?file=components/Hello.vue
