### ISSUE TITLE
Bug: type errors while using SFC script setup

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/test-utils#1232]
**Describe the bug**
While using two top-level script blocks in SFC, there appear TS errors in the console after `vite build` that go from `@vue/test-utils` typings. Those errors **depend on the trailing coma** from the first script block. 

**To Reproduce**
[Reproduction repo](https://github.com/Oleksii14/vue-jest-type-issue)
Steps:
```shell
pnpm i
```

```shell
pnpm run test:unit # test will pass
```

```shell
pnpm run build # will fail, see the type errors
```

Then go to `HelloWorld.vue` and remove a trailing comma in line 4.
Perform the steps above and the build error will dissapear.

**Expected behavior**
Type errors do not appear and do not depend on the trailing comma in the top-level script

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.18
- `Vue` version: 3.2.26
- `node` version: 14.17.6
- `pnpm` version: 6.25.1

**Additional context**

**Comment by lmiller1990** [comment]
I don't understand your comment around the trailing comma. Line 4 does not have one: https://github.com/Oleksii14/vue-jest-type-issue/blob/888e76c5276fda9509ba5b87121fb34c1fb44523/src/components/HelloWorld.vue#L4

I see this issue. I was able to get it to work by adding `export default defineComponent` to the first script tag:

```html
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  inheritAttrs: false
})
</script>
```

**Comment by Oleksii14** [comment]
Sorry, I meant semicolon.

Thanks for the reply, but I need it to work without `defineComponent` using `setup` script.

According to my comment, TS errors dissapear at once after I remove the semicolon. Why is that happening?

**Comment by cexbrayat** [comment]
This is super strange indeed. I don't think this is an issue with VTU though, it might be an issue of `vue-tsc`.

You should try to open this issue on the Volar repo, and link back to it so we can track it.

**Comment by lmiller1990** [comment]
Looks like it is fixed: **https://github.com/johnsoncodehk/volar/issues/874**
