### ISSUE TITLE
Backwards compatible with happy-dom

### ISSUE THREAD

**Issue by designervoid** [vuejs/test-utils#1240]
I wrote about that problem in another issue:
https://github.com/vuejs/vue-test-utils-next/issues/1239#issuecomment-1013670003

**Is your feature request related to a problem? Please describe.**
Cant't build Vue project

**Describe the solution you'd like**
Additional context block in the comment (second and next screenshots, besides the last, thats truly problem of `happy-dom` package):
https://github.com/vuejs/vue-test-utils-next/issues/1239#issue-1104633019

**Describe alternatives you've considered**
`libCheck: true` in `tsconfig.ts` or manually force fix types in `node_modules` (`happy-dom`)

**Additional context**
Maybe best solution:
https://github.com/vuejs/vue-test-utils-next/issues/1239#issuecomment-1013760464

**Comment by cexbrayat** [comment]
Hi @designervoid , thank you for opening an issue

Compatibility with happy-dom was not that easy the last time I checked, as there were some behavior differences. 

If you are just talking about the type error, then simply add `skipLibCheck: true` to your tsconfig (this is probably better anyway). 

If you are talking about full compatibility, then I think a good way to start would be to have the test suite of VTU work both with jsdom and happy-dom. Would you like to give it a try? If you're interested, we can give you some guidance, and we would be very happy if you submit a PR.

**Comment by designervoid** [comment]
Probably for users `skipLibCheck: true` is better.
Compatibility with happy-dom can be reached on `dev` environment. 
What do you think about this?

**Comment by cexbrayat** [comment]
> Compatibility with happy-dom can be reached on dev environment.
> What do you think about this?

I'm sorry, I did not understand what you mean by that. Which dev environment?

**Comment by designervoid** [comment]
@cexbrayat https://github.com/vuejs/test-utils#development

**Comment by designervoid** [comment]
However, the property (`libCheck`)[https://github.com/vuejs/test-utils/blob/main/tsconfig.volar.json#L5] is already defined.

**Comment by cexbrayat** [comment]
Maybe I was not clear: you need to add `skipLibCheck` to _your_ project to get rid of the issue.

But I think I misunderstood you: what are you trying to do?

**Comment by designervoid** [comment]
@cexbrayat yeah, i understand, just experimenting. i will set `libCheck`. can close the issue.
