### ISSUE TITLE
Bug: Teleport does not return actual html content if content is not defined in a child component

### ISSUE THREAD

**Issue by yuwu9145** [vuejs/test-utils#1266]
Teleport defined in child component results in `<!--teleport start--><!--teleport end-->`
**Describe the bug**

```
import { mount } from '@vue/test-utils'

beforeEach(() => {
  // create teleport target
  const el = document.createElement('div')
  el.id = 'modal'
  document.body.appendChild(el)
})

afterEach(() => {
  // clean up
  document.body.outerHTML = ''
})

test('teleport content wrapped in a child component works', () => {
  const ChildComponent = {
    name: 'ChildComponent',
    template: '<span>hello world</span>'
  }
  const ParentComponent = {
    name: 'ParentComponent',
    template: '<teleport to="#modal"><child-component /></teleport>',
    components: { ChildComponent }
  }
  const parentWrapper = mount(ParentComponent)
  const child = parentWrapper.getComponent(ChildComponent)

  expect(child.html()).toMatchInlineSnapshot(`"<span>hello world</span>"`)
})

test('teleport content as plain html does not work', async () => {
  const TeleportComponent = {
    name: 'ParentComponent',
    template: '<teleport to="#modal"><span>hello world</span></teleport>',
  }
  const wrapper = mount(TeleportComponent)

  expect(wrapper.html()).toMatchInlineSnapshot(`"<span>hello world</span>"`) // Results in <!--teleport start--><!--teleport end-->
})
```

**Expected behavior**

Teleport should not affect child component gets correct html content

- I guess it makes certain sense to argue the component holding `teleport` should return `<!--teleport start--><!--teleport end-->`
- However, the real challenge is how to test the eventual content rendered inside the teleport target if the content is not from a child component?

**Related information:**
- `@vue/test-utils` version: ^2.0.0-alpha.8
- `Vue` version: ^3.0.0-beta.17
- `node` version: 14.15.0
- `npm` (or `yarn`) version: 6.14.8

**Additional context**

**Comment by lmiller1990** [comment]
As of rc.17, we should be stubbing `<teleport>` by default. You could consider updating to rc.17. PR that implemented this: https://github.com/vuejs/test-utils/pull/1087

I got your test to behave mostly how you are suggesting by stubbing teleport - I get 

```html
    Received: "<teleport-stub><span>hello world</span></teleport-stub>"`
```

Here's the code:

```ts
test('teleport content as plain html does not work', async () => {
  const TeleportComponent = {
    name: 'ParentComponent',
    template: '<teleport to="#modal"><span>hello world</span></teleport>',
  }

  const wrapper = mount(TeleportComponent, {
    global: {
      stubs: {
        teleport: true
      }
    }
  })

  expect(wrapper.html()).toMatchInlineSnapshot(`"<span>hello world</span>"`) // Results in <!--teleport start--><!--teleport end-->
})
```

As for testing, see here: https://next.vue-test-utils.vuejs.org/guide/advanced/teleport.html.

If you are still having problems or think there's a bug, let me know. For now, I don't think there is any bug, so I'll close this.

**Comment by yuwu9145** [comment]
@lmiller1990 Thanks for your comprehensive explanation, I tested in my end it works very well!
