### ISSUE TITLE
Bug: Cannot set global plugins with shallowMount

### ISSUE THREAD

**Issue by tsiotska** [vuejs/test-utils#1276]
**Expected behavior**

Global components should be registered in plugins and stubbed as other children using shallowMount/shallow: true

**Current behavior**

Project has registered global components as vue plugins (objects with install function).
ShallowMount with global.plugins throws next:
'TypeError: Cannot set property tagName of [object Element] which has only a getter'
whereas simple Mount works okay

**To Reproduce**

```
  function factory() {
    return shallowMount(Master, {
      global: {
        plugins: [LayoutPlugin],
      }
    })
  }
```

**Related information**

- @vue/test-utils version: 2.0.0-rc.18
- vue version: 3.1.5
- ant-design-vue version: 2.2.8

**Comment by cexbrayat** [comment]
@tsiotska Sorry for the delay, this issue slipt through my inbox

Did you find a solution?
I see that you're using a fairly old vue version. Did you try to update to the latest vue version (and of the other dependencies)?

If that does not work let me know and we'll investigate.

**Comment by tsiotska** [comment]
@cexbrayat Thank you for feedback. 
I've made a reproduction with simple test case below
https://github.com/tsiotska/vue-test-utils-reproduction/blob/test-utils/1276/src/app.spec.js#L19

I updated  "vue" to"^3.2.33", "@vue/test-utils" to "2.0.0-rc.21" and critical error became just a warning. Plugin components started to be stubbed as well as other children with shallowMount, **but there's no possibility to 'unstub'** that component, if you do that it'll be completely removed

**Comment by cexbrayat** [comment]
Hi @tsiotska 

Sorry we took so long to get back to you.
I think what you're trying to do in this repro is not possible: `shallowMount` will stub everything, even if you pass `false` to a stub. So maybe you should use mount in that case.
