### ISSUE TITLE
Bug: The type passed by the button does not match the expectation

### ISSUE THREAD

**Issue by bosens-China** [vuejs/test-utils#1313]
**Describe the bug**

The type passed by the button does not match the expectation

**To Reproduce**

``` jsx
export default {
  setup() {
    return () => <button type="abc">123</button>
  }
}
```

``` js
  test('type', () => {
    const btn = mount({
      render: () => <Button></Button>,
    });
    console.log(btn.html());
  });
```
return 
``` js
       <button type="submit">
       123
      </button>
```

**Expected behavior**

`type = abc`

**Related information:**
- `@vue/test-utils` version:^2.0.0-rc.18
- `Vue` version:^^3.2.31
- `node` version:v14.18.1
- `npm` (or `yarn`) version: pnpm 6.30.1

**Additional context**

**Comment by cexbrayat** [comment]
@bosens-China Thanks for the report, but I don't think this is an issue: if the button type is invalid like `abc`, the browser will default to submit, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

If you specify a valid type like `button` or `reset` then the test would succeed.

**Comment by bosens-China** [comment]
But the button can switch styles according to the type. Although it does not conform to the specification, if a non-standard attribute is passed, how can I test the result?

![image](https://user-images.githubusercontent.com/39508895/153861986-5cc416bc-2560-4a30-bac6-ed1e2fce056c.png)

**Comment by cexbrayat** [comment]
Well this is not the same here, as `el-button` is probably a Vue component I imagine. So you can pass whatever you want to `type` as here it is a prop and not a standard HTML attribute
