### ISSUE TITLE
TypeError: Cannot read property 'devtoolsRawSetupState' of undefined

### ISSUE THREAD

**Issue by jonsalvas** [vuejs/test-utils#1329]
Vue Version: 3.2.31
Test-Utils: 2.0.0-rc.18

When upgrading from vue from 3.2.24 to 3.2.25 all our tests fail with the following error:
```
TypeError: Cannot read property 'devtoolsRawSetupState' of undefined
```

This is thrown when trying to call .findComponent on a mounted component using ref:
`wrapper.findComponent({ref: ".."})`

Seems that we were not alone with this issue:
https://github.com/vuejs/vue-test-utils/issues/1962

**Comment by cexbrayat** [comment]
@jonsalvas Thanks for the report. Can you provide a small reproduction so we can investigate? You can use `create-vue` to quickly set up a project with Vue Test Utils.

**Comment by lmiller1990** [comment]
I guess we just need a check around this: https://github.com/vuejs/test-utils/blob/f61b8aeb84352b29e29666326939531cd81c3bd6/src/vueWrapper.ts#L57

We are on latest Vue here though, which is [3.2.31](https://github.com/vuejs/test-utils/blob/main/package.json#L46). I'd love to see a reproduction, too.

**Comment by jonsalvas** [comment]
Hey, thanks for the fast reply and sorry for the delay, I had some other tasks to do at work. You can find a reproduction project here:
https://github.com/jonsalvas/test-utils-issue1329

I think the key is the v-for here:

```
<div v-for="value in 3" :key="value">
    <HelloWorld ref="hello" msg="Welcome to Your Vue.js App" />
  </div>
```

**Comment by lmiller1990** [comment]
Is

```html
<div v-for="value in 3" :key="value">
```

Even valid? I thought the syntax was `v-for="val in {object|array}". Is using a number even documented or valid syntax?

**Comment by jonsalvas** [comment]
The doc says the following are allowed: "Array | Object | number | string | Iterable" (https://vuejs.org/api/built-in-directives.html#v-for).  And changing it to [1,2,3] makes no difference. 

Anyway, the reproduction project is just a simplified example. In our original code we iterate over arrays of objects to generate multiple options/checkboxes.

**Comment by lmiller1990** [comment]
Thanks for the repo, will try take a look.

**Comment by cexbrayat** [comment]
I did not investigate but it looks similar to issues we've seen in vue core
https://github.com/vuejs/core/pull/5118 should fix them upstream (and should be merged and released fairly soon).
I think that before spending too much time on this, we'll wait for this patch and revisit this to see if the issue persists.

**Comment by cexbrayat** [comment]
@jonsalvas Can you give it a try with VTU 2.0.0-rc.20 and Vue v3.2.32 please? The fix I was talking about landed in Vue core, so it might solve your problem.

**Comment by jonsalvas** [comment]
@cexbrayat nope, slightly different error, but technically the same:

`TypeError: Cannot read properties of undefined (reading 'devtoolsRawSetupState')`

**Comment by freakzlike** [comment]
I was able to reproduce it within our unit tests and created a PR with the fix.

**Comment by jonsalvas** [comment]
thanks a lot! Any idea when it is going to be released?

**Comment by lmiller1990** [comment]
> thanks a lot! Any idea when it is going to be released?

It's out now! https://github.com/vuejs/test-utils/releases/tag/v2.0.0-rc.21
