### ISSUE TITLE
Bug: `html()` makes the output pretty making comparisons difficult

### ISSUE THREAD

**Issue by nandi95** [vuejs/test-utils#1334]
**Describe the bug**
The change introduced by https://github.com/vuejs/test-utils/pull/1120 has caused my test suite to fail.
The test checks that the focused element is same as the expected but given the `document.activeElement?.outerHTML` is on one line and `html()` is on multiple with indentation this fails.

**To Reproduce**
https://github.com/karnama/vueish/blob/main/src/components/select/UISelect.test.ts#L534

**Expected behavior**
The test to pass

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.18
- `Vue` version: 3.2.31
- `node` version: 17.5.0
- `npm` (or `yarn`) version: 8.4.1

**Additional context**
If this is desired, what is the best way to remove the indentation and new lines? a regex? something else?
Why was this change introduced? If people have to look at the html in the console the canuse the `pretty()` themselves no? or otherwise the differences are highlighted in the console.

**Comment by lmiller1990** [comment]
HTML and snapshot assertions have been painful over the years. What's the question exactly, how best to format HTML? I think the only way to expect consistency from an undefined behavior (whitespace around HTML is not something VTU specifies) would be to format it on your end using something like `prettier`.

For your particular assertion, I'd usually just have an `id` or `data-testid` and compare the two, so you are not relying HTML whitespace (which has no semantic meaning).

**Comment by nandi95** [comment]
I have not considered that. It is a good idea, excpect I would rather find something else that is unique to that html than a test specific attribute as I'm reluctant to change the component for the sake of testing.
> I don't think anyone should be relying on comparing HTML strings for any kind of testing

Perhaps we can make a note of this in the documentation?
I'm happy to open a PR

**Comment by lmiller1990** [comment]
We could add a note, but it's a complex issue to explain. This is also why I think snapshots for DOM comparison is basically useless - knowing how the string looks doesn't tell you anything about if it actually behaves correctly.
