### ISSUE TITLE
Translating the Documentation

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs/test-utils#1340]
#### Purpose

I would like to know,

When the documentation should be ready for translation?

And is the project's documentation already configured to facilitate the translation?

**Comment by nazarepiedady** [comment]
@lmiller1990 what do you consider a fully completed translation?

- A fully translation of a documentation that does not change, or

- A fully translation of a documentation that does constantly change

**Comment by lmiller1990** [comment]
First instinct is all pages in the current docs are translated. My concern is keeping it up to date - VTU v1 has 6 translation and are all outdated by months or even years. What do you think? Any ideas how we might solve this?

My experience in the past was

1. Add translation
2. Gets out of date
3. Bug report(s) based on old translation
4. I need to triage all these bugs

Translations are great, but unless they are actively updated (they never are, VTU v1 is a prime example) I feel like it adds a lot of overhead. Another alternative would be translating and hosting on your own GH repo/profile, which would let you move faster and get something (even partially completed) out there faster.

Thoughts?

**Comment by nazarepiedady** [comment]
@lmiller1990 you put the things in right way, I precisely have intentions to keep the documentation updated.

I will consider all your points.

**Comment by lmiller1990** [comment]
What would be nice is some automated system to make new issues to update the translations every time something changes. I wonder if there's a known solution for this?
