### ISSUE TITLE
Inaccurate Documentation/Function Signature for `wrapper.attributes()` 

### ISSUE THREAD

**Issue by Fimbelowski** [vuejs/test-utils#1355]
These are the function signatures for `wrapper.attributes()` listed in the documentation.

```TypeScript
attributes(): { [key: string]: string }
attributes(key: string): string
attributes(key?: string): { [key: string]: string } | string
```

However, calling `wrapper.attributes(someKey)` where `someKey` is an attribute that does not exist on the wrapper, `undefined` is returned. This is the behavior I would expect, but this is not reflected in the docs nor within `baseWrapper.d.ts`.

Furthermore, the third signature in the docs is also missing from `baseWrapper.d.ts`.

**Comment by cexbrayat** [comment]
Nice catch @Fimbelowski 

Can you open a PR to fix this? I would gladly review and merge it!
