### ISSUE TITLE
Feature request: create hook or class for create event in dom-events

### ISSUE THREAD

**Issue by OXXXRA** [vuejs/test-utils#1361]
https://github.com/vuejs/test-utils/blob/main/src/constants/dom-events.ts#L110-L975
Is it DRY mistake. Can create class or hook for delete the duplicate code?

**Comment by OXXXRA** [comment]
So like here
<img width="731" alt="Снимок экрана 2022-03-08 в 13 16 45" src="https://user-images.githubusercontent.com/26336577/157216663-6b1998a4-7681-4acc-a2e0-b3a487ebd710.png">
:

**Comment by cexbrayat** [comment]
Sure. Feel free to open a PR if you want to improve the code, we will gladly review it 👍

**Comment by lmiller1990** [comment]
I don't understand the proposal but always good to reduce code, if there's a better way to do this, that'd be great!

**Comment by cexbrayat** [comment]
@OXXXRA I'll close the issue as this is not really a problem or a feature request: we'll gladly merge your PR if you want to refactor dom-events 👍
