### ISSUE TITLE
Bug: isVisible() always returning true

### ISSUE THREAD

**Issue by rakibullahsazib** [vuejs/test-utils#1393]
**Describe the bug**

From the documentation, isVisible() should return false if v-show is false. But it is always returning true in the test. Although it is working perfectly in the browser.

**To Reproduce**

Here is the repo to reproduce the issue : https://github.com/rakibullahsazib/vitest-playground/tree/test-utils-visible-issue
Inside /src/components/visible folder is the Visible.vue component and the test file for it. Run yarn test to see test fail.

**Expected behavior**

isVisible() should return false when v-show is false.

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.18
- `Vue` version: 3.2.25
- `node` version: 3.2.25
- `yarn` version: 8.1.2
- `vitest` version: 0.7.12

**Additional context**

I am not sure, but does it have anything to do with vitest. By the way, I have already checked the closed issue with similar problem. But you can see in the repo that the my code has no complex structure and yet it is causing the issue.

**Comment by cexbrayat** [comment]
Hi @rakibullahsazib 

Thank you for providing a repro. There is an issue with your test though: the selector is wrong in the unit test.

```diff
-expect(wrapper.get('[data-testid=visible')
+expect(wrapper.get('[data-testid=visible]')
```

When the test is fixed, you can fix the issue by switching from happy-dom to jsdom. There are several issues with happy-dom, and I would advise using jsdom in your tests.

I'll close the issue for now, feel free to reopen if jsdom does not fix your problem.

**Comment by rakibullahsazib** [comment]
Sorry, for the wrong selector. Ok, then the problem is with happy-dom. I'll try jsdom. Thanks man
