### ISSUE TITLE
Bug: emits aren't catch in prod mode

### ISSUE THREAD

**Issue by wukang0718** [vuejs/test-utils#1410]
**Describe the bug**

After setting the environment variable `NODE_ENV=production`, execute `yarn test:unit` until the emitted("foo") is undefined.  
`example.spec.js`
```javascript
import { shallowMount } from '@vue/test-utils'
describe("example", () => {
  it("test emitted", async() => {
    console.log(process.env.NODE_ENV)
    const com = {
      template: `<div data-test="test" @click="$emit('foo', 'bar')"></div>`,
      emits: ["foo"],
    };
    const wrapper = shallowMount(com);
    await wrapper.find("[data-test=test]").trigger("click");
    expect(wrapper.emitted("foo")).toHaveLength(1);
    expect(wrapper.emitted("foo")[0]).toEqual(["bar"]);
  });
})
```
result
![image](https://user-images.githubusercontent.com/42261663/162661489-c82e85b8-2a38-4cf7-8a3d-bb328f156d8f.png)

**To Reproduce**

**Expected behavior**

Emitted works normally.
**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.19
- `Vue` version: 3.2.31
- `node` version: v14.17.4
- `npm` (or `yarn`) version: yarn 1.22.11

**Additional context**

**Comment by cexbrayat** [comment]
@wukang0718 I think this is expected: some parts of VTU relies on the devtools, and devtools are disabled in prod mode by default.

Have you tried running this test with the devtools enabled (IIRC you need to set `__VUE_PROD_DEVTOOLS__` to `true`)?

**Comment by wukang0718** [comment]
I set `__VUE_PROD_DEVTOOLS__` in vue.config.js to be `true`, but the result is still wrong.
```javascript
{
  chainWebpack: (config) => {
     config
       .plugin('feature-flags')
       .tap(() => {
          return [{ __VUE_OPTIONS_API__: true, __VUE_PROD_DEVTOOLS__: true  }]
       })
  }
}
```

**Comment by cexbrayat** [comment]
Can you provide us a simple reproduction, ideally in a github repository, so we can investigate and help you?

**Comment by wukang0718** [comment]
https://github.com/wukang0718/v3-test-demo

**Comment by cexbrayat** [comment]
I don't think this can work sadly: if you use the production mode, then the CLI uses `runtime-core.prod.cjs` in which the devtools are already removed. So setting `__VUE_PROD_DEVTOOLS__` has no effect.

I think you'll have to use dev mode in your tests if you use the CLI, as we usually do. Or you can open an issue on the CLI side, maybe there is a configuration that I don't know about that could help.

In the meantime, I'm going to close the issue here, as there is nothing we can do on VTU side.
