### ISSUE TITLE
Bug: test doesn't render conditional element after condition changed inside onMounted

### ISSUE THREAD

**Issue by JCodePeace** [vuejs/test-utils#1411]
**Describe the bug**

A reference value of a variable is not updating inside the onMounted hook in case of using `<script setup>`.

**To Reproduce**

[Reproduction](https://github.com/JCodePeace/Vue-Test-Issue)

Shortly, the issue happens with conditinal rendering. For example,

```
<template>
  <div class="hello">
      <div>
          <span id="test_1"></span>
          <span v-if="v" id="test_2"></span>
      </div>
  </div>
</template>

<script setup lang="ts">

import {defineProps, onMounted, ref} from "vue";

let props = defineProps({
    vis: {
        type: Boolean
    }
});

const v = ref(false)

onMounted(() => {
    if (props.vis) {
        v.value = true
    }
})


</script>
```

The v variable is updating inside onMounted hook and during browser rendering everything is good. But when I run tests with the same props, onMounted doesn't render condition inside HTML.

**Expected behavior**

**Related information:**
- `@vue/test-utils` version: ^2.0.0-0
- `Vue` version: ^3.2.13
- `node` version: v16.7.0
- `npm` (or `yarn`) version: 8.5.4

**Additional context**

**Comment by cexbrayat** [comment]
@JCodePeace I think this is expected. Try to add `await nextTick()` in your test after mounting your component, and the value should be properly updated.

**Comment by JCodePeace** [comment]
@cexbrayat It worked, thank you very much for your help.
