### ISSUE TITLE
Bug: instanceof Element check fails

### ISSUE THREAD

**Issue by Derviloper** [vuejs/test-utils#1433]
**Describe the bug**
The `instanceof Element` checks in the library fails (e.g. at [`src/utils/stringifyNode.ts`](https://github.com/vuejs/test-utils/blob/main/src/utils/stringifyNode.ts) or [`src/utils/isElement.ts`](https://github.com/vuejs/test-utils/blob/main/src/utils/isElement.ts)).
Because of that e.g. the `wrapper.find` method always returns an empty array and `wrapper.html` adds `xmlns="http://www.w3.org/1999/xhtml"` to every root element.

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.20
- `Vue` version: 3.2.32
- `node` version: v17.7.2
- `npm` (or `yarn`) version: 8.5.5

**Additional context**
![Screenshot from 2022-04-15 22-08-01](https://user-images.githubusercontent.com/36593752/163629614-f4fa6973-0035-49e0-8b36-ac0e365e84a5.png)
I noticed this by using the debugger.
At the bottom you can also see that even `element instanceof element.ownerDocument.defaultView.Element` returns false.

I run the tests with this command: `vitest --environment jsdom`
I think the only thing special is that I have the `canvas` package installed.

**Comment by cexbrayat** [comment]
I'm sorry I don't understand what your issue is. Can you provide us a minimal reproduction on GitHub with a simple component and a failing test?

**Comment by Derviloper** [comment]
I have created a repository where i can reproduce this: https://github.com/Derviloper/instanceof-fails
If you `npm run test:unit` you can see that the [`WelcomeItem.test.ts`](https://github.com/Derviloper/instanceof-fails/blob/master/src/test/components/WelcomeItem.test.ts) can't find a h3 element when it should.
And if you also look at the [`WelcomeItem.test.ts.snap`](https://github.com/Derviloper/instanceof-fails/blob/master/src/test/components/__snapshots__/WelcomeItem.test.ts.snap) you can see that the root element has this `xmlns="http://www.w3.org/1999/xhtml"` which shouldn't be there.
This is because the `instanceof Element` checks returns false when it should be true.
If you look at my screenshot on the top you can see the the element currently is a `HTMLDetailsElement` which normally extends `Element` but here it returns false.

**Comment by freakzlike** [comment]
I was able to run the tests successfully by removing the vitest `threads: false` option from `vite.config.ts`. Also I had no issues when using jest with `--runInBand` option. IMO this might be an issue with vitest

**Comment by cexbrayat** [comment]
Ho good catch @freakzlike ! Yes there are several issues with `threads: false` with vitest (some I opened myself on the vitest repo). They are working on it, but in the meantime, I recommend to stick to the threaded mode 

Let's close then, and we'll revisit if this is still an issue when the vitest team fox these issues on their side

**Comment by Derviloper** [comment]
I set `threads: false` because of the `node-canvas` package I installed (see https://github.com/vitest-dev/vitest/issues/740). So yes I'll guess I have to with the issues than.
