### ISSUE TITLE
Bug: Dom update problem when using fake timers

### ISSUE THREAD

**Issue by GDX64** [vuejs/test-utils#1448]
### Subject of the issue

when I use fake timers, the dom won't update for async actions until I wait nextTick twice.

### Steps to reproduce

```
<template>
  <div>
    {{ data }}
  </div>
</template>

<script lang="ts" setup>
import { onBeforeUpdate, onMounted, onUpdated, ref, onRenderTriggered } from 'vue';
const data = ref('');
function fakeAPI() {
  return new Promise((resolve) => setTimeout(resolve));
}
onMounted(async () => {
  await fakeAPI();
  data.value = 'world';
  console.log('changed text');
});

onBeforeUpdate(() => console.log('before update'));

onRenderTriggered(() => console.log('rerender'));

onUpdated(() => console.log('updated'));
</script>
```
```
// the test

import { mount } from '@vue/test-utils';
import { nextTick } from 'vue';
import FakeDemo from './fakeDemo.vue';

describe('fake', () => {
  test('timer problem', async () => {
    vi.useFakeTimers();
    const wrapper = mount(FakeDemo);
    console.log(wrapper.html());
    vi.advanceTimersByTime(10_000);
    console.log(wrapper.html());
    await nextTick();
    console.log(wrapper.html());
  });
});
```

the output

```
<div></div>
<div></div>
rerender
changed text
<div></div>
before update
updated
```
### Expected behaviour

I expected to see
```
<div></div>
<div></div>
rerender
changed text
before update
updated
<div>world</div>
```

### Actual behaviour

only if I await for nextTick one more time in sequence, I can get the dom update.
like 
```
await nextTick();
await nextTick();
```

Notice that before calling the first nextTick, I already had a rerender scheduled, so I thought it woud require just one tick to update the dom.

Is that intended behaviour?

**Comment by cexbrayat** [comment]
Hi @GDX64 

I think this is normal behavior. You can probably avoid the multiple `nextTick` with `flushPromises`. In your example I don't think you really rely on fake timers, so you can probably rewrite it like this:


 ```ts
const wrapper = mount(FakeDemo);
await flushPromises();
expect(wrapper.html()).toContain('world');
```

**Comment by GDX64** [comment]
@cexbrayat, in fact, if I wait for the flushPromises instead of the two ticks, it works even with the fake timers. Thank you for your help.
