### ISSUE TITLE
Bug: DOM sometimes not being updated

### ISSUE THREAD

**Issue by SkippedTurn** [vuejs/test-utils#1476]
**Describe the bug**
As of the test-utils version 2.0.0-rc.21, some of our tests started failing seemingly because the DOM was not being updated. For one component I managed to narrow the cause of this down to an equality check between two objects somehow no longer resolving to true, even when they both refer to the same object.
 
(Unfortunately the other components for which tests were broken are relatively old code, so I couldn't immediately verify whether those failures share a similar cause.)
 
 
**To Reproduce**
Here is a small repo in which the issue is reproduced: https://github.com/SkippedTurn/reproduction-recipe-test-utils. The line that seems to be causing the issue is [ln7 in "TestComponent.vue"](https://github.com/SkippedTurn/reproduction-recipe-test-utils/blob/master/src/TestComponent.vue#L7).

In the above project, if the v-if is replaced with `v-if="selectedField?.name === field.name"` so that the check is done on strings instead of Objects, everything does work again.
 
 
**Expected behavior**
The equality check resolves to true, and the associated tests succeed.
Note that, outside of the tests, the component works as intended with the latest version of Vue (3.2.33).
 
 
**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.21
- `Vue` version: 3.2.33
- `node` version: 18.1.0
- `npm` version: 8.8.0

**Comment by freakzlike** [comment]
This is caused by #1434. We might need to revert this changes and find another way to get props with Ref working.

**Comment by freakzlike** [comment]
Just as hint: I was able to run your reproduction successfully with:

```js
import { reactive } from 'vue';

const wrapper = mount(TestComponent, {
  props: { availableFields: reactive(FIELDS) }
});
```

or 

```js
import { readonly } from 'vue';

const wrapper = mount(TestComponent, {
  props: { availableFields: readonly(FIELDS) }
});
```

Maybe this workaround is easier for you instead of changing the `v-if`

**Comment by lmiller1990** [comment]
Looks like we have a fix. That said, relying on object equality seems unideal in general - comparing primitives seems far superior, with no real downside.
