### ISSUE TITLE
Bug: Functional Component Not Receiving Prop Data

### ISSUE THREAD

**Issue by mlturner88** [vuejs/test-utils#1490]
**Describe the bug**
Initial or later set props are not being passed into a functional component.

**To Reproduce**
I have made [a sample repo showcasing the issue here.](https://github.com/mlturner88/vue-test-utils-func-component-bug) After cloning the repo you may use the below commands to run the tests.

```bash
npm install
npm run test
```

**Expected behavior**
Functional components to receive props from the `mount()` function.

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.21
- `Vue` version: 3.2.33
- `node` version: 16.15.0
- `npm` version: 8.5.5

**Additional context**
The example (and my project itself) are using `vite` and `vitest` in conjunction with `@vue/test-utils`.

**Comment by mlturner88** [comment]
> You need to await `setProps`
> 
> https://test-utils.vuejs.org/guide/essentials/passing-data.html#using-setprops

What about the case of mounting the component giving it props from the start?

**Comment by freakzlike** [comment]
Oh sorry, I missed that. I was able to reproduce it in our unit tests and pushed a fix #1513
