### ISSUE TITLE
Bug: emitted does not include fallthrough events

### ISSUE THREAD

**Issue by KarKarbI4** [vuejs/test-utils#1509]
**Describe the bug**
`wrapper.emitted` does not include events, which are proxied by component to child component via context.attrs

**To Reproduce**
reproduction repo: https://github.com/KarKarbI4/vtu-emitted-fallthrough-bug

```js
// CoolInput.vue proxies BaseInput.vue
<template>
  <base-input v-bind="{ ...props, ...attrs }" />
</template>

<script>
import { defineComponent } from "vue";
import BaseInput from "./BaseInput.vue";

export default defineComponent({
  name: "CoolInput",
  components: {
    BaseInput,
  },
  setup(props, { attrs }) {
    return {
      props,
      attrs,
    };
  },
});
</script>
```

```js
// BaseInput.vue
<template>
  <input :value="props.modelValue" @input="onInput" />
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "BaseInput",
  props: {
    modelValue: {
      type: String,
      required: true,
    },
  },
  setup(props, { emit }) {
    function onInput(event) {
      emit("update:modelValue", event.target.value);
    }

    return {
      props,
      onInput,
    };
  },
});
</script>
```

```js
// CoolInput.test.js
import CoolInput from './CoolInput.vue';
import { it, expect } from "vitest";
import { mount } from "@vue/test-utils";

it('Test CoolInput', async () => {
  const wrapper = mount(CoolInput);
  
  await wrapper.find('input').setValue('testvalue');
  
  const emitted = wrapper.emitted('update:modelValue') || [];
  expect(emitted.length).toBe(1);  // FAILS: recieved "0", expected "1"
  expect(emitted).toMatchObject([ ['testvalue'] ]);
})
```

meanwhile in application code I use
```
<CoolInput v-model="text" />
```
and text is correctly updated

**Expected behavior**
I expect wrapper.emitted to include fallthrough events

**Observed behavior**
wrapper.emitted does not include fallthrough events

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.21
- `Vue` version: 3.2.25
- `node` version: v16.14.2
- `pnpm` version: 7.0.0-rc.3

**Additional context**
Maybe bug is releated to issue https://github.com/vuejs/test-utils/issues/352

**Comment by lmiller1990** [comment]
Interesting - seems like a bug. I did not know you could proxy events by doing `...attrs`. First step would be adding a failing test, then we can look into it more depth. Would you be interested in trying to fix this?

**Comment by freakzlike** [comment]
I have created a reproduction PR #1574. Not able to find a solution yet

**Comment by freakzlike** [comment]
I'm not sure if this is achievable by only changing the `@vue/test-utils`.

First the listener must be passed to `CoolInput`. Otherwise `attrs` contains nothing. You can test the same code without `emitted` when you pass the listener as prop

```typescript
const updateFn = jest.fn()
const wrapper = mount(CoolInput, {
  props: {
    modelValue: 'Text',
    'onUpdate:modelValue': updateFn
  }
})

await wrapper.get('input').setValue('New Text')

expect(updateFn).toHaveBeenCalledTimes(1)
expect(updateFn).toHaveBeenLastCalledWith('New Text')
```

Second `v-bind="...attrs"` does not use vue's `emit` handling (no call of `emit` and just a function as prop). So no event validation and also no logging for vue devtools (`emitted()` relies on this).

**Comment by cexbrayat** [comment]
The analysis of @freakzlike is correct, and we can't do more in that case, as there is in fact no event emitted.
The solution proposed by @freakzlike is the one I would also use (see previous comment).
