### ISSUE TITLE
Bug: doc website search bar not work

### ISSUE THREAD

**Issue by arnauddoub** [vuejs/test-utils#1512]
**Describe the bug**
On the site test-utils.vuejs.org when I open the search bar I get an error
`POST https://undefined-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.8.5)%3B%20Browser%20(lite)%3B%20docsearch%20(3.0.0)%3B%20docsearch-react%20(3.0.0)%3B%20docsearch.js%20(3.0.0)&x-algolia-api-key=ee1b8516c9e5a5be9b6c25684eafc42f&x-algolia-application-id=undefined net::ERR_NAME_NOT_RESOLVED`

**To Reproduce**
I go to website test-utils.vuejs.org, i click on the search bar, i fill input and nothing happens.

**Expected behavior**
I want to use the search bar.

**Related information:**
- Website doc production

**Additional context**
<img width="1427" alt="Screenshot 2022-05-19 at 10 20 03" src="https://user-images.githubusercontent.com/14277978/169248601-465ddb96-83ef-4ea0-be49-076845f21072.png">

**Comment by cexbrayat** [comment]
Thanks for the report, we'll look into it 👍

**Comment by lmiller1990** [comment]
Algolia bug? I've not worked with the Algolia integration before.

Looks like the application id is undefined

```
x-algolia-api-key=ee1b8516c9e5a5be9b6c25684eafc42f&x-algolia-application-id=undefined
```

Not sure what's going on. I am also not sure who set up Algolia or how we can configure it, maybe @afontcu?

**Comment by afontcu** [comment]
hey! yeah I set it up a while ago, and I'd say it worked as expected. Probably something went south during the site transition for vue 2 -> vue 3. I remember we needed to define some tags to split the V1 docs and the V2 ones, but now that might work different as domains are different as well.

For instance, [current config](https://github.com/vuejs/test-utils/blob/main/docs/.vitepress/config.ts#L20-L26) is probably aiming at the old setup (notice the `tags:next` filters). I recall contacting to algolia open source support team, they were really helpful to set up the appropriate config

**Comment by luckylooke** [comment]
Please, searching docs is quite important feature of libraries, thanks 🙏 🙏 🙏

**Comment by lmiller1990** [comment]
If someone wants to pick this up that would be great - you don't need to a member of this repo/org to reach out to Algolia and make this request. I am swamped in 50+ notifications a day with all the projects I work on and won't be able to look into this at this point in time.

Some help from anyone reading this would be greatly appreciated!

**Comment by okxiaoliang4** [comment]
@lmiller1990 Hi, I can help to fix this.
but need you [invite me](https://www.algolia.com/account/teams) to the team :)

**Comment by lmiller1990** [comment]
@okxiaoliang4 what's the fix? Can you just send us a PR?

Due to the nature of this project (millions of downloads / week) we tend to not add people to the team unless there's a compelling reason to do so (many contributions, triaging issues, etc).

**Comment by okxiaoliang4** [comment]
I think the `appId` is missing, but I can't send pr because I can't get the `appId` from Algolia  😀 @lmiller1990

**Comment by lmiller1990** [comment]
Where is the `appId`? How do we get it? I don't know how the Algolia search is configured.

I don't have access to anything you don't. The entire repo is completely OSS. Let me know what you need me to do :+1:
