### ISSUE TITLE
Bug: ReferenceError: Vue is not defined for v2.0.0

### ISSUE THREAD

**Issue by pdsuwwz** [vuejs/test-utils#1525]
**Describe the bug**

In the latest version (v2.0.0), the introduction of `@vue/test-utils` will result in an error.

Minimal reproduction: https://github.com/pdsuwwz/vue-unit/pull/17/files

Related action: https://github.com/pdsuwwz/vue-unit/runs/6535330150?check_suite_focus=true

<img width="605" alt="image" src="https://user-images.githubusercontent.com/19891724/169705791-fdd51bee-89d4-4390-83dc-2dc64c10701f.png">

<img width="714" alt="image" src="https://user-images.githubusercontent.com/19891724/169705403-77d550ce-fa65-49b9-8b27-9ecf6f39a8fd.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/19891724/169705678-e8da08e4-8fe4-440d-a4bb-e4e6f762f56c.png">

**To Reproduce**

Upgrade the version of `@vue/test-utils` from `v2.0.0-rc.21` to `v2.0.0`
https://www.npmjs.com/package/@vue/test-utils/v/2.0.0

**Expected behavior**

Unit test passed.

**Related information:**
- `@vue/test-utils` version: v2.0.0
- `Vue` version: v3.2.35
- `node` version: v14.19.2
- `npm` (or `yarn`) version: v6.14.17

**Additional context**

**Comment by wxsms** [comment]
same issue [here](https://github.com/uiv-lib/uiv/runs/6541495914?check_suite_focus=true)

**Comment by freakzlike** [comment]
Maybe this solution will help https://github.com/vuejs/test-utils/issues/234#issuecomment-1133672109

**Comment by freakzlike** [comment]
Now I faced the same issue in some of my projects which are using jest v28 with `jsdom`.
The solution from https://github.com/vuejs/test-utils/issues/234#issuecomment-1133672109 worked for me 
```
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: [
      'node',
      'node-addons'
    ]
  },
```

When I manually remove the changes of #1484 from the `package.json` then it is working without `testEnvironmentOptions`. I'm not sure what is actually the correct way to fix this.

**Comment by lmiller1990** [comment]
Is this a bug in test utils? Sounds like it's more related to Jest 28 and Vue Jest?

**Comment by stephan-roolvink** [comment]
The fix suggested by @pdsuwwz works 👍

**Comment by lmiller1990** [comment]
This sounds like it is Jest/jsdom, and nothing something in Test Utils... going to close this, unless there's an obvious way to improve things on this end.

**Comment by sheremet-va** [comment]
I think the issue might be on our end. Jest by default uses `browser` field in `exports`. Do we need it? Or is it just for unpkg?

**Comment by lmiller1990** [comment]
Just normally runs in a Node.js environment (using CommonJS modules) so it should be using the `require` field. I am not sure why it's using the browser field, that's definitely incorrect, but I do not think this is an issue in Test Utils - we specify for `require` to use the `cjs` build:

https://github.com/vuejs/test-utils/blob/main/package.json#L14-L15

**Comment by sheremet-va** [comment]
It uses browser field, because jest resolves to it for jsdom (since v28?)

**Comment by lmiller1990** [comment]
Oh, I see. I do not think we can do anything about this here, though. Seems https://github.com/vuejs/test-utils/issues/1525#issuecomment-1134786522 is the solution for now.

**Comment by RaphaelDDL** [comment]
A bit late to the party but just wanted to double check something regarding https://github.com/vuejs/test-utils/issues/1525#issuecomment-1134786522 "fix". 

I have `testEnvironment: 'jsdom',` and without `customExportConditions` or with it set as `browser`, tests fails with `ReferenceError: Vue is not defined`. Expected as per the discussion. So, changing to suggested `node` and `node-addons` does work and tests run. But then, all `window.something` fails pointing to " use jsdom"

```
    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined
```

I have `jest@29`, `jest-environment-jsdom` installed, and I have all expected configs (.vue transform to `@vue/vue3-jest`;  .js transform to `babel-jest`). 

What am I missing to make jsdom features (aka browser window and other implementations) work in test-utils tests?
