### ISSUE TITLE
Bug: An error was reported while running test cases，The version of vue is 3.2.33

### ISSUE THREAD

**Issue by crossskyLi** [vuejs/test-utils#1534]
**Describe the bug**

I updated the Vue to 3.2.33, then reported the error which is like this:

![image](https://user-images.githubusercontent.com/24408773/169995045-6197f951-61b2-48b9-bbd6-b64ef47da666.png)

**To Reproduce**

**Expected behavior**

Hope to adapt to the new version of Vue

**Related information:**
- `@vue/test-utils` version:  2.0.0-rc.18
- `Vue` version: 3.2.33
- `node` version: 16.x
- `npm` (or `yarn`) version: 8.1.x

**Additional context**

**Comment by cexbrayat** [comment]
Hi @crossskyLi 

Can you try to update to the latest release of Vue Test Utils (v2.0.0) please?

Let us know if that fixes your issue

**Comment by crossskyLi** [comment]
> Hi @crossskyLi
> 
> Can you try to update to the latest release of Vue Test Utils (v2.0.0) please?
> 
> Let us know if that fixes your issue

It worked fine when I switched to V2.0
