### ISSUE TITLE
Vue 2 support?

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuejs/test-utils#1561]
Does VTU2 support Vue2?
Is it safe to use VTU2 with Vue2?
Is it recommended to use VTU2 with Vue2, or should we stick with VTU1 until we migrate to Vue3?

**Comment by afontcu** [comment]
Hi!

> Does VTU2 support Vue2?
No, VTU2 was created to target Vue 3.

>  should we stick with VTU1 until we migrate to Vue3?
Exactly. Vue 2 apps will need to be tested using VTU1, and follow the [migration guide](https://test-utils.vuejs.org/migration/) if you update your app from Vue 2 to Vue 3.


Hope it helps!
