### ISSUE TITLE
Bug: Components that use `modelValue` props throw TS overload errors

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/test-utils#1567]
**Describe the bug**

When testing a component in TS that uses a v-model as defined with a `modelValue` prop and a `update:modelValue` emit, TS will throw an error when mounting the component with a ref for the `modelValue`.

**To Reproduce**

Component:
```html
<template>
  <input
    type="text"
    data-test-id="input"
    :value="modelValue"
    @input="update"
  >
  <span data-test-id="tst">{{ modelValue }}</span>
</template>

<script setup lang="ts">
defineProps({
  modelValue: {
    type: String,
    required: true,
  },
})

const emit = defineEmits(['update:modelValue'])

const update = (e: Event) => {
  const val = (e.target as HTMLInputElement).value
  emit('update:modelValue', val)
}
</script>
```

Test:
```ts
import { describe, test, expect } from 'vitest'
import TST from '../tst.vue'
import { nextTick, ref } from 'vue'
import { mount } from '@vue/test-utils'

describe('Input', () => {
  test.only('thing', async () => {
    const text = ref('')
    const wrapper = mount(TST, { //TS will throw a "No overload matches this call."
      props: {
        modelValue: text, // Using text.value makes TS happy, but obviously you lose reactivity so you can't test.
      },
    })

    expect(wrapper.find('[data-test-id="tst"]').text()).toBe('')

    text.value = 'foo'
    await nextTick()

    expect(wrapper.find('[data-test-id="tst"]').text()).toBe('foo')
  })
})
```

**Expected behavior**

TS to accept a ref to be passed in as the `modelValue`.

**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.20
- `Vue` version: 3.2.20
- `node` version: 16.14.0
- `npm` (or `yarn`) version: 8.3.1

**Additional context**

Tests run fine and builds work too, so it's really just an issue inside the IDE.

**Comment by cexbrayat** [comment]
Hi @TheDutchCoder 

Can you try to update VTU to v2.0.0 and Vue to v3.2.34 to make sure that this is not fixed in more recent releases?

**Comment by freakzlike** [comment]
You should use `setProps` instead of a ref as prop. Because the `modelValue` should be of type `string` and not of `Ref<string>`. Try this solution:

```typescript
import { describe, test, expect } from 'vitest'
import TST from '../tst.vue'
import { mount } from '@vue/test-utils'

describe('Input', () => {
  test.only('thing', async () => {
    const wrapper = mount(TST, {
      props: {
        modelValue: ''
      },
    })

    expect(wrapper.find('[data-test-id="tst"]').text()).toBe('')

    await wrapper.setProps({
      modelValue: 'foo'
    })

    expect(wrapper.find('[data-test-id="tst"]').text()).toBe('foo')
  })
})
```
https://test-utils.vuejs.org/guide/essentials/passing-data.html#using-setprops

**Comment by TheDutchCoder** [comment]
> Hi @TheDutchCoder
> 
> Can you try to update VTU to v2.0.0 and Vue to v3.2.34 to make sure that this is not fixed in more recent releases?

Updating both seemed to have worked, thanks!
2.0.0 just crashes in VSCode when running tests (opened a bug for that), but it works in iTerm, so thanks!
