### ISSUE TITLE
Bug: 2.0 crashes in VSCode on Mac M1

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/test-utils#1568]
**Describe the bug**

I just updated to 2.0 and when I run my tests in VSCode's terminal it crashes after a few of them:
![image](https://user-images.githubusercontent.com/1668207/171878659-69eae610-8afe-4b7c-b0fb-32bf70510e20.png)

**To Reproduce**

Not sure how easy/hard it is to reproduce, but I upgraded fro 2.0.0.-rc20 to 2.0.0 and when running vitest the whole thing crashes in VSCode but not in iTerm

**Expected behavior**

No crashes to happen

**Related information:**
- `@vue/test-utils` version: 2.0.0
- `Vue` version: 3.2.20
- `node` version: 16.14.0
- `npm` (or `yarn`) version: 8.3.1

**Additional context**

**Comment by cexbrayat** [comment]
I don't think this is really related to VTU, this is more probably an issue with your node version and maybe vitest version
(my teams are running VTU on M1, and when we encounter this kind of issue, it's related to vitest) 

Can you try with an updated nodejs (v16.15.1 is the latest) and update to the latest vitest release?
If you still encounter the issue, try to isolate a reproducible test case and open an issue on vitest.

**Comment by TheDutchCoder** [comment]
> I don't think this is really related to VTU, this is more probably an issue with your node version and maybe vitest version (my teams are running VTU on M1, and when we encounter this kind of issue, it's related to vitest)
> 
> Can you try with an updated nodejs (v16.15.1 is the latest) and update to the latest vitest release? If you still encounter the issue, try to isolate a reproducible test case and open an issue on vitest.

That did the trick. Looks like node was the culprit, sorry for opening the issue (it happened when upgrading test-utils, hence the report)
