### ISSUE TITLE
add link to eslint-plugin-vue-test-utils to readme?

### ISSUE THREAD

**Issue by snoozbuster** [vuejs/test-utils#1610]
This is not a super conventional way of asking this, but it's the easiest way I know of to get in touch. I recently published [eslint-plugin-vue-test-utils](https://www.npmjs.com/package/eslint-plugin-vue-test-utils) to help with best practices and fixing deprecations for VTU. I'd love to get more of the community using it and contributing to it - is it worthwhile/valuable to add a link to the project from VTU's readme? (given that most of the rules help with fixing v1 deprecations - maybe a link in the VTU 1 -> 2 migration guide?)

**Comment by lmiller1990** [comment]
Sure thing, we can link to it from the docs and/or README. Let's make a note it's a third party library, so people don't report issues relating to it in this repo, but the correct one.

**Comment by snoozbuster** [comment]
sweet. I will open a PR Soon (tm) - hopefully next week if I can find a spare moment.
