### ISSUE TITLE
Bug: Running tests with both script setup and script error

### ISSUE THREAD

**Issue by VividLemon** [vuejs/test-utils#1617]
**Describe the bug**

This happens only under specific circumstances. This could also be a vitest issue, but I think it's a test util problem.

When using script setup and script in the same component, if a required item is imported inside the script setup portion, the test will error out. Read below
**To Reproduce**
Create a component
Create <script setup lang="ts">
import {defineComponent} from 'vue' // for example, this is where I had my issue
then create normal <script lang="ts">
then attempt to export default defineComponent({}) // This is completely fine when building, and running in dev, however, the test will always fail. `ReferenceError: Cannot access '__vite_ssr_import_1__' before initialization`

So an import in script setup will cause a test error when attempted to be called in regular script. I imagine it happens with other variables, but is most of an issue when trying to use defineComponent. Unsure of why this would happen since script setup is compiled down. 
**Expected behavior**

It should run the test just fine, similar to how building would be fine
**Related information:**
- `@vue/test-utils` version: 2.0.0-rc.18
- `Vue` version: Observe stackblitz link below, vue-tsc 0.38.1 && vite 2.9.12
- `node` version: 16.14.2
- `npm` (or `yarn`) version: 7.17.0

**Additional context**

https://stackblitz.com/edit/vitejs-vite-suaivh?file=src/components/HelloWorld.vue
Read the comments I placed, uncomment out and test around with the two imports. One works, the other doesn't. Both should be valid for Vue

**Comment by cexbrayat** [comment]
Hi @kwiksilver3441 

Thanks for the repro. I tend to think this is probably an issue with Vitest, as VTU doesn't do anything special as you're pointing out, and the error is very "vite-specific". I'm surprised that this even works at all with Vite (I tried to repro with Webpack and this does not even build). But anyway if that works with Vite, that should probably work with Vitest?

Would you mind opening an issue on the Vitest repo?

I'll close this one for now as I don't think we can help. I'm happy to re-open if this is not tooling-related.
