### ISSUE TITLE
Bug: upgrade 2.0.0  Assertion failure and error

### ISSUE THREAD

**Issue by yanzhangshuai** [vuejs/test-utils#1631]
Describe the bug

Updating from "@vue/test-utils": "2.0.0-rc.21" to "@vue/test-utils": "2.0.0",  Assertion failure and get error

![image](https://user-images.githubusercontent.com/31086862/176656893-dd7218ad-98c4-4b44-85a4-04be6210de42.png)
![image](https://user-images.githubusercontent.com/31086862/176656927-e8644a89-a72f-4696-8862-7a14a42185cc.png)
![image](https://user-images.githubusercontent.com/31086862/176656952-6b6e7114-59e4-4127-9a09-ce300eabf9d0.png)
![image](https://user-images.githubusercontent.com/31086862/176656976-0d4bc249-1d5a-445d-9ae0-4c5302bc782a.png)
![image](https://user-images.githubusercontent.com/31086862/176657033-5c3dc5ab-0eda-4928-bdd8-ab0eb863accc.png)

Expected behavior
All tests should pass as they are doing in the version 2.0.0-rc.21.

Related information:
*  `@vue/test-utils version`: 2.0.0
*  `vue`: 3.2.37
*  `vitest`:  0.16.0
*  `node`: 16.13.2

**Comment by cexbrayat** [comment]
Hi @yanzhangshuai 

Can you provide a minimal reproduction in a github repo if you think this is an issue with VTU? It's hard to know what's going on without that.

Note that v2.0.0 fixed a few things on how VTU finds elements in templates with multiple roots, so maybe you have to adapt your tests.

**Comment by yanzhangshuai** [comment]
> 嗨@yanzhangshuai
> 
> 如果您认为这是VTU的问题，是否可以在github存储库中提供最小的复制？如果没有这一点，很难知道发生了什么。
> 
> 请注意，v2.0.0 修复了一些关于 VTU 如何在具有多个根的模板中查找元素的问题，因此也许您必须调整测试。



> Hi @yanzhangshuai
> 
> Can you provide a minimal reproduction in a github repo if you think this is an issue with VTU? It's hard to know what's going on without that.
> 
> Note that v2.0.0 fixed a few things on how VTU finds elements in templates with multiple roots, so maybe you have to adapt your tests.

**Comment by cexbrayat** [comment]
@yanzhangshuai I took a quick look and both of your issues are caused by `mainFields` in your vitest config.

If you comment this line both tests should succeed. 
```diff
- mainFields: ['index', 'module', 'jsnext'],
+ // mainFields: ['index', 'module', 'jsnext'],
```
Hope that helps!

**Comment by yanzhangshuai** [comment]
> ```diff
> mainFields
> ```

Thank's. You're right

**Comment by yanzhangshuai** [comment]
> @yanzhangshuai I took a quick look and both of your issues are caused by `mainFields` in your vitest config.
> 
> If you comment this line both tests should succeed.
> 
> ```diff
> - mainFields: ['index', 'module', 'jsnext'],
> + // mainFields: ['index', 'module', 'jsnext'],
> ```
> 
> Hope that helps!

Thank's. You're right
