### ISSUE TITLE
Bug: `Using a real router with Composition API` example is missing `push`

### ISSUE THREAD

**Issue by N8ers** [vuejs/test-utils#1632]
**Describe the bug**
In the docs there is a code example for [Using a real router with Composition API](https://github.com/vuejs/test-utils/blob/main/docs/guide/advanced/vue-router.md). Here is the code example in it's current state:
```js
import { mount, flushPromises } from '@vue/test-utils'
import { createRouter, createWebHistory } from 'vue-router'
import { routes } from "@/router"

let router;

beforeEach(async () => {
  router = createRouter({
    history: createWebHistory(),
    routes: routes,
  })

  router.push('/')
  await router.isReady()
});

test('allows authenticated user to edit a post', async () => {
  const wrapper = mount(Component, {
    props: {
      isAuthenticated: true
    },
    global: {
      plugins: [router],
    }
  })

  await wrapper.find('button').trigger('click')

  expect(push).toHaveBeenCalledTimes(1)
  expect(push).toHaveBeenCalledWith('/posts/1/edit')
})
```
 
In the assertion `expect(push).toHaveBeenCalledTimes(1)`, we access the `push` variable, but `push` is not defined anywhere. 

How should that be handled? Am I just missing something? I'd be happy to put up a PR for it if anyone has an answer!

**Comment by cexbrayat** [comment]
Hi @N8ers 

You're right, push is not defined here.

I suppose the test should look like:

```ts
test('allows authenticated user to edit a post', async () => {
  const wrapper = mount(Component, {
    props: {
      isAuthenticated: true
    },
    global: {
      plugins: [router],
    }
  })

  const push = jest.spyOn(router, 'push');
  await wrapper.find('button').trigger('click')

  expect(push).toHaveBeenCalledTimes(1)
  expect(push).toHaveBeenCalledWith('/posts/1/edit')
})
```

This is pseudo-code though, I haven't tested it.
If you're interested in opening a PR, can you check that this properly works and update the docs if that's the case?
That would be a great help!

**Comment by N8ers** [comment]
Hey @[cexbrayat](https://github.com/cexbrayat)!

Okay cool, I'm glad I didn't miss something. I can confirm that that worked for me. I'm using vitest not jest, but I'm confident it will be fine.

I'll make a PR and link it to this issue - thanks for the help 😄

**Comment by N8ers** [comment]
I've submitted [this PR](https://github.com/vuejs/test-utils/pull/1635) to update the documentation!
