### ISSUE TITLE
Bug: component is not receiving props

### ISSUE THREAD

**Issue by thany** [vuejs/test-utils#1651]
**Describe the bug**
The literal example from the [Getting Started](https://test-utils.vuejs.org/guide/) page doesn't work. The `MessageComponent` renders to `<p></p>`, completely ignoring the `msg` prop. After some investigation testing a real component, it turns out the props given it by the `mount` function never arrive at the component. They are lost in transit somewhere.

**To Reproduce**
Copypaste the first code example from the Getting Started page.

**Expected behavior**
The test in the example succeeds.

**Related information:**
- `@vue/test-utils` version: ^1.3.0
- `Vue` version: ^2.6.14
- `node` version: 16.15.1
- `npm` version: 8.13.2

**Additional context**
* Had to install `babel-jest` to get `import` to work. This is never mentioned.
* Had to set `modules` in the `@babel/preset-env` plugin to `"commonjs"`. This is also mentioned nowhere.
* Had to install `jest-environment-jsdom` to get anything to work at all. This was also not mentioned.

Relevant jest config that, again, is not mentioned how to set up properly, so this is gathered together from bits&pieces of internet and a lot of trial&error:
```javascript
module.exports = {
  transform: {
    "\\.(js|ts|jsx|tsx)$": "babel-jest",
    "\\.vue$": "@vue/vue2-jest",
  },
  transformIgnorePatterns: [
    "\\\\node_modules\\\\",
  ],
  testEnvironment: "jsdom",
  moduleFileExtensions: [
    "js",
    "json",
    "vue",
  ]
};
```

If I hadn't done any of the above (so just install `jest` and `@vue/test-utils` and call it a day), it doesn't work - and how on earth could it? So apart from props not arriving at a component in its simplest possible form, the getting started guide is too sparse. Maybe if it were more complete, I would have the correct configuration where props do arrive at a component.

**Comment by thany** [comment]
After some more trial & error, which is not a good thing to be doing after just having installed this toolkit, I come up with several findings:

* Using `propsData` instead of `props` seems to pass the `msg` prop as intended. But I don't know why this works, and `props` doesn't. I can't figure out what, if any, the difference is between the two.
* A bit [further into the documentation](https://test-utils.vuejs.org/guide/essentials/passing-data.html#using-props-to-set-a-minimum-length) it mentions the use of a `data()` function passed into the `mount` function. It is not explained why this is done, nor what the difference is between it, and passing `props` (or indeed `propsData`). In any case, it too doesn't work, which is a bad thing to be having in the documentation. Please update according to how it really works.
* In that same bit of documentation, the examples seem to be using `props` in a very different way - it doesn't seem like actual props, more like proptypes. If this is correct, then I fail to understand why you'd pass that into `mount` - surely proptypes go in the component itself, not in its implementation/test.

**Comment by cexbrayat** [comment]
Hi @thany 

Thank you for your feedback, but this is the repository for test-utils v2 that is intended for Vue 3.

It looks like you're trying to use test-utils v1 with Vue 2, so you need to check the documentation here https://vue-test-utils.vuejs.org/

The example you talk about works properly in Vue 3/VTU v2, see https://stackblitz.com/edit/vitest-dev-vitest-xowrxf?file=test%2Fbasic.test.ts&initialPath=__vitest__ 

If you have feedback about VTU v1 docs, please open an issue on https://github.com/vuejs/vue-test-utils/ (the repository for v1)

**Comment by thany** [comment]
Why is the API of test-utils different then? With the knowledge of both vue2 and vue3 existing, you could've opted for consistency. This would also have reduced the burden of an upgrade to vue3. Yet, you chose to keep it confusing.

Btw, how was I supposed to know? There is no version number of any kind on the documentation. I don't think I could've known this. Maybe add a version switch *at the very very least*?
