### ISSUE TITLE
bug: global is not part of the mount options type

### ISSUE THREAD

**Issue by jofaval** [vuejs/test-utils#1653]
**Describe the bug**
Typescript warned me that `mount` and `shallowMount` do not take `global` as an argument and that it does not exist as a mounting options parameter.

**To Reproduce**

1. Use the following package.json for the dependencies [https://github.com/jofaval/gh-btc-vue-final/blob/v1.1/package.json](https://github.com/jofaval/gh-btc-vue-final/blobv1.1/package.json).
2. Attempt to add the `mock` property inside the `global` key when mounting the component for testing as per the [official docs](https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-mocked-router).
3. I've used the following file: [https://github.com/jofaval/gh-btc-vue-final/blob/v1.1/tests/unit/views/PostDetailView.spec.ts](https://github.com/jofaval/gh-btc-vue-final/blob/v1.1/tests/unit/views/PostDetailView.spec.ts) but it also happened on the sibling views.
4. Typescript should, at that point, indicate that global does not exist in the `FunctionalComponentMountOptions<Vue>`, it does not work with `id` instead of `postId`
```
Object literal may only specify known properties, and 'global' does not exist in type 'FunctionalComponentMountOptions<Vue>'.
```
5. Attempt to run the tests and get the following error log:
```
      tests/unit/views/PostDetailView.spec.ts:40:7 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type '{ global: { mocks: { $route: { params: { postId: number; }; }; $router: { push: jest.Mock<any, any>; }; }; }; }' is not assignable to parameter of type 'FunctionalComponentMountOptions<Vue>'.
          Object literal may only specify known properties, and 'global' does not exist in type 'FunctionalComponentMountOptions<Vue>'.

     40       global: {
              ~~~~~~~~~
     41         mocks: {
        ~~~~~~~~~~~~~~~~
    ...
     44         },
        ~~~~~~~~~~
     45       },
        ~~~~~~~

      node_modules/@vue/test-utils/types/index.d.ts:193:25
        193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                    ~~~~~
        The last overload is declared here.
    tests/unit/views/PostDetailView.spec.ts:63:7 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type '{ global: { mocks: { $route: { params: { postId: number; }; }; $router: { push: jest.Mock<any, any>; }; }; }; }' is not assignable to parameter of type 'FunctionalComponentMountOptions<Vue>'.
          Object literal may only specify known properties, and 'global' does not exist in type 'FunctionalComponentMountOptions<Vue>'.

     63       global: {
              ~~~~~~~~~
     64         mocks: {
        ~~~~~~~~~~~~~~~~
    ...
     67         },
        ~~~~~~~~~~
     68       },
        ~~~~~~~

      node_modules/@vue/test-utils/types/index.d.ts:193:25
        193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                    ~~~~~
        The last overload is declared here.
```

**Expected behavior**
Typescript should recognize global as part of the `FunctionalComponentMountOptions<Vue>` type.

**Related information:**
- `@vue/test-utils` version: ^1.1.3
- `Vue` version: ^2.6.14
- `node` version: v15.14.0
- `npm` (or `yarn`) version: 8.11.0

**Additional context**
When cexbrayat reviewed my PR [https://github.com/vuejs/test-utils/pull/1649](https://github.com/vuejs/test-utils/pull/1649), I thought `mocks` were at the same level than `propsData` and it was a matter of updating the documentation, he let me know that global still existed and that mocks should be inside it.

In case this is an issue to fix and not something that I, as a newcomer to Vue's ecosystem did not configured properly, please let me know if you'd like a completely new repository replicating the bug, or a branch from the repo it happened in with as less code as possible.

Thanks!!

**Comment by cexbrayat** [comment]
Thanks @jofaval 

It looks like you're using Vue 2 and VTU v1: this is the repo for VTU v2, that only works with Vue 3.
Maybe you had the same issue with the docs: the docs for VTU v1 are here https://vue-test-utils.vuejs.org/

And indeed, in VTU v1, mocks are a property at the same level as props IIRC.

So I'm closing this issue: if you have an issue with the docs of VTU v1, the proper Github repository is https://github.com/vuejs/vue-test-utils

**Comment by jofaval** [comment]
Hello @cexbrayat ,

Thank you very much for your time and patience, you're totally right and it makes so much sense.

I'm sorry for the confussion and once again, thank you, have a nice day!
