### ISSUE TITLE
Bug: Reactivity issues with @vue/compat

### ISSUE THREAD

**Issue by Weetbix** [vuejs/test-utils#1665]
**Describe the bug**
Reactivity does not seem to work when using the vue compat build.

For example all these tests will work with vue 3, but all will fail with @vue/compat:

```javascript
import {ref, onMounted, defineComponent} from 'vue';
import {it, expect} from 'vitest';
import {mount} from '@vue/test-utils';

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

const TestAsync = defineComponent({
    template: '<div><div>{{ mountText }}</div><div>{{ asyncText }}</div></div>',

    props: {
        done: Function,
    },
    setup({ done }) {
        const mountText = ref();
        const asyncText = ref();

        onMounted(() => {
            mountText.value = 'mounted';
        });

        sleep(0).then(() => {
            asyncText.value = 'async';
            done?.();
        });

        return {
            mountText,
            asyncText,
        };
    },
});

it('should show onMount text', () => new Promise(done => {
    const wrapper = mount(TestAsync);
    wrapper.vm.$nextTick(() => {
        expect(wrapper.html()).toMatch('mounted')
        done();
    });
}));

it('should show async text', async () => {
    let renderedAsyncResolve;
    const renderedAsync = new Promise(resolve => renderedAsyncResolve = resolve);

    const wrapper = mount(TestAsync, {
        propsData: { done: renderedAsyncResolve }
    });

    await renderedAsync;
    expect(wrapper.html()).toMatch('async');
});

it('should show async text with nextTick', () => new Promise(async (done) => {
    let renderedAsyncResolve;
    const renderedAsync = new Promise(resolve => renderedAsyncResolve = resolve);

    const wrapper = mount(TestAsync, {
        propsData: { done: renderedAsyncResolve }
    });

    await renderedAsync;
    wrapper.vm.$nextTick(() => {
        expect(wrapper.html()).toMatch('async');
        done();
    });
}));
```

**To Reproduce**
Check out this repo on the `jh/vue-utils-version` branch: https://github.com/Weetbix/vue-compat-composition-api-bug-repo/blob/jh/vue-utils-version/test.spec.js

Run `yarn test:vue3` to run in vue 3 and notice all tests pass.

Run `yarn test:vue-compat` to run with the vue compat alias, notice all tests fail.

**Expected behavior**
All tests should pass when running in compat mode. The templates/output should update to reflect the new values.

**Related information:**
- `@vue/test-utils` version: `2.0.2`
- `Vue` version: `3.2.37`
- `node` version: `16.13.2`
- `npm` (or `yarn`) version: yarn `1.22.19`

**Additional context**

Originally raised in vue testing library: https://github.com/testing-library/vue-testing-library/issues/275
Similar issues in vue 2.7 but seems to be caused by `vue-jest`: https://github.com/vuejs/vue-test-utils/issues/1983

**Comment by lmiller1990** [comment]
Curious, what if you try using `flushPromises`?

```js
import { flushPromises } from '@vue/test-utils'


    const wrapper = mount(TestAsync, {
        propsData: { done: renderedAsyncResolve }
    });

    await renderedAsync;
    await flushPromises()
    wrapper.vm.$nextTick(() => {
        expect(wrapper.html()).toMatch('async');
        done();
    });
```

Is this just a race condition?

**Comment by Weetbix** [comment]
Hey @lmiller1990 :)

I added a test with flush promises and got the same results (works with vue 3, doesnt work with compat alias):
```js
it('with flushPromises', () => new Promise(async (done) => {
    let renderedAsyncResolve;
    const renderedAsync = new Promise(resolve => renderedAsyncResolve = resolve);

    const wrapper = mount(TestAsync, {
        propsData: { done: renderedAsyncResolve }
    });

    await renderedAsync;
    await flushPromises();
    wrapper.vm.$nextTick(() => {
        expect(wrapper.html()).toMatch('async');
        done();
    });
}));
```
https://github.com/Weetbix/vue-compat-composition-api-bug-repo/commit/f0282f91a1a75564c7a4e9b89648fc72824c4102

I think checking for the race condition was my original intention behind the `done` prop and awaiting `renderedAsync`;

**Comment by Weetbix** [comment]
@lmiller1990 any news on this? It seems that this issue makes `@vue/compat` not a viable upgrade path because any components written with the composition api (previously using `@vue/composition-api`) will not pass tests. I imagine this would affect a lot of people trying to upgrade.

Is it possibly the same issue as this? https://github.com/vuejs/vue-test-utils/issues/1982#issuecomment-1201131222

I'm not sure, because to use compat we have to set the vue alias, so I don't think there could be two imports resolving to different distributions..

Let me know if there is anything I can do to help! 🙏

**Comment by lmiller1990** [comment]
I tried to reproduce in this code base so we could start working on a fix, but they all seem to pass, even in compat mode: https://github.com/vuejs/test-utils/compare/issue-1665?expand=1.

**Comment by lmiller1990** [comment]
Here is a more minimal example for debugging

## package.json

```js
{
  "dependencies": {
    "@vue/compat": "^3.2.37",
    "@vue/test-utils": "^2.0.2",
    "global-jsdom": "8.5.0",
    "jsdom": "20.0.0",
    "vue": "^3.2.37"
  },
  "type": "module"
}
```

## `index.mjs`

```js
import 'global-jsdom/register'
import {mount, flushPromises} from '@vue/test-utils';
import pkg from '@vue/compat';
const {ref, onMounted, defineComponent} = pkg

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const TestAsync = defineComponent({
  template: '<div><div>{{ mountText }}</div><div>{{ asyncText }}</div></div>',

  props: ['done'],

  setup({ done }) {
    const mountText = ref();
    const asyncText = ref();

    onMounted(() => {
      mountText.value = 'mounted';
    });

    sleep(0).then(() => {
      asyncText.value = 'async';
      done?.();
    });

    return {
      mountText,
      asyncText,
    };
  },
});

function main () {
  const wrapper = mount(TestAsync);

  return new Promise(resolve => {
    setTimeout(async () => {
      await flushPromises();
      await flushPromises();
      await flushPromises();
      console.log(wrapper.html())
      resolve()
    }, 100)
  })
}

main()
```

**Comment by lmiller1990** [comment]
Edit: got it work with Jest as well, I configured `moduleNameMapper` in `package.json` under `jest`. https://github.com/lmiller1990/jest-vtu-compat-error

cc @Weetbix - this seems like a Vite bug?

**Comment by cexbrayat** [comment]
I'll close this, as the upstream issue in Vitest mentions the proper solution (this was not an issue in VTU)

See https://github.com/vitest-dev/vitest/issues/1886
