### ISSUE TITLE
Feature request: (type): Add optional element type argument

### ISSUE THREAD

**Issue by nandi95** [vuejs/test-utils#1689]
**Is your feature request related to a problem? Please describe.**
I would like to have the element on the wrapper typed in the tests, so I could have all the type hints.
This Is currently typed as `Element`
https://github.com/vuejs/test-utils/blob/036e201b520b0a0221feec8d9731e59abb511fd1/src/vueWrapper.ts#L158

**Describe the solution you'd like**
I'm aware that vue types their `$el` as any as there is no good solution here

https://github.com/vuejs/core/blob/a95554d35c65e5bfd0bf9d1c5b908ae789345a6d/packages/runtime-core/src/componentPublicInstance.ts#L192

but perhaps we could add a second type argument `E extends Element = Element`
This would be helpful in testing non fragmented components like https://github.com/karnama/vueish/blob/main/src/components/button/UIButton.vue

This type argument could also be passed into the base wrapper instead of `T['$el']` (which equates to `any`)

**Describe alternatives you've considered**
I could just cast as `(wrapper.element as HTMLButtonElement)`

**Comment by lmiller1990** [comment]
If only `element` was a function we could make it generic.

Where would we add the type arg? I think I'm missing something.

**Comment by nandi95** [comment]
In the constructor like so
```ts
export class VueWrapper<
  T extends Omit<
    ComponentPublicInstance,
    '$emit' | keyof ComponentCustomProperties
  > & {
    $emit: (event: any, ...args: any[]) => void
  } & ComponentCustomProperties = ComponentPublicInstance,
  E extends Element = Element
> extends BaseWrapper<E> {
.
.
.
```
but yeah looking over where to add it in the `mount` I'm not sure. Can only really be the last argument otherwise it's breaking 😩

**Comment by lmiller1990** [comment]
I wonder if we just add a `getElement` that's generic:

```js
getElement<T extends Element = Element>() {
  return this.element as T
}
```

Again not really ideal, but better than a breaking change just to alleviate the need for a type cast.

**Comment by nandi95** [comment]
At that point the isn't much difference between
```ts
wrapper.element as HTMLButtonElement
```
vs
```ts
wrapper.getElement<HTMLButtonElement>()
```
The advantage in the constructor would be that you don't need to assert it `as` every time
But again, thinking of it, I could just do
```ts
const wrapper = mount(MyComp, ...) as unknown as ReturnType<typeof mount<typeof UIButton, maybe_props_typed_here>> & { element: HTMLButtonElement };
``` 

If you haven't got a better idea, then I think this can be closed 😅

**Comment by lmiller1990** [comment]
I'm thinking the type cast is likely the best solution at this point in time.
