### ISSUE TITLE
Bug: isVisible always returns true

### ISSUE THREAD

**Issue by Druckles** [vuejs/test-utils#1704]
**Describe the bug**

If I use `isVisible()` on an element with `display: none`, it will always return `true`. 

**To Reproduce**

```vue
// TestComponent.vue
<script setup>
import {ref} from 'vue';

const active = ref(false);

</script>

<template>
  <a @click="active = !active" id="button">Show list</a>
  <ul :class="{active}" id="underTest">
    <li>Apple</li>
    <li>Banana</li>
  </ul>
</template>

<style>
ul:not(.active) {
  display: none;
}

ul.active {
  display: block;
}
</style>
```

```typescript
// TestComponent.spec.ts
import {describe, test} from 'vitest';
import {mount} from '@vue/test-utils';
import TestComponent from './TestComponent.vue';
import {expect} from 'vitest';

describe('TestComponent', () => {
    test('starts invisible', async () => {
        const component = mount(TestComponent);
        const list = component.get('#underTest');
        expect(list.isVisible()).toBe(false);
        await component.trigger('#button');
        expect(list.isVisible()).toBe(true);
    })
})
```

```
vitest --environment jsdom
```

**Expected behavior**

The above test should be green. The start state is hidden (`isVisible === false`) and after the link is clicked it should be visible. It fails at the first `expect`, however. Switching the expectations doesn't work, neither does the following:

```typescript
const component = mount(TestComponent);
const list = component.get('#underTest');
const startState = list.isVisible();
await component.trigger('#button');
expect(list.isVisible()).toBe(!startState);
```

The component runs in the browser as expected: the list is hidden, the link is clicked, the list is visible.

Moving `#underTest` to a child `li` doesn't produce a different result, i.e. the "ancestors" are also "visible".

happy-dom doesn't do it any better than jsdom.

**Related information:**

- `@vue/test-utils` version: 2.0.0
- `Vue` version: 3.2.37
- `node` version: 16.16.0
- `npm` (or `yarn`) version: 8.11.0
- `vite` version: 2.9.12

**Additional context**

I have tried testing this some other way, but the "element" (under `list.element`) is not a `HTMLElement` so I can't use a library like `@testing-library/jest-dom`. I also see no way of explicitly getting the styles of an element, so I have no workaround.

**Comment by Tubring25** [comment]
got the same problem

**Comment by Druckles** [comment]
As explained above, this occurs with both `jsdom` and `happy-dom`.

**Comment by Druckles** [comment]
The solution is to use Vue's native `v-show` attribute instead of the class `.active` like in the example above. It still seems odd that it doesn't pick up on the styles.

**Comment by lmiller1990** [comment]
Not directly to address this, but Cypress solves this problem with a more robust visibility algorithm + real browser, if that's something you are interested in. You also can't be 100% sure the element is actually showing/hiding without rendering a real browser. You might be interested in checking it out.

In general I have encountered bugs when doing anything around CSS using jsdom/HappyDOM - they don't implement a full rendering engine, so you cannot always rely on them for features relating to CSS.

**Comment by cexbrayat** [comment]
I dug a little and it turns out Vitest disables CSS by default, hence the issue.

You need to add `css: true` to the vitest config, and the test you shared succeeds

See https://stackblitz.com/edit/vitest-dev-vitest-hmv4hr?file=vitest.config.ts
