### ISSUE TITLE
Feature request: nextFrame() or transitionFinish() hook to test onafterleave hook of Transition or TransitionGroup

### ISSUE THREAD

**Issue by Sepush** [vuejs/test-utils#1709]
**Is your feature request related to a problem? Please describe.**

I'm try to migrate frome jest to vitest
in jest I use settime(()=>{},0) to test onAfterLeave hook but in vitest this didn't work
I'm try to find out some way properly to test the onAferLeave

![image](https://user-images.githubusercontent.com/39197136/183251442-600ed762-8223-4fec-88b9-ca03ed524f34.png)

vue core test the following way
![image](https://user-images.githubusercontent.com/39197136/183251481-e77ed6de-e142-46ed-8941-6b1fbfb15017.png)

**Describe the solution you'd like**

I found that vuejs/core use these hook to test is
so If test-utils can provide these hook that will be great.
[vue core test transition](https://github.com/vuejs/core/blob/main/packages/vue/__tests__/Transition.spec.ts )
**Describe alternatives you've considered**

**Additional context**

**Comment by lmiller1990** [comment]
If it worked in Jest but not Vitest, it is a Vitest bug? Should it be reported there?

**Comment by cexbrayat** [comment]
@Sepush There is no reason that a test that worked with Jest would not with Vitest (we ported several code bases from one to the other). Did you reach out to the Vitest team to solve your issue? 

I'll close for now, and if the Vitest team can't help with your issue, then we'll revisit and see if VTU needs to add a specific API for that. In that case, feel free to reopen the issue with a minimal repro and we'll take a look (you can even open a PR with a failing test, as this codebase uses Vitest).
