### ISSUE TITLE
Bug:  export 'staticRenderFns' was not found in './Todo.vue?vue&type=template&id=e107d2f8&'

### ISSUE THREAD

**Issue by mariadb-ThienLy** [vuejs/test-utils#1711]
**Describe the bug**
Hi, I understand that you have no bandwidth to support some new features in Vue 2.7, but if I don't use any new features in 2.7 all of my tests are still failing with this error:
` export 'render' was not found in './Todo.vue?vue&type=template&id=e107d2f8&'`
`export 'staticRenderFns' was not found in './Todo.vue?vue&type=template&id=e107d2f8&'`

**Expected behavior**
Is there any workaround for this?

**Related information:**
- `@vue/test-utils` version: 1.3.0
- `Vue` version: 2.7.8
- `node` version: 16.16.0
- `npm` (or `yarn`) version: 8.11.0

**Comment by cexbrayat** [comment]
Hi 

This repo is for VTU v2 which only supports Vue 3. For VTU v1, please open an issue on https://github.com/vuejs/vue-test-utils
