### ISSUE TITLE
Bug: Setting computed value

### ISSUE THREAD

**Issue by walmartwarlord** [vuejs/test-utils#1719]
Is it possible in VTU 2 to set initial computed data from a setup function? We can do it in Options API:

```js
{
  computed: {
    hospitalId () {
      return this.aSampleDataKey
    }
  }
}
```

Then we can set the value of it manually in tests like

```js
wrapper = mount({
  computed: { hospitalId: () => 69 },
})
```

This doesn't work in Composition API

```js
const hospitalId = computed(() => aSampleDataKey.value)

return { hospitalId }
```

Is it possible to set computed value like this one?

```js
wrapper = mount({
  computed: { hospitalId: () => 69 },
})
```

**Comment by freakzlike** [comment]
It is not possible to set the value of a `computed` with the composition API. As you can see in the `mount` API Reference (https://test-utils.vuejs.org/api/#mount) there is not `computed` option.

Depending in your case I would:
1. Test the real behavior

or if not possible/too complicated to test

2. Use a composable file and mock it

In case you need some help with a specific case, you can open a discussion
