### ISSUE TITLE
Bug: Whitespace is always condensed in snapshots

### ISSUE THREAD

**Issue by kazvaggos** [vuejs/test-utils#1732]
**Describe the bug**

Hello team. We noticed that the whitespace in the output snapshots is always condensed. We tried to set `global.config.compilerOptions.whitespace: 'preserve'`, in the mounting option but we noticed from the types that it is not supported.
Is it possible to add the support for the 'preserve' whitespace or is there any other workaround? 
Our webpack compiler option of `vue-loader` is with `whitespace: 'preserve'` so it would be great the output snapshot to be the same with the compiled html.
Thanks in advance.

**To Reproduce**

You can generate a snapshot for this html
```html
<span>span1</span>
<span>span2</span>
```
The output shapshot will always be
```html
<span>span1</span><span>span2</span>
```

**Expected behavior**

The expected snapshot with compiler option `whitespace: 'preserve'` should be
```html
<span>span1</span> <span>span2</span>
```

**Related information:**
- `@vue/test-utils` version: 2.0.2 
- `Vue` version: 3.2.37
- `node` version: 16.13.2
- `npm` (or `yarn`) version: 8.1.2

**Additional context**

N/A

**Comment by cexbrayat** [comment]
This is expected: compiler options are not handled by VTU.

If you use vue-jest, you have to set the compiler options in jest options. Check out vue-jest readme for more info https://github.com/vuejs/vue-jest#compiler-options-in-vue-3

If you use vite and vitest, set the option in Vite config.
