### ISSUE TITLE
Disabled attribute gets set to 'false' instead of removing the attribute

### ISSUE THREAD

**Issue by Ken-vdE** [vuejs/test-utils#1760]
I had already tried to fix the issues through this pull request: https://github.com/vuejs/test-utils/pull/1759 .
After that I thought the problem lied within happy-dom, closed that pull request and I created an issue there https://github.com/capricorn86/happy-dom/issues/578 .

After trying it again with jsdom within my project I found the issue persists.

**Describe the bug**

It seems the disabled attribute of a button gets set to 'false' instead of being removed.

**To Reproduce**

```vue
<template>
   <component :is="type" :disabled="index > 1" @click="$emit('something')" data-testid="button"/>
</template>
```
with a test like this:
```javascript
const wrapper = mount(Component, { props: { type: 'button' } })
const button = wrapper.find('[data-testid="button"]')
await button.trigger('click');
expect(wrapper.emitted()).toHaveProperty('something')
```

**Expected behavior**

The emit should be called, however it is not. [baseWrapper](https://github.com/vuejs/test-utils/blob/main/src/baseWrapper.ts) checks only for `undefined`, not for 'false'.

**Related information:**
- `@vue/test-utils` version: 2.x.x 
- `Vue` version: 3.x.x
- `node` version:
- `npm` (or `yarn`) version:

**Additional context**

I've tried to add this test to attributes.spec.ts:
```javascript
  it('correctly handles dynamic disabled components', async () => {
    const Component = {
      template: `<component :is="'button'" :disabled="false" @click="click" data-testid="button" />`,
      methods: {
        click: vi.fn(),
      },
    }

    const wrapper = mount(Component)
    const button = wrapper.find('[data-testid="button"]')
    // expect(button.attributes('disabled')).toEqual('false');
    await button.trigger('click');
    expect(Component.methods.click).toHaveBeenCalled();
  })
```

Now guess what; is works as it should... The disabled attributes gets removed correctly instead of set to 'false'. So now I'm not sure where to search for a solution. 
Can anyone point me in the direction of a possible culprit?

**P.S.**
I found a quick workaround:
```vue
<component :type="type" :disabled="someBool ? 'disabled' : null" />
```
This way the attribute does get removed correctly.

**Comment by cexbrayat** [comment]
@Ken-vdE Yeah, it's hard to say without a failing test case... I think it should work as expected, but maybe you have some weird configuration or an out-of-date dependency somewhere. 

I'll close this, as I don't think we can help until you have a reproducible test that pinpoints the issue in VTU. Feel free to ping us on this issue if you manage to reproduce it, and we'll reopen!
