### ISSUE TITLE
`findAllComponents({ref})` returns a WrapperArray of length zero

### ISSUE THREAD

**Issue by esanzgar** [vuejs/test-utils#1761]
# Subject of the issue

Calling `findAllComponents()` with a ref returns an empty WrapperArray.

# Steps to reproduce

```vue
<template>
  <div>
    <div ref="hello">1</div>
    <div ref="hello">2</div>
  </div>
</template>
```

```javascript
import { mount } from '@vue/test-utils';
import Component from '@/components/HelloWorld.vue'

describe('div-exists', () => {
    const wrapper = mount(Component)

    it('ref check', () => {
        expect(wrapper.findAllComponents({ref: 'hello'})).toHaveLength(2)
    })
})
```

* write a template like the one above
* call wrapper.findAllComponents({ref: 'hello'})

# Expected behaviour

findAllComponents() should return a WrapperArray with two items.

# Actual behaviour

findAllComponents() should return a WrapperArray with no items.

# Versions
"vue": "2.6.14"
"@vue/test-utils": "1.3.0",

**Comment by cexbrayat** [comment]
Hi @esanzgar 

This is the repo for @vue/test-utils v2 targeting Vue 3.

Can you please open an issue on the repo of VTU v1 instead https://github.com/vuejs/vue-test-utils

Thanks

**Comment by esanzgar** [comment]
Sure, sorry about that.

**Comment by esanzgar** [comment]
Besides, the report was incorrect: I should have used `findAll` because I am finding DOM element not Vue components.
