### ISSUE TITLE
Feature request: Offer an alternative to setData for the composition API

### ISSUE THREAD

**Issue by lobo-tuerto** [vuejs/test-utils#1770]
**Is your feature request related to a problem? Please describe.**

I haven't found a way to set a component's internal variables to the values I need.  
This is in order to properly test it.

I found something close to it here: https://test-utils.vuejs.org/api/#setdata but it comes with a note that says:  
**Also, notice that setData does not modify composition API setup() data.**

But it does not link to an alternative for composition API. So I assume it does not exist. :thinking: 

**Describe the solution you'd like**

It would be great to have a way to change a component's internal variables to properly test them.

**Describe alternatives you've considered**
Unfortunately, I don't have any. :(

**Additional context**
Just starting with **test-utils** :pray:

**Comment by freakzlike** [comment]
I would only rely on internal variables if there is no better way. The component should be a closed scope and you should only test the user facing side (input events, etc.).

To modify the variables (which must be returned from setup) you can do:
```typescript
wrapper.vm.myVar = 1
await nextTick()
```

**Comment by lobo-tuerto** [comment]
Alright, thanks for the advice and for the answer!

**Comment by lobo-tuerto** [comment]
And I think you meant:

```ts
await wrapper.vm.$nextTick()
```

Right?

**Comment by freakzlike** [comment]
Yes, or you can import it from `vue`
