### ISSUE TITLE
Bug: Using a Mocked Router doesn't work

### ISSUE THREAD

**Issue by HassanAlgoz** [vuejs/test-utils#1772]
**Describe the bug**

I followed the docs of [Using a Mocked Router](https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-mocked-router) but it is not working. I get this error instead:
```
 FAIL  src/components/pager.spec.js > Pager > Component
TypeError: Cannot read properties of undefined (reading 'query')
```

**To Reproduce**

Code to reproduce:
```vue
// Pager.vue
<script setup>
import { useRoute } from "vue-router";
const route = useRoute();
</script>
<template>
    <div>{{ route.query }}</div>
</template>
```

```js
// pager.spec.js
import { describe, test, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import Component from './Pager.vue'

describe('Pager', () => {
  test('Component', () => {
    const mockRoute = {
      query: {
        page: 1,
      }
    }
    const mockRouter = {
      push: vi.fn()
    }
    mount(Component, {
      global: {
        mocks: {
          $route: mockRoute,
          $router: mockRouter
        }
      },
    })
  })
})
```

**Expected behavior**

Expected the test to run without errors.

**Related information:**
- `@vue/test-utils` version: 2.0.2
- `Vue` version: 3.2.37
- `node` version: v17.2.0
- `npm` (or `yarn`) version: 8.1.4

**Comment by cexbrayat** [comment]
@HassanAlgoz If you use the composition API, you need to follow this part of the docs 

https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-mocked-router-with-composition-api

You can also check https://github.com/posva/vue-router-mock which we mention in the docs. It's what I personally use, and it's great

I'm going to close the issue as this should solve your problem. Feel free to ping me with a repro (you can use https://stackblitz.com/edit/vitest-dev-vitest-2mah1p?file=package.json&initialPath=__vitest__ to build one online in a few minutes)
