### ISSUE TITLE
Bug: Mount async setup component error!

### ISSUE THREAD

**Issue by fellz** [vuejs/test-utils#1774]
**Describe the bug**

It gets empty wrapper. Examples: ```console.log(wrapper.html())``` gives nothing or  ```expect(wrapper.find("h3").exists()).toBe(true)``` -  gives error

**To Reproduce**

Complete describe function: 

```
describe("City Booking component test", () => {
  test("should render", () => {
    const TestComponent = defineComponent({
      components: { CityBookingTest },
      template: "<Suspense><CityBookingTest /></Suspense>",
    });
    const wrapper = mount(TestComponent);
    console.log("wrapper", wrapper.html());
    expect(wrapper.find("h3").exists()).toBe(true);
  });
});
```
and simple component: 

```
<template>
  <div>
    <h3>Booking</h3>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { bookingService } from "~/services";
export default defineComponent({
  async setup() {
    const city = 1;
    const resp = await bookingService.getLocations(`/locations/?city=${city}`, "en");
    console.log(resp.data);
  },
});
</script>

```
**Expected behavior**

```expect(wrapper.find("h3").exists()).toBe(true)``` -> should give true
**Related information:**
- `@vue/test-utils` version: 2.0.2
- `Vue` version: 3.2.38
- `node` version: 16.13.0
- `npm` (or `yarn`) version: 1.22.17

**Additional context**

Reference for async setup functions in tests: 
https://test-utils.vuejs.org/guide/advanced/async-suspense.html#testing-asynchronous-setup

**Comment by cexbrayat** [comment]
@fellz You probably need to add `await flushPromises()` after `mount` 

Check https://v1.test-utils.vuejs.org/guides/testing-async-components.html for more info

**Comment by fellz** [comment]
> @fellz You probably need to add `await flushPromises()` after `mount`
> 
> Check https://v1.test-utils.vuejs.org/guides/testing-async-components.html for more info

added  ```await flushPromises()``` result the same - no h3 tags

**Comment by freakzlike** [comment]
How does `bookingService.getLocations` gets resolved? Is it mocked somehow?

**Comment by cexbrayat** [comment]
I don't see where you mock the call to getLocations. How are replacing the HTTP call?

Can you make a repro on https://stackblitz.com/edit/vitest-dev-vitest-1vo1fe?file=package.json&initialPath=__vitest__ so we can take a look?

**Comment by fellz** [comment]
> I don't see where you mock the call to getLocations. How are replacing the HTTP call?
> 
> Can you make a repro on https://stackblitz.com/edit/vitest-dev-vitest-1vo1fe?file=package.json&initialPath=__vitest__ so we can take a look?

All API requests should be mocked ?

**Comment by freakzlike** [comment]
Yes. If it is not mocked then the normal logic (incl. sending a request to the host) will be performed. It's normal JS code

**Comment by cexbrayat** [comment]
@fellz Yes, and that should solve your problem. I'll close, as this is not an issue with VTU.
