### ISSUE TITLE
Bug: Spy a function in a function if these 2 functions have been declared in the same vue component

### ISSUE THREAD

**Issue by mattaiod** [vuejs/test-utils#1799]
**Describe the bug**
Spying a function in a function in a Vue component if these 2 functions are declared in the same vue file doesn't work.

**To Reproduce**
Minimum reproduction:
https://github.com/mattaiod/VITEST-cant-spy-fn-in-fn-in-component

**Expected behavior**
Since I have spied fnInside, when I call fnOutside, fnInside should be called

Related information:

@vue/test-utils: 2.1.0
vitest: 0.23.4
Vue: 3.2.40
node: v16.13.1
pnpm: 7.8.0

**Comment by cexbrayat** [comment]
@mattaiod I answered in #1798 and I don't think you changed something since then?

Is there anything else we can do to help?

Duplicates #1798

**Comment by cexbrayat** [comment]
@mattaiod Yes, it's exactly the same issue.

**Comment by freakzlike** [comment]
Spying and mocking is using the same technique by replacing the original function. But this only works for functions which are part of an object and accessible from outside. That's not `vue` specific and the same thing for common js modules as well.
