### ISSUE TITLE
Bug: ts(2769) in vscode when mounting component

### ISSUE THREAD

**Issue by stevemandl** [vuejs/test-utils#1822]
**Bug Description:**
I'm getting the following error in vscode in the HelloWorld.spec.ts:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'typeof import("/home/steve/temp/script_setup_test/node_modules/vue/dist/vue")' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<Readonly<ComponentPropsOptions<Data>>, unknown, {}, ComputedOptions, {}, Record<string, any>, ComponentOptionsMixin, ComponentOptionsMixin, string, Readonly<...> & { ...; }, { ...; } | {}>'.
      Type 'typeof import("/home/steve/temp/script_setup_test/node_modules/vue/dist/vue")' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: `on${Capitalize<string>}`]: (ComponentOptionsMixin[Uncapitalize<Capitalize<string>>] extends null ? (...args: any[]) => any : (...args: ComponentOptionsMixin[Uncapitalize<Capitalize<string>>] extends (...args: infer P) => ...'.
        Types of property 'computed' are incompatible.
          Type '{ <T>(getter: ComputedGetter<T>, debugOptions?: DebuggerOptions | undefined): ComputedRef<T>; <T>(options: WritableComputedOptions<T>, debugOptions?: DebuggerOptions | undefined): WritableComputedRef<...>; }' is not assignable to type 'ComputedOptions'.
            Index signature for type 'string' is missing in type '{ <T>(getter: ComputedGetter<T>, debugOptions?: DebuggerOptions | undefined): ComputedRef<T>; <T>(options: WritableComputedOptions<T>, debugOptions?: DebuggerOptions | undefined): WritableComputedRef<...>; }'.ts(2769)
mount.d.ts(33, 25): The last overload is declared here.
```

**Steps to Reproduce:**
```
$ npm create vue@3
Vue.js - The Progressive JavaScript Framework

✔ Project name: … script_setup_test
✔ Add TypeScript? … No / Yes
✔ Add JSX Support? … No / Yes
✔ Add Vue Router for Single Page Application development? … No / Yes
✔ Add Pinia for state management? … No / Yes
✔ Add Vitest for Unit Testing? … No / Yes
✔ Add Cypress for End-to-End testing? … No / Yes
✔ Add ESLint for code quality? … No / Yes

Scaffolding project in /home/steve/temp/script_setup_test...

Done. Now run:

  cd script_setup_test
  npm install
  npm run dev

$ cd script_setup_test/
$ npm i

added 199 packages, and audited 200 packages in 14s

43 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ code .
```
Then open __tests__/HelloWorld.spec.ts and look at line 8:
`    const wrapper = mount(HelloWorld, { props: { msg: 'Hello Vitest' } })`
Even though the above error is reported on the HelloWorld parameter, there is no error when running 
`npm run test:unit`

The contents of the resulting project can be found at https://github.com/stevemandl/script_setup_test

**Expected behavior**

Mounting components in vscode does not report an error when there is no error in the code.

**Related information:**
- `@vue/test-utils` version: 2.0.2
- `Vue` version: 3.2.38
- `node` version: v16.15.0
- `npm` version: 8.5.5

**Additional context**

This I am also getting this error in other projects using vue-jest and @vue/test-utils 2.1.0.

**Comment by cexbrayat** [comment]
Hi @stevemandl 

I see no error in VS Code, and no error when I run `npm run type-check`.

Can you try to run `npm run type-check` and let us know if you see the same error? `type-check` executes vue-tsc/Volar on your project and should display the same error you have in VS Code.

**Comment by stevemandl** [comment]
![image](https://user-images.githubusercontent.com/5465626/196801143-262893c1-88ab-480b-b6cc-f9eeb380a5b1.png)

Thanks @cexbrayat 
No type-check errors are displayed, but vscode still displays the error as seen in the attached screenshot.

**Comment by cexbrayat** [comment]
So this probably means Volar is not properly configured in your VS Code (as there are in fact no errors as you can see when running the type checking task)

Have you enabled "take over mode" as explained here https://github.com/johnsoncodehk/volar/discussions/471 ?

**Comment by cexbrayat** [comment]
@stevemandl Did that fix your issue?
