### ISSUE TITLE
Bug: [Vue warn] Non-function value encountered for default slot on stubbed teleport

### ISSUE THREAD

**Issue by freakzlike** [vuejs/test-utils#1829]
**Describe the bug**
After update from 2.1.0 to 2.2.0, tests with `stubs: { teleport: true }` produce a warning:
```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
  at <Teleport to="body" >
  at <Anonymous ref="VTU_COMPONENT" >
  at <VTUROOT>         
```

**To Reproduce**
Able to reproduce within VTU unit test
https://github.com/vuejs/test-utils/blob/6371349bd97e010169ed773b24a222ac3dc584e1/tests/mountingOptions/global.stubs.spec.ts#L514-L531

**Expected behavior**
Not print a warning

**Related information:**
- `@vue/test-utils` version: 2.2.0 
- `Vue` version: 3.2.41
- `node` version: 16.18.0
- `npm` (or `yarn`) version: pnpm@7.14.0

**Additional context**
I think this might come from the stubs refactoring and some previous special handling on the teleport child nodes, where they have been explicit passed as function:
https://github.com/vuejs/test-utils/blob/30e9c0c90ccfa5c7a90340ee29efce4935ed0d4d/src/stubs.ts#L208

**Comment by gabriellatavares** [comment]
i'm having the same issue

**Comment by FlorentGimaret** [comment]
I'm facing the same issue

**Comment by cexbrayat** [comment]
I have a hacky workaround that gets rid of the warning in #1833 but I'm not convinced this is the proper way.
