### ISSUE TITLE
Bug: Cannot spyOn methods when using the composition api (setup)

### ISSUE THREAD

**Issue by tongvantruong** [vuejs/test-utils#1830]
**Describe the bug**

I tried solutions from this https://github.com/vuejs/test-utils/issues/775 but they don't work on my side.

MyComponent.vue
```ts
<template>
  <div @click="methodA"> </div>
</template>

<script setup lang="ts">
const methodA = () => {
  console.log("methodA");
  methodB();
};

const methodB = () => {
  console.log("methodB");
};
</script>
```

MyComponent.spec.ts
```ts
import { mount } from "@vue/test-utils";
import MyComponent from "./MyComponent.vue";

it("a", () => {
  const wrapper = mount(MyComponent);
  const spy = jest.spyOn(wrapper.vm, "methodB");
  wrapper.vm.methodA();
  expect(spy).toHaveBeenCalled();
});
```

=> Error
```
 expect(jest.fn()).toHaveBeenCalled()

    Expected number of calls: >= 1
    Received number of calls:    0

       7 |   const spy = jest.spyOn(wrapper.vm, "methodB");
       8 |   wrapper.vm.methodA();
    >  9 |   expect(spy).toHaveBeenCalled();
         |               ^
      10 | });
```

**To Reproduce**

**Expected behavior**

The test should be passed

**Related information:**
- `@vue/test-utils` version: ^2.0.2 
- `Vue` version: ^3.2.37
- `node` version: 16.14.2
- `npm` (or `yarn`) version: yarn 1.22.17

**Additional context**

**Comment by freakzlike** [comment]
Spying and mocking is using the same technique by replacing the original function. But this only works for functions which are part of an object and accessible from outside. That's not vue specific and the same thing for common js modules as well. So unfortunately this is not possible
