### ISSUE TITLE
Feature request: combine with `unplugin-auto-import`

### ISSUE THREAD

**Issue by priority3** [vuejs/test-utils#1846]
if I use [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import) in `vue`, writed the fllowing code
```js
// foo.vue
<script>
// import {ref} from 'vue'
const msg = ref('')
</script>
```
write the `test` file
```js
import {mount} from '@vue/test-utils'
import Foo from './foo.vue'
const wrapper = mount(() => <Foo />)
```
excute this, there is a fail:
`ref` is not defined.
![image](https://user-images.githubusercontent.com/75966543/200162845-fa42db93-02ce-46a7-8761-4dac02387af8.png)

**Additional context**

or say, I want use `test-utils` with `auto-import`, is there any solution?

**Comment by priority3** [comment]
oh, I had solved it🤣

**Comment by freakzlike** [comment]
Can you post your solution please? Might be useful for others

**Comment by priority3** [comment]
> Can you post your solution please? Might be useful for others

ok, this can be solved by your test tools, it’s up to what is your test tool in your project. In my case, I use the vitest ,which provides the config file, so I just inject the plugin(unplugin-auto-import , or others ) into the config file , and it’s work fine.
