### ISSUE TITLE
Bug: setData with classes/Object prototypes does not work correctly

### ISSUE THREAD

**Issue by jacksongross** [vuejs/test-utils#1851]
**Describe the bug**
When testing a component that calls `setData` with a non-primitive class/object, the object gets set into the component VM without the prototype properties which breaks what should be a straightforward test. If you set the data property on the VM property directly with `wrapper.vm.foo = bar` it works as expected.

**To Reproduce**
Made a very basic example that illustrates the bug relating to the [mergeDeep](https://github.com/vuejs/test-utils/blob/2700e88351fe9853288f974b9d0469f6084380d7/src/utils.ts#L47) behaviour when calling setData
https://stackblitz.com/edit/vue3-script-setup-with-vite-prcxxz?file=src%2Fcomponents%2FHelloWorld.spec.ts,src%2Fcomponents%2FMyObject.js,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue

**Expected behavior**
I expect that calling `setData` will simply set the property on the component's VM without modification.

**Related information:**
- `@vue/test-utils` version: 2.0.0 
- `Vue` version: 3.2.37
- `node` version: 16.15.0
- `npm` (or `yarn`) version: 8.10.0

I can see a fix was applied [specifically for Date objects](https://github.com/vuejs/test-utils/issues/1717) but feel the real problem isn't solved.

**Comment by cexbrayat** [comment]
Hi @jacksonGross 

Thanks for the repo! This indeed looks like an issue.

`deepMerge` probably needs to handle this edge case. Our codebase mentions a SO post that was the source of the algorithm https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge/48218209#48218209

It looks like the answer was updated with a reference to https://jhildenbiddle.github.io/mergician/#/ I wonder if this lib handles this use-case? Maybe we could use it, or at least improve `mergeDeep` with their findings.

Would you like to try and open a PR to solve it? Any help would be gladly appreciated!

**Comment by jacksonGross** [comment]
Yeah I might take a stab at this when I have some extra time in the next week or so.

**Comment by lmiller1990** [comment]
Just to check you said 

> @vue/test-utils version: 2.0.0

We are on 2.2.2 now - there has been many releases since 2.0.0, might be worth updating? That said, I don't think we've changed `deepMerge` since then.

**Comment by jacksonGross** [comment]
> Just to check you said
> 
> > @vue/test-utils version: 2.0.0
> 
> We are on 2.2.2 now - there has been many releases since 2.0.0, might be worth updating? That said, I don't think we've changed `deepMerge` since then.

It makes no difference -- as you said, the `deepMerge` hasn't been updated. See https://stackblitz.com/edit/vue3-script-setup-with-vite-prcxxz?file=package.json

**Comment by lmiller1990** [comment]
Right, fair enough. We should update `deepMerge`.
