### ISSUE TITLE
Bug: Triggering keyboard event keydown.esc for components using withKeys does not update the DOM.

### ISSUE THREAD

**Issue by neoglez** [vuejs/test-utils#1852]
**Describe the bug**

Triggering keyboard event `keydown.esc` for components using `withKeys` does not update the DOM.

**To Reproduce**

Here is a [stackblitz](https://stackblitz.com/edit/node-92eszw?file=src%2Fcomponents%2FApp.js,src%2Fcomponents%2FHelloWorld.js), please **run it with Chrome** and [here the repo](https://github.com/neoglez/vue-test-utils-bug-withKeys). 

**Expected behavior**

Dom must be accordingly updated when keyboards events (others than click) are fired/triggered.  

**Related information:**
- `@vue/test-utils` version: 2.0.2 
- `Vue` version: 3.2.29
- `node` version: 18.9.1
- `npm` (or `yarn`) version: 8.19.1

**Comment by cexbrayat** [comment]
Hi @neoglez 

I don't think this is an issue with VTU: it looks like your repro has a few problems that make the test fails.

`HelloWord.js` should listen to the `esc` key:
```ts
onKeyup: withKeys((event) => { this.setInputInfo(event); }, ['esc']),
```
and `this.setInputInfo` should check the `esc` key as well:
```ts
if (event.key === 'esc') {
```

Then the test should trigger `keyup` and not `keydown`, and await the the action to let the template update:
```ts
await wrapper.get(spanWithKeys).trigger('keyup.esc');
```

With these fixes the test does succeed 👍

**Comment by neoglez** [comment]
@cexbrayat 

Thanks for answering so fast and taking the time to look at my test.
Indeed, by changing the code the way you said, the test pass. Unfortunately, those changes completely break the functionality `npm run serve:universal`, which makes the problem even worst since the test pass for a non-functioning component. Please note that Escape keyboard event (pressing escape key) [equals `Escape`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) and not `esc`. It seems that the problem is not the key (it doesn't work with other keys neither) but the event not being properly triggered. I do believe it is VTU bug. Would please reopen the issue? Maybe I find the problem myself and can post a PR.

**Comment by cexbrayat** [comment]
@neoglez Yes, both `escape` and `esc` should work 
See https://sfc.vuejs.org/#eNqFkT9PwzAQxb/K4SUg0VisURrBgMTIxuIlTS9tiv/J5xShyN+dc1xAQkLd7j2/+/l8XsST9/V5RtGIloYw+QiEcfadspPxLkRYIOAICcbgDFQcrZRVdnCWIhg6wDaf31YvqLWDNxf0/qa6U7aVBccgFhGN131EVgDt8aFblrU5pVayWt39dF4LLnW/Q929BiSCZxp6j60s3iUwWT9HeHzHz9nXuCa2SpRxqtJRKVG48hv83w3cfwX/y2bxF9zKn9eJe1G2tjG9r0/kLO91yWF1OSAlGlid7PE2s1biGKOnRkoah/wbJ6pdOEiu6jDbOBnkKcxmF9wHYWCwEhmRlE0ifQG685av

I don't mind reopening the issue, but I don't understand why that would be a VTU issue. Can you make a small repro explaining what you're thinking about?

**Comment by neoglez** [comment]
@cexbrayat Here is [the updated repo](https://stackblitz.com/edit/node-92eszw?file=tsconfig.json,README.md):

# vue-test-utils-bug-withKeys

This repo explores the possibility that Vue Test Utils (VTU) contains a bug that does not allow tests passing successfully, when using Vue Js [`h()` render function](https://vuejs.org/api/render-function.html) and [withKeys](https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-dom/src/directives/vOn.ts#L60).

The repo contains two parts: the first part is the functionality itself, i.e., by running `npm run serve:universal` an application launches where the user can enter keyboard characters in a form input. When the user presses other key than Escape (Keyboard event with `key = "Escape"`), the text `"You did not press the Esc key"` is displayed. If the user does press Escape, the text reads `"You just pressed the Esc key"`.

The second part is a VTU test that attempt to test exactly that functionality. `npm run test` runs the test.

Some recommendations has been done by VTU members to make the test pass, e.g., see [this comment](https://github.com/vuejs/test-utils/issues/1852#issuecomment-1309186816). The problem is that if those changes are applied, the test passes, however the component does not work any more.

The expected behavior is to have both functionality (part one: `npm run serve:universal`) and test passing (part two: `npm run test`) successfully executed.

Special attention has to be taken when changing line 40 in HelloWorld.js since replacing `escape` by `Escape` breaks the functionality. The same situation in line 31 in HelloWorld.js: replacing `Escape` by `escape` breaks the component (an issue with Vue Js?).

**Comment by cexbrayat** [comment]
@neoglez doesn't that work if you use `await wrapper.get(spanWithKeys).trigger('keyup.Escape');`?

**Comment by neoglez** [comment]
@cexbrayat Wow :satisfied:
That actually did it :+1:
Thanks again for taking the time :smiley:
I suppose there is a way to do it with `await wrapper.get(spanWithKeys).trigger('keyup', {key: 'SomeEscape'});` but that's another history. :wink:
