### ISSUE TITLE
Bug: spying on wrapper.vm for script setup methods using Vue 3.2.45 and VTU 2.2.2 stop working

### ISSUE THREAD

**Issue by felixzapata** [vuejs/test-utils#1859]
**Describe the bug**

All the tests we have using explicit casting for _wrapper.vm_ in order to spy methods stop working after updating to Vue 3.2.45 and VTU 2.2.2.

Related bugs:

- [https://github.com/vuejs/test-utils/issues/1791](https://github.com/vuejs/test-utils/issues/1791)
- [https://github.com/vuejs/test-utils/issues/972](https://github.com/vuejs/test-utils/issues/972)

**To Reproduce**

This is the minimal sample based on one of the failing tests. With the previous version, this test passes.

https://stackblitz.com/edit/vitest-dev-vitest-pcp793?file=components%2FHello.vue

**Expected behavior**

The test must be passed.

**Related information:**
```
System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 57.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5417.0
    Firefox: 106.0.5
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @intlify/core-base: 9.2.2 => 9.2.2 
    @intlify/unplugin-vue-i18n: 0.7.3 => 0.7.3 
    @vitejs/plugin-vue: 3.2.0 => 3.2.0 
    @vue/eslint-config-typescript: 11.0.2 => 11.0.2 
    @vue/test-utils: 2.2.2 => 2.2.2 
    @vue/tsconfig: 0.1.3 => 0.1.3 
    vite: 3.2.3 => 3.2.3 
    vitest: 0.25.1 => 0.25.1 
    vue: 3.2.45 => 3.2.45 
    vue-i18n: 9.2.2 => 9.2.2 
    vue-loader: 17.0.1 => 17.0.1 
    vue-router: 4.1.6 => 4.1.6 
    vue-tsc: 1.0.9 => 1.0.9
```

**Additional context**
NA

**Comment by cexbrayat** [comment]
👍 Thanks for the repro

This should be fixed by #1860 

Vue changed its internal, and we now have to do a bit more work in VTU to allow the same feature than previously. You can stay on Vue v3.2.44 until this is released

**Comment by felixzapata** [comment]
> 👍 Thanks for the repro
> 
> This should be fixed by #1860
> 
> Vue changed its internal, and we now have to do a bit more work in VTU to allow the same feature than previously. You can stay on Vue v3.2.44 until this is released

ok, just to confirm, Vue 3.2.44 and VTU 2.2.1, correct?

**Comment by cexbrayat** [comment]
Exactly

**Comment by felixzapata** [comment]
it works now, thanks.
