### ISSUE TITLE
Bug: Type-check doesn't work properly for variables declared in script setup components

### ISSUE THREAD

**Issue by gbyesiltas** [vuejs/test-utils#1866]
**Describe the bug**
Trying to access a variable declared in a component written with `script setup` results in a type error

```
Property 'someVariable' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{ errors: string[]; }> & Omit<Readonly<ExtractPropTypes<{ action: { type: PropType<"Update" | "Create">; required: true; }; ... 5 more ...; isLoading: { ...; }; }>> & ... 5 more ... & ComponentCustomProps, "errors">; ... 10 more ...; $watch<T extends string ...'.
``` 

**To Reproduce**
1. Create a component with `script setup` and declare a variable inside it
2. Write a test where you are trying to access that variable with `wrapper.vm.someVariable`
3. The type-check will give an error similar to the one above

**Expected behavior**
The variable accesses to work without typing errors

**Related information:**
- `@vue/test-utils` version: 2.2.3
- `Vue` version: 3.2.45
- `node` version: 16.17.0
- `npm` (or `yarn`) version: 9.1.1

**Additional context**
The tests do pass, but typescript isn't happy

**Comment by cexbrayat** [comment]
Hi @gbyesiltas 

Yes, you'll need to add an explicit cast, like `expect((wrapper.vm as unknown as { count: number }).count).toBe(1)`.

We sadly can't do anything about it in VTU, we're waiting for improvements in Vue itself.

This is tracked in https://github.com/vuejs/test-utils/issues/972

Closing this one as duplicate

**Comment by cexbrayat** [comment]
Yeah I hope too 😉

This is the case for a while, but if you were still on VTU v2.0.0, maybe we had a `any` type for `vm`, whereas we now try to infer the maximum information we can (but I don't exactly remember in which version we started to improve this).

**Comment by gbyesiltas** [comment]
Thanks! :)
