### ISSUE TITLE
Bug: v-for elements is null

### ISSUE THREAD

**Issue by liujiayi666** [vuejs/test-utils#1875]
**Describe the bug**

 can't get v-for elements and got warn!!
`[Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol)
  at <XXXPage ref="VTU_COMPONENT" >
  at <VTUROOT>
[Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol)
  at <XXX ref="VTU_COMPONENT" >
  at <VTUROOT>`

**To Reproduce**

**Expected behavior**

**Related information:**
- `@vue/test-utils` version: 2.x.x 
- `Vue` version: 3.2.37
-  `vitest` version: 0.24.5
-  `@vue/test-utils` version: 2.2.1
- `node` version: v16.15.1
- `npm` (or `yarn`) version:8.11.0

**Additional context**

**Comment by cexbrayat** [comment]
Hi @liujiayi666 

Can you provide us a small repro online using https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=package.json&initialPath=__vitest__ ?

**Comment by cexbrayat** [comment]
If you use `mainFields: ['module']` I think that you get 2 instances of Vue, hence the error about Symbol (as Symbol needs to be unique). 

See https://github.com/vuejs/core/issues/2600

I don't think we can do much about this. What are you trying to achieve with `mainFields: ['module']` in your tests

**Comment by liujiayi666** [comment]
@cexbrayat  I need to use a Private repository， but got error `SyntaxError: Cannot use import statement outside a module`. Thank you for your answer
