### ISSUE TITLE
Bug: Submit a form using a submit button does not trigger handler function

### ISSUE THREAD

**Issue by MrShnaider** [vuejs/test-utils#1883]
**Describe the bug**
I was trying to reproduce a simple scenario. The component contains an input and a button, wrapped by form. The text is entered in the input field, and when you click on the button, the form is submited and the text is deleted. However, after clicking on the button form does not submit and test fails.

**To Reproduce**
``` vue
// component.vue
<template>
    <form @submit.prevent="submitForm">
        <input type="text" v-model="inputValue" />
        <button type="submit">Submit</button>
    </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const inputValue = ref('');
const submitForm = () => {
    inputValue.value = '';
}
</script>
```

``` ts
// component.test.ts
import { DOMWrapper, mount } from '@vue/test-utils';
import { describe, it, expect } from 'vitest';
import component from './component.vue';

describe('component test', async () => {
    it('clear input after submit', async () => {
        const wrapper = mount(component);
        const input = wrapper.get('input') as DOMWrapper<HTMLInputElement>;
        const button = wrapper.get('button');

        expect(input.element.value).toBe('');
        await input.setValue('Test input');
        expect(input.element.value).toBe('Test input');
        await button.trigger('click');
        expect(input.element.value).toBe(''); // fails and say, that value='Test input'
    })
})
```
**Expected behavior**
If I click on button I expect that form would be submitted and handler function would be called, but handler function was not called

**Possible Solution**
I tried to bind components to the DOM using AttachTo and read the "Form Handling" documentation. None of this helped. If there are exceptions to this behavior, you need to add them to the "Form Handling" documentation

**Related information:**
- `@vue/test-utils` version: 2.1.0
- `Vue` version: 3.2.41
- `node` version: 16.13.1
- `npm` version: 8.1.2

**Comment by cexbrayat** [comment]
Hi @MrShnaider 

As explained here https://test-utils.vuejs.org/guide/essentials/forms.html#triggering-complex-event-listeners, you need to use `attachTo`.

Mount your component with `const wrapper = mount(component, { attachTo: document.body });` and the test will succeed.

See https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=test/basic.test.ts
