### ISSUE TITLE
Feature request: tests without `expect` should display warning

### ISSUE THREAD

**Issue by MrShnaider** [vuejs/test-utils#1884]
**Is your feature request related to a problem? Please describe.**
If there is no `expect` in the test, then the test is still considered successful and still passes with green color. In all xUnit test frameworks such tests are yellow and display warnings when passing. It is very confusing when an unfinished test is green.

**Describe the solution you'd like**
I would prefer that all tests without `expect` pass, but display a warning. This should be the default behavior. If `expect` is not required in the test, for example, the test checks that there was simply no error during the script, then you need to specifically prescribe prefixes for this test, like `ignore` `skip` or `todo`, for example `it.doesNotFails('my testcase', () => { })`

**Comment by freakzlike** [comment]
`expect` is not part of `@vue/test-utils`. This belongs to your test runner (for example `jest` or `vitest`) or can be checked with a linter plugin like [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/expect-expect.md)
