### ISSUE TITLE
Should await "input" event then "change" in setValue api

### ISSUE THREAD

**Issue by houfeng0923** [vuejs/test-utils#1886]
**Describe the bug**
About `setValue` api, for trigger input value change,  if the node type is `input` or `textarea`,  the actual flow is trigger input event firstly, then  trigger change when  element  blur.
Now `input` and `change` event is sync . it's not match with reality in browser side.

It cause a problem for watch modelValue and modelValue is changed in inputHandler and changeHandler.

**Expected behavior**

I think it need  await in [setValue](https://github.com/vuejs/test-utils/blob/v2.2.4/src/domWrapper.ts#L122)

**Related information:**
- `@vue/test-utils` version: 2.2.4
- `Vue` version: 3.x.x 

**Additional context**

**Comment by cexbrayat** [comment]
Hi @houfeng0923 

This is a bit more complicated than that in the spec: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

As you can see here the input and change events are not synced for input and texteare [Demo](https://sfc.vuejs.org/#eNqdks1OwzAMx18lymUgbY24Ttk0XoFzLl3nbh1rEjluQar67jhJC9UQIHGKv/L7O7EH+ex90Xcgt1KHChtPIgB1fm9s03qHJAaBUItR1OhaseLSlbHGVs4GEo31HYldrHioy1uAxzlTXUp7hruUVlmC4ewQtP5WErAnhL48pVNk5lYMw0QfxxzXx47IWXGobk31ujNyFk90I/cvwJ1rlcsyVE3UL3ruK+GnFn/kfz7hT4Fknpp+n1rSKpoplls8pGPRMWHHPFZKCkupnMmXI4XgnUqEcsGcQ//AajVfZlR0pgHItczD3rSlL67BWV6HIaoxPCWCkfxn+aOM5CWIvpEXIh+2SoW6ikt0DYXDs2KrwM5S00IBod0c0b0FQAYbuV4wFAd7wA2CPQEC/sa8K/3GjVge5CjHD8do938=)

The change event is only fired when the user loses the focus

If you have a specific use-case that does not work, can you provide us a small repro online using https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=package.json&initialPath=__vitest__ ? We'll take a look

**Comment by houfeng0923** [comment]
https://stackblitz.com/edit/vitest-dev-vitest-medouj?file=components%2FHello.vue,test%2Fbasic.test.ts&initialPath=__vitest

It's a single demo just for usecase. please check it .

**Comment by cexbrayat** [comment]
@houfeng0923 I'm not sure I understand. How is that supposed to work? `Number.isNaN('Test')` will return `false` no? Won't that only work if the value is `NaN`?

**Comment by cexbrayat** [comment]
And as you can see if you add a `console.log` in `adjust`, the change event is only called when the input loses the focus. So I would say this works as expected, no?

**Comment by houfeng0923** [comment]
@cexbrayat , demo case is updated. please help to confirm .

**Comment by cexbrayat** [comment]
I think this is working as expected.

I've your repro on the SFC playground [here](https://sfc.vuejs.org/#eNqdVE1vm0AQ/SsjVAks2dBeXSdpVfXQQ6OqlXoplUJgcbBgQbuL0wjx3zszC2TBrpX0YrM7b958vdnO+9g04bEV3tbb6VQVjQEtTNtcx7KomloZ6ECJHHrIVV2Bj1D//WS7bat7ob7IpjWDPYycOyImdFpLbUC2FVwRWfDu7Qpvd5ENiKHwYETVlIkReAKCbqHr2KXv6WbnhjpuqjoT5VXsISD2IEKnXeQweGvPZripkiY86FpifR3xxINBxx5GoBu6wzzpHHsPxjR6G0U6Tyn5gw5rtY/wK1StNEUlQqGrzb2qH7VQSBx7a4cjwsujUBslZCaUUJc4F9ATXqLFynssZdFRGtWsW7tlV7JCo/XpZ1JSXfAhfUjkXqAhyQ6tNuc6hkd3/FCiBzpQnxZSWMNjYtKHfyhiroUzKmhU3WjUQSbyQopvdAp4Dpw8p7wddIWt7Ukoo6uoCjN5fsaDDn75bZNhBdtnb38Nvi3Y/+16o1SQkyGDDDmV8NmT0BbrNnAA+74ly1uZmqKWYAPbTAPzx6ysnEoxKt0xoSdAkYODY5GPCYXHIZL1CQt9m9wGCFjBDeLKErYEZ5oeRKnFJRJysFD6UThPJU+BiEB7LHmaASGDFVxd2wE5XWGBW1Pg9mUKt3SAmxvAbrFfB0VViaygEYFRaMSY7lSsIpHFtgaDcGHui3HSaK7tbCp3bzry4QT6O8aRaIKzKqH2OpBBM9N9P3+icA8vbGDBsked4M7w93eR0+bxN94hd1YKJpgtpL3/xMdza3npTR4WcQ21/Frj6ySy5U6+YuN+GFXI/Ys2bmqUz9XRx2l7Z6s3dmRYpcUiOb0JxFHIcUOs7zhatoQmUXuBMxgEfGm8jHEHPGY7GVj+izTsKP43j6k18xiJfpIpLF4OLpiTDRA9xKI3YuyWZZ+ei/n1JHn8H3f9tes8EJ+kc+5d5AB2cJPcAofmRSSsLXen+r+0LfeL)

As you can see, the input is cleared when it loses focus, on the change event.
So if you want to test that in your test, you'll need to emit the change event or give the focus to another element.

**Comment by houfeng0923** [comment]
Ok, in fact in my unit test, i used ` await trigger('input'); await trigger('change')` instead.
But i also think  https://github.com/vuejs/test-utils/blob/v2.2.4/src/domWrapper.ts#L122 need resolve promise.
