### ISSUE TITLE
Bug: Errors in setup/mount throw and do not return a wrapper

### ISSUE THREAD

**Issue by twoBoots** [vuejs/test-utils#1899]
**Describe the bug**

#1845 merged and released in [v2.2.2](https://github.com/vuejs/test-utils/releases/tag/v2.2.2) as a workaround for a [reactivity issue](https://github.com/vuejs/core/issues/7020) with errors during mount in Vue. This causes errors during component mount to throw and not return a wrapper by [intercepting the expected error handler](https://github.com/vuejs/test-utils/pull/1845/files#diff-10dced802c6852b5a362ffd5970356d2be22d555549040e3533bea567bdc878cR577-R593).

This prevents the ability to test error handling strategies for larger Vue projects that manage when errors occur in subcomponents and use fallback components.

**To Reproduce**

```
it('displays error messages from setup errors', async () => {
  const theError = new Error('very bad things happened out of our control');

  const ErrorSubComponent = defineComponent({
    setup() {
      throw theError;
    },
    template: '<div>I load external data from flaky provider</div>',
  });
  const ParentWithErrorSubComponent = defineComponent({
    components: { ErrorSubComponent },
    template: `
      <div>
        <h1>parent content</h1>
          <ErrorHandlerSafeguard>
            <ErrorSubComponent />
            <div>inner content</div>
          </ErrorHandlerSafeguard>
        <footer>parent footer</footer>
      </div>
    `,
  });

  wrapper = mount(ParentWithErrorSubComponent, {...configWithErrorSafeguardPlugin}); // <--- throws

  expect(wrapper.text()).toContain('parent content');
  expect(wrapper.text()).toContain('parent footer');
  expect(wrapper.text()).toContain('SAFEGUARD DEFAULT OOPS MESSAGE WITH DINOSAUR GAME');
  expect(wrapper.text()).toContain('error details: very bad things happened out of our control');

  expect(wrapper.text()).not.toContain('inner content');
  expect(wrapper.text()).not.toContain('I load external data');
});
```

**Expected behaviour**

A wrapper is returned with the mounted component, or a configuration option added to `mount` to determine whether to intercept error handlers and throw errors, or return the wrapper.

**Related information:**
- `@vue/test-utils` version: 2.2.2

**Additional context**

I'm happy to put a PR together to add this configuration option.

**Comment by cexbrayat** [comment]
Hi @twoBoots 
Thanks for the repro. We are aware of this issue (this is similar to #1870)

@xanf mentioned he was taking a look in https://github.com/vuejs/test-utils/issues/1870#issuecomment-1321885137 so we'll hopefully have a fix soon

**Comment by cexbrayat** [comment]
@twoBoots I wanted to check if that's still an issue, but I can't run your reproduction
Can you check if that's still the case with the latest VTU version?
If it doesn't work, can you provide us a small repro online using https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest__ ?

**Comment by cexbrayat** [comment]
Let's close this as we've not heard back from the OP
