### ISSUE TITLE
Feature request:  add new methods to Vuewrapper,  which can  get provide value

### ISSUE THREAD

**Issue by flynn-eye** [vuejs/test-utils#1932]
**Is your feature request related to a problem? Please describe.**

i write an vue plugin (use provide/inject feature) to provide the value for global components, to test it i need to get  value in children components, now my way to get the value is not graceful
```
wrapper.__app._context.provides
```
**Describe the solution you'd like**

a new methods that
```
const value = wrapper.inject('key')
```

**Comment by cexbrayat** [comment]
Hi @flynn-eye 
Thanks for opening a feature request.

To better understand what you're trying to do, could you put a small repro online using Stackblitz:  https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest__ please?

**Comment by flynn-eye** [comment]
> https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest

thanks, this is demo
[https://stackblitz.com/edit/vitest-dev-vitest-dlgn5x?file=test%2Fbasic.test.ts,package.json&initialPath=__vitest](https://stackblitz.com/edit/vitest-dev-vitest-dlgn5x?file=test%2Fbasic.test.ts,package.json&initialPath=__vitest)

**Comment by cexbrayat** [comment]
Ok, in that case, what about injecting the value in the component you mount, and testing it on `wrapper.vm`?

```
const CMP = {
  template: '<p>hello</p>',
  setup() {
    const value = inject('myKey') as { status: string; value: any };
    return { value };
  },
};
// ...

expect(wrapper.vm.value.status).toBe('pending');
```

See https://stackblitz.com/edit/vitest-dev-vitest-jfg8u3?file=test/basic.test.ts

With this, I think we don't need to introduce another method in the API.
