### ISSUE TITLE
Question: how to run async code that rely on 'app' before mounting component?

### ISSUE THREAD

**Issue by semiaddict** [vuejs/test-utils#1938]
**Is your feature request related to a problem? Please describe.**

I am working on a large modular vue application, which registers modules before rendering the main component.
Most components rely on some of those modules to function correctly.

I am able to test simple components by registering modules in the `install` method of a plugin defines in the test's [`global.plugins`](https://test-utils.vuejs.org/api/#global-plugins) option.
However, I am having trouble testing components that have a required prop, which in turn depends on a module to be registered.

**Describe the solution you'd like**
I would like to be able to define the [`props`](https://test-utils.vuejs.org/api/#props) option as an async function to be able to generate the props after all the plugins and directives have been setup.

Something like :
```js
const wrapper = mount(Component, {
  props: async () => {
    const model = await createModel();
    return { model };
  }
});
```

Another solution could consist in allowing the initialization of all plugins, directives, etc before calling the mount method, but this would likely require a lot more work as I believe it would require a lot of changes in the API.

**Describe alternatives you've considered**
I have tried setting the prop via the [`setProps`](https://test-utils.vuejs.org/api/#setprops) mothed, but that doesn't work in my case as the prop is required. It thus has to be created before initializing the component.

**Additional context**
Here's an example test I'm working on:

```js
import { mount } from "@vue/test-utils";
import { createTestingPinia } from "@pinia/testing";
import VueDOMPurifyHTML from "vue-dompurify-html";
import { registerModules } from "@metascore-library/core/services/module-manager";
import MediaPlayer from "@metascore-library/core/modules/media_player";
import MediaCuepoints from "@metascore-library/core/modules/media_cuepoints";
import Content from "../models/Content";
import ComponentWrapper from "../components/ComponentWrapper.vue";
import Component from "../components/ContentComponent.vue";

jest.mock("@metascore-library/core/modules/media_player");

describe("ContentComponent.vue", () => {
  it("renders text", async () => {
    const text = "my content";

    const content = await Content.create({
      type: "Content",
      id: "Content-test",
      text,
    });

    const wrapper = mount(Component, {
      global: {
        components: {
          ComponentWrapper,
        },
        plugins: [
          createTestingPinia(),
          VueDOMPurifyHTML,
          {
            install: async (app) => {
              await registerModules([MediaPlayer, MediaCuepoints], { app });
            },
          },
        ],
      },
      props: {
        component: content,
      },
    });

    expect(wrapper.text()).toBe(text);
  });
});
```

The test fails, as the `Content` model, which is used as a prop for the tested component, requires the `MediaCuepoints` module.
The module is registered in a custom plugin, but the `Content` model is created before.

**Comment by cexbrayat** [comment]
Hi @semiaddict 

Can you provide us a small repro online using https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest__ ? This would help us understand your issue more precisely and maybe come up with a solution that doesn't need to add a new feature to VTU.

**Comment by semiaddict** [comment]
@cexbrayat,

Thank you for your reply.
I seem to have misunderstood the reason for my failing test.
The problem seems to be that the mounted component's setup method is called before the plugins defined in the `global.plugins` option are installed.

I will create a small repro and post it here in a few moments.

**Comment by semiaddict** [comment]
Here's a simple repro: https://stackblitz.com/edit/vitest-dev-vitest-h5tsxj?file=components%2FHello.vue,test%2Fplugins.test.ts&initialPath=__vitest

We can see that the tests finishes running before `console.log('install');` in the plugin's async method is called.
I'm not sure this is a bug, as I don't seem to find any Vue documentation for a plugin's async install.

So my question now is, how can I run an async function that relies on the `app` variable in test-utils before mounting the tested component ?

In my application, this is done by:
1. creating the app using vue's `createApp`
2. setting up global app configs (such as globalProperties)
3. waiting for the registration of required modules
4. mouting the app

So the modules are registered before sub-component's setup is called.
I am using a plugin in the tests to simulate this app initialization setup, but since the component's setup runs before the plugin's async method has finished running, the test fails.

**Comment by cexbrayat** [comment]
AFAIK Vue does not do anything for async plugin (see https://github.com/vuejs/core/blob/0c07f12541061cf10996f998705d7ad36193aa4f/packages/runtime-core/src/apiCreateApp.ts#L218-L234)

I'm not familiar with the metascore library you're using: what does `registerModules` do with the `app`? Maybe try to build a repro on stackblitz so we can try a few options?

**Comment by semiaddict** [comment]
The metaScore library is the project I'm working on.

`registerModules` registers a list of modules. It send the `app`  variable to each module, to allow it to register global components and directives, or install plugins.

Basically, each module is a sort of a mini Vue app, which adds new functionality to the global vue app.
Some of those modules need to make API calls to retrieve data/configs from a CMS before initializing, so they are installed via an async method.

What do you need me to reproduce? Do you need the entire module registration process?

**Comment by cexbrayat** [comment]
I'm trying to understand what is blocking your test, but this is hard without seeing what does what. 

A few options:
- Can't you mock some parts in your tests?
- Or maybe give a fake props on mount and then use `setProps` to give the real one?
- Or maybe you can have a fake `registerModules` for tests that just does what is necessary to be able to use `Content.create`?

**Comment by semiaddict** [comment]
Thank you @cexbrayat.
Since I only had one async module, I ended up slightly rewriting the module manager to make module registration synchronous; moving async code somewhere else in the module.
