### ISSUE TITLE
Bug: When importing a comp within script setup without extension test fails with stub

### ISSUE THREAD

**Issue by marina-mosti** [vuejs/test-utils#1941]
**Describe the bug**

When in script setup, when importing a component and not adding the .vue extension VTU stubs out the component as `<anonymous-stub />`, which breaks any type of stubbing.

ie component:

```html
<template>
  <MyComponent 
    ref="component"
    v-model="someVmodel"
  />
</template>

<script setup>
import { ref, onMounted } from 'vue'
import MyComponent from '@/components/MyComponent'; // HERE

const component = ref(null)
const someVmodel = ref(null)

onMounted(() => {
  console.log(component.value)
  const myProp = component.value.myProp[0] // This breaks since MyComponent will not be stubbed
  console.log(myProp)
})
</script>
```

test

```js
it('fails', () => {
    const wrapper = shallowMount(HelloWorld, {
      global: {
        renderStubDefaultSlot: true,
        stubs: {
          MyComponent: { // This will not bet stubbed
            template: '<span />',
            data: () => ({
              myProp: [1, 2, 3]
            })
          }
        }
      }
    })

    console.log(wrapper.element.outerHTML)
  })
```

There are two possible fixes: 
To add a `name: ` property to the subcomponent that is getting stubbed, as the docs suggest.
To add the .vue extension back.

I'm not sure if this qualifies as a bug but it took a few hours to figure out the problem so fwiw :)

**To Reproduce**

**Expected behavior**

VTU should be able to infer the component name without the extension

**Related information:**

**Additional context**

**Comment by lmiller1990** [comment]
I wonder why removing the `vue` extension causes this to not work. Weird. I'm guessing this is related to the tooling - Test Utils doesn't know about `vue` files, by the time the component code is mounted it has already been compiled to plain JS. Is this using Vitest? Does the same problem manifest when using another tool chain (like Jest?)

I suspect this will need to be addressed somewhere else.

I generally just add the extension in my own projects, it sure makes life easier for basically every tool.

**Comment by marina-mosti** [comment]
We're using jest, you are probably right this is pointing to some odd parsing of the file. The weirdest part is that it happens in the stubs, feel free to close but just in case someone else runs into this

**Comment by cexbrayat** [comment]
Yeah I think VTU does not have any logic to handle vue files, we rely on the name we find
See https://github.com/vuejs/test-utils/blob/864e9e2b3a1e65d19b9e748c0af5d4b26698d99c/src/utils/componentName.ts

I agree that this is probably a tooling issue somewhere else 👍

**Comment by lucassonsinlima** [comment]
Hey! I went through the same issue and adding the extension to the import or naming it really fixes the problem. Probably the problem does not happen in vitest because it asks for extensions by default. Thank you @marina-mosti, saved me a lot of time!
