### ISSUE TITLE
Bug: The v2 document link doesn't work

### ISSUE THREAD

**Issue by MahsaGoudarzi** [vuejs/test-utils#1945]
https://next.vue-test-utils.vuejs.org/guide/
Hey, This link that is in the official website assume to work for documentation v2 vue test utils but it doesn't...
could u plz check it

**Comment by cexbrayat** [comment]
Hi @MahsaGoudarzi 

Thank you for pointing this out.

Can you give us the URL where you found this link? Is this in the VTU docs or the Vue docs or somewhere else?

**Comment by lmiller1990** [comment]
Closed in #1946!

**Comment by cexbrayat** [comment]
@lmiller1990 I'm not sure this was the URL @MahsaGoudarzi was talking about, but we can always reopen if we have an answer
