### ISSUE TITLE
Bug: test slotted element inside component

### ISSUE THREAD

**Issue by kabinthakuri** [vuejs/test-utils#1954]
`<tabs>
    <nav>
      <ul>
        <li>Test</li>
      </ul>
    </nav>
  </tabs>
`
tabs component is from vue3-tab external package. How do i test this slotted component used inside external component

**Comment by cexbrayat** [comment]
Hi @kabinthakuri 

You should be able to test this as you test your usual component. Something like `expect(wrapper.get('li').text()).toBe('Test')`.

If that does not help, can you provide us a small repro online using https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest__ ? We'll then be able to help you

**Comment by kabinthakuri** [comment]
hi @cexbrayat 
i getting problem in mount

**Comment by kabinthakuri** [comment]
Hi @cexbrayat 
i getting error in mount

`import History from "@/common/core/components/leads/History.vue";

const wrapper = shallowMount(My component, {
    global: {
      plugins: [Tabs]
    },
  });`

**Comment by cexbrayat** [comment]
@kabinthakuri Try to make a repro using the link I posted above, it'll take you 5 minutes. Without more context, we won't be able to help you

**Comment by lmiller1990** [comment]
Try `mount`, otherwise it will stub out the entire `Tab` component.

**Comment by cexbrayat** [comment]
@kabinthakuri Did you manage to solve your problem or put together a repro?

**Comment by cexbrayat** [comment]
No answer from the OP, let's close this
