### ISSUE TITLE
Bug: mounting a component that uses a pinia store makes 'props' undefined

### ISSUE THREAD

**Issue by Zazcallabah** [vuejs/test-utils#1965]
**Describe the bug**
Consider a component that uses the result from `defineProps` and a pinia-store, like this modified example from `npm init vue@latest`:

```
import { useCounterStore } from '@/stores/counter';

const props = defineProps<{
  msg: string
}>()

const counter = useCounterStore() // this line causes the issue
</script>

<template>
    <h1 v-if="props.msg !== 'abcd'">{{ msg }}</h1>
</template>
```

When running the test, the test fails in the template because props is undefined. If you remove the pinia store, the test passes.

**To Reproduce**

https://github.com/Zazcallabah/vitest-mount-demo/blob/master/src/components/HelloWorld.vue

**Expected behavior**
Test should pass and the props object inside the component should contain the mounted prop values.

**Related information:**

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 18.05 GB / 31.73 GB
  npmPackages:
    @vue/test-utils: ^2.2.6 => 2.2.10
    vitest: ^0.25.6 => 0.25.8
    vue: ^3.2.45 => 3.2.47
```

**Comment by cexbrayat** [comment]
Hi @Zazcallabah 

Thanks for opening an issue. From what I see from your repro:
- you don't have to use `props.msg` in the template, you can directly use `msg`
- you currently don't set the pinia context in your test

See the docs from Pinia on how to correctly test a component that uses Pinia

https://pinia.vuejs.org/cookbook/testing.html#unit-testing-components

Something like this should work:

```ts
import { describe, it, expect, vi } from 'vitest'
import { createTestingPinia } from '@pinia/testing'
import { mount } from '@vue/test-utils'
import HelloWorld from '../HelloWorld.vue'

describe('HelloWorld', () => {
  it('renders properly', () => {
    const wrapper = mount(HelloWorld, { 
      props: { msg: 'Hello Vitest' }, 
      global: {
        plugins: [createTestingPinia({ createSpy: vi.fn })],
      }
    })
    expect(wrapper.text()).toContain('Hello Vitest')
  })
})

```

If that does not solve your issue, feel free to reopen this.

**Comment by Zazcallabah** [comment]
Ok, so the issue is now that the error message from pinia was suppressed.

expected: 

```getActivePinia was called with no active Pinia. Did you forget to install pinia?```

actual:

```Cannot read properties of undefined (reading 'msg')```

**Comment by Zazcallabah** [comment]
Also, kind of scummy to close the issue and say "feel free to reopen" when non-contributors don't have that access.

Also, kind of dismissive to say "you don't have to use X" about things in a minimalistic reproduction repo.

**Comment by Zazcallabah** [comment]
☝️ @cexbrayat (sorry for ping, idk if you get notifications on closed issues)

**Comment by cexbrayat** [comment]
@Zazcallabah No worries about the ping. We see the notifications, we're just less reactive on Sundays

It wasn't intended to be dismissive: I was just pointing out what I think is a helpful tip about props, and that you might not know. You'll see that if you don't use `props.` in the template, then the pinia error message is shown, this is why I thought this was relevant.

The error is also not specific to Pinia, as:

```ts
const counter = () => {
  throw new Error();
};
counter();
```

produces the same result as well.

I'm not sure VTU can do much in this case, as the error comes from vue itself, and the error message makes sense: the setup function throws so `props` is undefined. I tried to dig a little, but I don't think we can do better
