### ISSUE TITLE
Bug: activating/deactivating a component is not more possible in v2

### ISSUE THREAD

**Issue by mkarras** [vuejs/test-utils#1968]
**Describe the bug**
In vue-utils-v1 it was possible to deactivate a component via `wrapper.vm.$options.deactivated[0].call(wrapper.vm)`. This is needed to test code that depends on the `onDeactivated` hook. Analogous the `onActivated` hook.

In Vue 3 you can access the hook with `wrapper.vm.da[0]()`. See https://github.com/vuejs/core/blob/v3.2.47/packages/runtime-core/src/enums.ts for the other hooks.

**To Reproduce**
I guess because of internal changes due to Vue 3 `wrapper.vm.$options` is not more defined. But `wrapper.vm.da[0]`, is also not defined in vue test utils v2 (using `2.2.7`).

**Expected behavior**
 `wrapper.vm.da[0]()` or any other way (if i missed it please let me know! <3) should deactivate the component, so that the `onDeactivated` hook and its code inside is triggered.

A dream would be functions analogous to the unmount function `wrapper.unmount()`.
E.g. `wrapper.deactivate()` and `wrapper.activate()`.

**Comment by cexbrayat** [comment]
Hi @mkarras 

There is indeed no methods to trigger the activation/deactivation of a component on the wrapper.

You can currently test these hooks with something like this, to give you a rough idea

https://stackblitz.com/edit/vitest-dev-vitest-ip9dvu?file=test/basic.test.ts

```vue
<script setup lang="ts">
import { onDeactivated } from 'vue';
onDeactivated(() => {
  console.log('deactivated')
})
</script>

<template>
  <div>Hello</div>
</template>
```

```ts
import { mount } from '@vue/test-utils';
import { defineComponent, ref } from 'vue';
import Hello from '../components/Hello.vue';

test('mount component', async () => {
  vi.spyOn(console, 'log');
  const KeepAliveWrapper = defineComponent({
    components: { Hello },
    template: `<KeepAlive>
        <Hello v-if="!deactivate"/>
      </KeepAlive>
      <button @click="deactivate = true">Deactivate</button>
      `,
    setup() {
      const deactivate = ref(false);
      return { deactivate };
    },
  });

  const wrapper = mount(KeepAliveWrapper);

  expect(wrapper.text()).toContain('Hello');
  expect(console.log).not.toHaveBeenCalledWith('deactivated');

  await wrapper.get('button').trigger('click');

  expect(wrapper.text()).not.toContain('Hello');
  expect(console.log).toHaveBeenCalledWith('deactivated');
});
```

I'm not sure we need to add explicit functions to VTU for this.

WDYT @lmiller1990 @freakzlike ?

**Comment by mkarras** [comment]
Thank you @cexbrayat for your quick reply!
I like this approach in some way because it creates the real deactivating behavior from Vue. The downside is that it is a little bit laborious in comparison to just calling a function.

before:
```
it('should do whatever component gets deactivated', async () => {
    const wrapper = createWrapper({ label: 'label' });

    // deactivate component
    wrapper.vm.$options.deactivated[0].call(wrapper.vm);

    expect(whatever).toHaveBeenCalledTimes(1);
    ...
  });
```

I will try to write some util function to reuse this approach for different test suites. To avoid doing it multiple times. Maybe something like this:
```
it('should do whatever component gets deactivated', async () => {
    const { deactivate } = useKeepAlive(Component);

     // deactivate component
    deactivate();

    expect(whatever).toHaveBeenCalledTimes(1);
    ...
  });

**Comment by cexbrayat** [comment]
@mkarras 👍 I think it can be easily made reusable (that's what we do in our teams). 
I'll close for now and we'll reconsider in the future if more people look for something like this!
