### ISSUE TITLE
"vue-tsc" fails with "error TS2769: No overload matches this call" in "strict" mode

### ISSUE THREAD

**Issue by tinobino** [vuejs/test-utils#1973]
**Describe the bug**
`vue-tsc` fails with "error TS2769: No overload matches this call" in when "strict" mode is configured in "tsconfig.json".

If the `defineEmits` part in the component is removed `vue-tsc` doesn't complain. Seems that this issue is somehow related with Vue version 3.2.46.

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-nwzj9x?file=components%2FSlotComponent.vue,test%2FSlotComponent.test.ts,package.json&initialPath=__vitest

**Expected behavior**
`vue-tsc` does not fail for the example given.

**Comment by cexbrayat** [comment]
Hi @tinobino and thanks for the repro

After looking at your repro, it does look like there is an issue, but I don't know if that should be fixed in Vue core, VTU or Volar.

The error goes away if:
- Vue v3.2.45 is used
- if `defineEmits` is removed
- More surprising, if `<slot />` is removed from the template

Let me ping @johnsoncodehk as he may have some idea of what's going on

**Comment by johnsoncodehk** [comment]
It seems due to `DefineComponent` type updates. It should fix if update this line: https://github.com/vuejs/test-utils/blob/f68ceee8675e3274eb80e6b1f5a99cfe093be4ce/src/mount.ts#L204

```diff
- export declare function mount<T extends DefineComponent<any, any, any, any, any>>(component: T, options?: ComponentMountingOptions<T>): VueWrapper<InstanceType<T>>;
+ export declare function mount<T extends DefineComponent<any, any, any, any, any, any, any, any, any, any>>(component: T, options?: ComponentMountingOptions<T>): VueWrapper<InstanceType<T>>;
```

**Comment by cexbrayat** [comment]
@johnsoncodehk Thanks for taking a look! Sadly, it doesn't look like it's fixing the issue
See https://github.com/vuejs/test-utils/pull/1974

**Comment by tinobino** [comment]
Hi guys! Any updates on this? This issue prevents us from upgrade to latest vue version.

**Comment by cexbrayat** [comment]
@johnsoncodehk kindly offered (on another channel) to refactor the types when he has time, so this issue will get fixed, but we can't give you a timeline.

In the meantime, you can still upgrade to the latest vue version, by adding an explication cast `mount(SlotComponent as any, {...})`. We understand this is not ideal, but that should unblock you to update

**Comment by spacedawwwg** [comment]
I've added this to a `env.d.ts` file for now and it seems to get us by

```

// TODO: Remove once https://github.com/vuejs/test-utils/issues/1973 is resolved
declare module '@vue/test-utils' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export function mount<T extends DefineComponent<any, any, any, any, any, any, any, any, any>>(
    component: T,
    options?: ComponentMountingOptions<T>
  ): VueWrapper<InstanceType<T>>;
}
```

**Comment by johnsoncodehk** [comment]
I will check it out next week.

**Comment by dschmidt** [comment]
> 

Thanks, just a heads up: this should be put in a module file (i.e. with at least one top level export or import - in doubt add `export {}`) to make it a type augmentation, otherwise it replaces the module types completely and e.g. `RouterLinkStub` won't be available anymore.

**Comment by johnsoncodehk** [comment]
Please track #2026

**Comment by cexbrayat** [comment]
Thanks to @johnsoncodehk , the issue should be fixed in the next release (I added a test based on @tinobino repro to make sure we don't have this again).
