### ISSUE TITLE
Feature request: docs example of useFetch / useLazyFetch

### ISSUE THREAD

**Issue by danielgroen** [vuejs/test-utils#1976]
Hi,

I ran in the following issue:
I want to mock a response of some standard nuxt methods as `useFetch` and `useLazyFetch`. However i can't see any examples in the docs. Also this question is around on the internet for a longer time without any answers.

Can this be added to the docs somewhere? Maybe in a "nuxt" section?

## Duplicate of issue:
https://stackoverflow.com/questions/73581342/how-to-mock-nuxts-uselazyfetch-method-with-vitest

## Environment:
- nuxt 3
- @vue/test-utils

**Comment by freakzlike** [comment]
I don't think this makes sense, because it has nothing to do with `@vue/test-utils`. `@vue/test-utils` is a low-level library to render and mount vue components for testing. This makes more sense on the `nuxt` docs: https://nuxt.com/docs/getting-started/testing

**Comment by cexbrayat** [comment]
I agree with @freakzlike , this would be too specific for our documentation, and nuxt is a bit special as it has auto-imports, etc.

You can check out https://github.com/danielroe/nuxt-vitest from one of the Nuxt contributors that can probably help you (it uses Vue Test Utils under the hood), but this is still a very young project
