### ISSUE TITLE
Bug: No hint where not overwritten, why not show 100% ？

### ISSUE THREAD

**Issue by ChaiMayor** [vuejs/test-utils#1981]
**Describe the bug**

The Uncovered Line no longer exists. Why isn't it 100%?
I don't know what this is, is it a bug or is it normal?

![image](https://user-images.githubusercontent.com/97388975/219250230-03d12de0-fbd3-45e6-a0ee-cf96000ef32e.png)

**To Reproduce**

The code can be found in this repository：https://github.com/ChaiMayor/hview-ui/tree/dev
dev branch based.

![image](https://user-images.githubusercontent.com/97388975/219251014-8bba40e8-4a55-40d9-96e3-6cca969c84ba.png)

Follow these steps:

1. git clone https://github.com/ChaiMayor/hview-ui.git

2. git checkout dev

3. pnpm i

4. pnpm run test on root dir

5. pnpm run coverage

 

**Expected behavior**

There is no hint where is not overwritten, so should it be displayed as 100%

**Comment by freakzlike** [comment]
Hello!
Thanks for the info, but this is not part of `@vue/test-utils`. You can post your issue on `vitest` here: https://github.com/vitest-dev/vitest
