### ISSUE TITLE
Feature request: Make it easier to wrap an arbitrary element/selector

### ISSUE THREAD

**Issue by ascott18** [vuejs/test-utils#1984]
**Is your feature request related to a problem? Please describe.**
When testing components that Teleport a node to somewhere else, I need to make a wrapper for that teleported HTML element. I can't use .findComponent, because the teleported node might not be a component, and finding by selector doesn't work because the teleported HTML is not in the DOM tree of my root mounted component.

Instead, I have to make the following utility:

```js
export function getWrapper(selector) {
  const el = document.querySelector(selector);
  if (el) return new DOMWrapper(el);
  else return createWrapperError("DOMWrapper");
}
```

This works, but there's a major footgun here because if you don't know about `createWrapperError`, the intuitive thing is to just always return a `DOMWrapper`. But, `DOMWrapper.exists()` always returns true, regardless of whether `element` is nullish or not.

**Describe the solution you'd like**
`DOMWrapper.exists` returns false if its element doesn't exist. 

OR export a function similar to the one I wrote above from vue-test-utils that includes this error handling.

**Describe alternatives you've considered**

Keep writing this wrapper function myself.

**Additional context**

If there's a better way of testing Teleport when it only teleports pure DOM nodes (not components), I'd love to see it added to https://test-utils.vuejs.org/guide/advanced/teleport.html.

**Comment by lmiller1990** [comment]
> `But, DOMWrapper.exists()` always returns true, regardless of whether element is nullish or not.

This seems like a bug - but according to our test suite, we have coverage for this. A DOM element that does not exists should return false for `exists()`. Here's the test: https://github.com/vuejs/test-utils/blob/main/tests/exists.spec.ts#L14

I could be missing something - can you reproduce this error in a minimal fashion?

**Comment by ascott18** [comment]
``` js
import { DOMWrapper } from "@vue/test-utils";
expect(new DOMWrapper(null).exists()).toBe(false); // fails, @vue/test-utils@2.2.10
```

**Comment by cexbrayat** [comment]
It looks like `BaseWrapper` defines `true` as the default value: https://github.com/vuejs/test-utils/blob/52b25f4bcc3df90de1dbd0fcc3d2008837486f40/src/baseWrapper.ts#L265-L267 and that `exists` is not overwritten in `DOMWrapper`. As it extends `BaseWrapper`, `exists` always returns true.

This looks like a bug, even if it probably went unnoticed as people usually don't build `DOMWrapper` themselves, but get it via `find` or `get`.

I think that adding a proper `exists` in `DOMWrapper` may solve the issue? Do you want to give it a try @ascott18 and open a PR?
