### ISSUE TITLE
[docs] Add documentation on hooks like `beforeEach` & `afterEach`

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/test-utils#1986]
**Is your feature request related to a problem? Please describe.**
I'm the author of UI lib [Anu](https://github.com/jd-solanki/anu) and use test utils for testing the components. I'm first time writing tests for vue app. My UI lib runs some configurations in [`install`](https://vuejs.org/guide/reusability/plugins.html) method via lib's [plugin](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/plugin.ts#L54-L74)

The issue is when I import the components and test it via vitest, `install` method doesn't get called and my all tests fail (_previously I wasn't doing any configuration in `install` method and everything was working fine_).

I searched the docs but didn't find the solution and then finally chatGPT indicated to use `beforeEach` and `afterEach` hook for this and now my tests are running as usual.

These hooks are used in router & teleport docs but aren't mentioned anywhere.

**Describe the solution you'd like**
Write docs on hooks.

**Describe alternatives you've considered**
chatGPT 😉 

**Additional context**
Additionally, It will be easy for me if you can answer "I have to write beforeEach & afterEach on top of all file or have to import file on top that contains these hooks, can't we just configure it once and VTU knows the plugin?"

Thanks 😇

**Comment by jd-solanki** [comment]
It looks like these are from [`vitest`](https://vitest.dev/api/#beforeeach), are they?

**Comment by cexbrayat** [comment]
@jd-solanki Yes, these are from vitest (or jest, as most testing libraries have something similar). This is not something we can document in VTU, so I'll close this issue

However, if I understand your use case correctly, I think you might be interested in the the `global.plugins` option of `mount`. See https://test-utils.vuejs.org/api/#global
