### ISSUE TITLE
Bug: Problem extending VueWrapper type definitions

### ISSUE THREAD

**Issue by mailok** [vuejs/test-utils#1999]
**Describe the bug**
I am following the steps in the documentation to have a properly typed plugin. But I run into the situation that I can't extend the `VueWrapper` types following the steps in the documentation.

**To Reproduce**

I am using these versions in my dependencies:
```
"typescript": "~4.7.4",
"vitest": "^0.29.2",
"vue": "^3.2.47",
"@vue/test-utils": "^2.3.0"
```

1-Create and add the following code to the file `vue-test-utils.d.ts`:

```
import type { DOMWrapper } from "@vue/test-utils";

declare module "@vue/test-utils" {
  export class VueWrapper {
    findByTestId(testId: string): DOMWrapper<Element>;
  }
}
```

2-Add the following code to `vitest.setup.ts`: 

```
const DataTestIdPlugin = (wrapper: VueWrapper) => {
  function findByTestId(selector: string) {
    return wrapper.find(`[data-test-id='${selector}']`);
  }
  return {
    findByTestId,
  };
};

config.plugins.VueWrapper.install(DataTestIdPlugin);
```

**Expected behavior**

I was expecting to have the definition of type xxx when I get a `VueWrapper`.

```
const wrapper = mount(Component);
wrapper.findByTestId()
```

My tests are working, so the plugin is working the way I expect it to. But I have Typescript telling me that this function does not exist in `VueWrapper`.

**Additional context**
 
 I was checking its unit tests for the plugin feature and found that instead of `class` it use `interface`, but it didn't work for me either: 
 
```
 declare module '../../src/vueWrapper' {
  interface VueWrapper {
    width(): number
    $el: Element
    myMethod(): void
    greet: (name: string) => string
  }
}
```

Another solution I found on StackOverflow suggests creating a new type definition that extends `VueWrapper` and using it as follows:

`const wrapper = mount(MyComponent) as MyExtendedVueWrapper`;

But.... wouldn't want to have to do that for each of my tests or have another alternative function to `mount` 😩

**Comment by mailok** [comment]
I tried moving this:

```
import type { DOMWrapper } from "@vue/test-utils";

declare module "@vue/test-utils" {
  export class VueWrapper {
    findByTestId(testId: string): DOMWrapper<Element>;
  }
}
```

to the file `env.d.ts` and it worked correctly 🤷‍♂️

**Comment by mailok** [comment]
I found out what the problem was. I just had to include the file `vue-test-utils.d.ts` in the include of my `tsconfig.app.json`.

```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json", "vue-test-utils.d.ts"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

It would be great to have this tip in the documentation. How can I help to add it?

**Comment by cexbrayat** [comment]
@mailok Yes, the file must be included in what TypeScript compiles.
Feel free to open a PR to add it to the docs https://github.com/vuejs/test-utils/blob/main/docs/guide/extending-vtu/plugins.md 👍
