### ISSUE TITLE
Bug: Dynamic Components with Async Components

### ISSUE THREAD

**Issue by maximilianruesch** [vuejs/test-utils#2000]
**Describe the bug**

When creating a dynamic component (`<component :is="..." />`) in a template through a `v-for` in combination with an async component (defined with `defineAsyncComponent`), the dynamic component does not render. This fails the test in the reproduction as the necessary string is never given.

However when normally importing the component in `<script setup>` and adding it to the list of components to be rendered (async via a function as seen in the reproduction), it shows up and the corresponding test passes.

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-k153mh?file=package.json

Execute `npm run test` and analyse the test outputs, especially the `console.log(...)` statements indicating the addition of the component.

**Expected behavior**
Dynamic components should be rendered even if async components are used as their `:is="..."` value.

**Related information:**
```
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.98 GB / 15.58 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  npmPackages:
    @vue/test-utils: ^2.3.0 => 2.3.0 
    vitest: ^0.29.2 => 0.29.2 
    vue: ^3.2.45 => 3.2.45
```

**Additional context**
In live context, this worked, so i assume it not to be a  `vue/vue` problem in general. However, i am not 100% certain on this.

**Comment by cexbrayat** [comment]
Hi @maximilianruesch and thanks for the repro

This is expected when using Vite/Vitest and not really related to Vue/VTU: you have to use `vi.dynamicImportSettled`  (https://vitest.dev/api/vi.html#vi-dynamicimportsettled) when using dynamic imports

The test should then succeed:
```ts
test('can mount a component async', async () => {
  const wrapper = await mount(AsAsync);

  wrapper.vm.addHelloAsync();
  await wrapper.vm.$nextTick();
  await vi.dynamicImportSettled();

  // Assert key text of Hello component exists
  expect(wrapper.html()).toContain('HELLO');
});
```

**Comment by maximilianruesch** [comment]
Hi @cexbrayat,

thanks for the fast reply.
I will try the fix in my own code tonight and then update you here.

Anyways, thanks again :)

**Comment by maximilianruesch** [comment]
Update: This seemed to work (and makes a lot of sense when you think about why it should). So i may be reminded to read the docs more carefully next time :sweat_smile: 

Thanks :)

**Comment by cexbrayat** [comment]
No worries, this is hard to find as it is not very well documented in Vitest (as it is not Vue specific) and not mentioned in VTU docs (as it is Vitest specific and it used to work out of the box with Webpack/Jest)
