### ISSUE TITLE
Bug: Support Adding variables outside the target element when triggering onChange Event.

### ISSUE THREAD

**Issue by vangakirankumarreddy** [vuejs/test-utils#2003]
**Describe the bug**

In Vue test utils Version 1 when working with the [Freshworks Crayons Library](https://crayons.freshworks.com/components/core/checkbox/#demo) we used to emit and mock the complete event object.
If you notice we pass detail object.

```bash
   const event = {
      type: 'drop',
      target: {
        getAttribute: () => 'app',
        name: 'app',
        value: 'test',
      },
      detail: { 
        meta: {
          checked: true,
        },
      },
      preventDefault: jest.fn(),
    };
    wrapper.find('fw-checkbox-stub').vm.$emit('fwChange', event);
    expect(wrapper.vm.appDetails.app).toBe(true); ✅ This works
```
Now when migrated to vue test utils v2, we no longer have $emit, instead, a trigger was introduced.
The problem with the trigger is I can't mock the above event method. partially was able to mock the field inside the target object.

```bash
    const input = wrapper.find('fw-checkbox');
    input.element.value = 'test'; ✅ // able to add variables on the element & capture using event.target
    input.element.type = 'drop'; ✅
    input.element.name = 'app'; ✅
    input.element.getAttribute = () => 'app'; ✅
    input.detail = { ❌ // unable to add detail object.
      meta: {
        checked: true,
      },
    };
    input.trigger('fwChange');
    await flushPromises();

    expect(wrapper.vm.appName).toBe('test'); ✅ This works
    expect(wrapper.vm.localNewAppInitialDetails.app).toBe(true);  ❌ // Since I was reading event.detail.meta.checkbox // this will fail.
event.detail is undefined in this case.
```

**To Reproduce**

**Expected behavior**

If you suggest any change or workaround by allowing other variables to add outside of the target object it would be helpful

```bash

    input.detail = { ❌ // unable to add detail object.
      meta: {
        checked: true,
      },
    };
    
    or 
    
     input.element.detail = { ❌ // unable to add detail object.
      meta: {
        checked: true,
      },
    };
    
    I can capture event.detail.meta.checked;
    
    
    **Method I use when fwChange is triggered on the checkbox.**
     setFieldValue(ev) {
     const name = ev.target.getAttribute('name');
     const value = ev.detail.meta.checked; //I want this case to resolved.
     }
```

**Related information:**

**Additional context**

**Comment by cexbrayat** [comment]
Hi @vangakirankumarreddy 

If you were using a stub for `fw-checkbox` previously, can't you do the same now? You could use a custom `FwCheckboxStub` in your test, which would offer a function to emit the event you want.

Pseudo-code:

```ts
const FwCheckboxStub = defineComponent({
  setup(props, { emit }) {
    emitFwChange() {
      emit('fwChange', { /* add your event detail */ })
    }
  }
});

// test 
const wrapper = mount(MyComponent, { global: { stubs: { 'fw-checkbox': FwCheckboxStub } } });
await wrapper.get(FwCheckboxStub).vm.emitFwChange();
```

If that doesn't help, can you provide us a small repro online using https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/vue?initialPath=__vitest__ ? That would help us understand what you want to achieve

**Comment by cexbrayat** [comment]
@vangakirankumarreddy Did the previous comment helped or if not, did you manage to build a repro?

**Comment by cexbrayat** [comment]
Closing as we did not hear back from the OP, and we don't have an actionable repro
