### ISSUE TITLE
Bug: document calls should fail during ssr test

### ISSUE THREAD

**Issue by webistomin** [vuejs/test-utils#2020]
**Describe the bug**
Correct me if I'm wrong, but during `ssr` any access to `document` should fail. I want to test my component in a `node` environment, but `vue test utils` throws an error.

It works if I change environment to `JSDOM`, but then my component will not throw an error.

```
ReferenceError: document is not defined
 ❯ createInstance ../../../node_modules/.pnpm/@vue+test-utils@2.3.1/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.mjs:8020:14
 ❯ Module.renderToString ../../../node_modules/.pnpm/@vue+test-utils@2.3.1/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.mjs:8281:15
```

I think we shouldn't use `document` inside `createInstance` function

https://github.com/vuejs/test-utils/blob/main/src/createInstance.ts#L114
https://github.com/vuejs/test-utils/blob/main/src/createInstance.ts#L119

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-nnsmqh?initialPath=__vitest__

**Expected behavior**
Tests work in `node` environment

**Related information:**
```
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
    Memory: 3.58 GB / 15.83 GB
  npmPackages:
    vitest: ^0.29.2 => 0.29.2
```

**Comment by lmiller1990** [comment]
Yeah, I think you are correct - no DOM in Node.js.

Do we just wrap this in a check? Something like `if (globalThis.window) { /* we are in a browser env */ }`

Although we now have `renderToString` - shouldn't you just use that?

**Comment by webistomin** [comment]
I'm just used `renderToString`. Look at the [example](https://stackblitz.com/edit/vitest-dev-vitest-nnsmqh?file=package.json&initialPath=__vitest) I provided.

```vue
<script setup lang="ts">
console.log(document.documentElement)
</script>

<template>
  <div>Hello world</div>
</template>
```

```ts
test('SSR', async () => {
  const html = await renderToString(Hello)

  expect(html).toEqual('<div>Hello world</div>')
});
```

This test should fail with `document is not defined` error not inside `vue-test-utils` helpers but inside a component.
