### ISSUE TITLE
Bug: Custom directives as functions don't work as expected

### ISSUE THREAD

**Issue by alextana92** [vuejs/test-utils#2022]
## Custom directives as functions don't work as expected

**The issue**
I have a custom directive that converts markdown to html, instead of being an object it's a function and it passes the current `app` instance to the directive to have access to other methods in `globalProperties`

Now, I've tried my custom directive on a Vue 3 component and it works fine, object directives also work ok and the tests pass - as soon as the directive needs to be called as a function it won't work in the tests though

Example:
```js
// other stuff
export default function (app) {
    return {
        beforeMount (el, binding, vnode) {
            el.markdown = new MarkdownDirective(app, el, binding)
            el.markdown.setContent(el, el.markdown.html(el, binding))
        },
        updated (el, binding, vnode) {
            el.markdown.setContent(el, el.markdown.html(el, binding))
        }
    }
}
```
and in my test:
```js
import { createApp } from 'vue'

const app = createApp()

config.global.directives = {
    markdown: markdown(app) // works ok
}
config.global.directives = {
    markdown: markdown // doesn't work
}
```

but I could not find a way to make this work without importing `createApp` which I'd like to avoid, especially because my directive then needs to use a plugin which will then be bound to the wrong `app` instance

**Expected behaviour**
```js
config.global.directives = {
    markdown: markdown // maybe check if this is a function and pass the instance to it behind the scenes if that's the case?
}

config.global.plugins = [new Strings()]
```

I'm completely out of my depth here but I looked at the source code and drafted something super naive, like:
`src/createInstance.ts`
![image](https://user-images.githubusercontent.com/124579168/230210408-8ca57162-c6df-4278-8e84-4782a275e7fe.png)
(I didn't know how to test this either)

I've created it below, this won't work, but you can see that if you don't call `markdown: markdown()` the directive doesn't get called at all:
https://stackblitz.com/edit/vitest-dev-vitest-tm2zkk?file=test/basic.test.ts

My issue here is that I'd like it to be called and I'd like to have a way for the test to use the correct app instance when that happens

let me know if it's unclear or if it's a non-issue and I'm just missing something super simple 🙂

Thank you!

**Related information:**
```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 53.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  npmPackages:
    @vue/test-utils: ^2.3.0 => 2.3.0
    jest: ^28.1.3 => 28.1.3
    vue: ^3.2.46 => 3.2.47
```

**Additional context**
This is being ported to v2 from v1 and with localVue on v1 it worked perfectly

**Comment by freakzlike** [comment]
Hi @alextana92,

Just to make sure I understand your example correctly:
In your real app you would register your directive with `app.directive('markdown', markdown(app))` correct?

I think this is a bit specific usage and I don't think it is possible to just check for a `function` and call it with `app` as argument. There is a shorthand for directives which is already a function https://vuejs.org/guide/reusability/custom-directives.html#function-shorthand
