### ISSUE TITLE
Bug: You can only use setProps on your mounted component when setProps of a child component

### ISSUE THREAD

**Issue by renartius** [vuejs/test-utils#2029]
**Describe the bug**
I'm trying to setProps of a child component. I can get child component using getComponent but when I try to setProps an error occurs:

"Error: You can only use setProps on your mounted component"

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-2cimwj?file=test/basic.test.ts

**Expected behavior**
get child component and set props properly

**Related information:**
nm packages:
├── @quasar/extras@1.15.10
├── @quasar/vite-plugin@1.3.0
├── @rushstack/eslint-patch@1.2.0
├── @testing-library/vue@6.6.1
├── @types/node@18.11.19
├── @typescript-eslint/eslint-plugin@5.51.0
├── @typescript-eslint/parser@5.51.0
├── @vitejs/plugin-vue@4.0.0
├── @vitest/coverage-istanbul@0.28.5
├── @vue/eslint-config-prettier@7.0.0
├── @vue/eslint-config-typescript@11.0.2
├── @vue/test-utils@2.3.2
├── @vue/tsconfig@0.1.3
├── aws-amplify@5.0.18
├── axios@1.3.2
├── echarts@5.4.1
├── eslint-config-prettier@8.6.0
├── eslint-plugin-prettier@4.2.1
├── eslint-plugin-vue@9.9.0
├── eslint@8.33.0
├── happy-dom@8.4.3
├── jsdom@21.1.0
├── npm-run-all@4.1.5
├── pinia-plugin-persistedstate@3.1.0
├── pinia@2.0.30
├── prettier@2.8.3
├── quasar@2.11.5
├── sass@1.32.12
├── typescript@4.7.4
├── vite-plugin-eslint@1.8.1
├── vite@4.1.1
├── vitest@0.28.5
├── vue-echarts@6.5.4
├── vue-router@4.1.6
├── vue-tsc@1.0.24
└── vue@3.2.47

**Additional context**

**Comment by freakzlike** [comment]
Hi @renartius 

Can you explain what your use case is? From my point of view, I don't see a valid reason to do this. In the real app the child props are always set by the parent component and this should be the same for the tests to test the actual behavior of your app. In case you want to test different scenarios for the child component, then I suggest to create a separate unit test for the child component.

**Comment by renartius** [comment]
Hi @freakzlike 
I built a simple test just to reproduce the problem. Sorry if it doesn't represent the real case.

In my real scenario, I have a child component, like a select, that accepts a list of options and emits the selected value (along with some other functions that justify it being a component and not just a regular select).
So, I've used it in another component, like a form, with validation.
When users press the submit button in that form, it checks the validation of the child components (basically, it tests the emitted value of the selected option).
I agree that a child component can (and in this case, it is) be passed by props from the parent, but how can I test that scenario?

**Comment by lmiller1990** [comment]
Can you share a minimal reproduction for the test you'd like to write? It will greatly help with getting recommendations. Also, if there is a bug, we could add your test to the test suite and use it to fix the regression.

It looks like the case you describe is intended not to work, according to https://github.com/vuejs/test-utils/blob/main/tests/setProps.spec.ts#L144-L146. I wonder if it *should* work - I cannot quite remember why this decision was made. 

I'd still like to see an actual real use case (with code) to justify looking into this - ideally you'd test this as described by @freakzlike.
