### ISSUE TITLE
Bug: Stubbed Teleport does not update reactively

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/test-utils#2033]
**Describe the bug**

Ref: https://github.com/vuejs/test-utils/issues/798#issuecomment-1513197973

**To Reproduce**

Here: https://github.com/vuejs/test-utils/issues/798#issuecomment-1513197973

**Expected behavior**

Should update count to 1.

**Related information:**

**Additional context**

**Comment by Made-of-Clay** [comment]
@lmiller1990, I've successfully reproduced the behavior from my reproduction repo in the [teleport automated test](https://github.com/Made-of-Clay/test-utils/blob/main/tests/features/teleport.spec.ts#L135) and pushed it to a forked branch (so you can see). 

After some digging, I suspect it has to do with the slots variable passed into the `setup()` function not being reactive. [The Vue docs note](https://vuejs.org/api/composition-api-setup.html#setup-context) that `attrs` and `slots` are not reactive (which I just learned). I also suspect [Evan's comment in this thread](https://github.com/vuejs/core/issues/6202#issuecomment-1278776852) might be related to the test-utils situation; [the `stubComponentsTransformer` uses `slots` to make the stub](https://github.com/Made-of-Clay/test-utils/blob/main/src/vnodeTransformers/stubComponentsTransformer.ts#L83).

I need to come back to this later. I thought I'd share my findings in case someone else or you get a clever idea.

**Comment by doutatsu** [comment]
Having issues myself as well, so here to keep an eye on the progress resolving this issue

**Comment by doutatsu** [comment]
Dropping by here again - any updates on this?
