### ISSUE TITLE
Bug: Default props reported as missing when using <script setup> & withDefaults

### ISSUE THREAD

**Issue by conorhooley** [vuejs/test-utils#2041]
**Describe the bug**
This is fairly straightforward, to the extent that I'm suspecting that I'm missing something glaringly obvious. If so, mea culpa. If not, however, there does not appear to be much information available w/r/t how to get things configured properly in the following use case.

I'm working on a Vue 3 project, written in TS and using <script setup>. For testing, I'm using vitest & VTU. When testing various cases against components that define props using the `withDefaults(defineProps<Props>(), {})`-style syntax, I am consistently met with a `[Vue warn]: Missing required prop: [prop name here]` warning if they are not explicitly passed into the `shallowMount` or `mount` method.

**To Reproduce**
Minimal reproduction here: https://stackblitz.com/edit/vitest-dev-vitest-vrkckj?file=components/App.vue

You should be able to comment/uncomment the data nested in `defaultProps` within the `HelloWorld.spec.js` file to observe the issue I'm referring to. I'm also dumping the html in the test case to show that the default prop is being set and rendered correctly when the component is mounted... but I'm still getting a warning about a missing prop anyway.

![image](https://user-images.githubusercontent.com/103948900/235535270-ea28e996-a687-4b9f-9e59-343540a9bd4c.png)

**Expected behavior**
Props that have default values set using the `withDefaults` macro should not trigger warnings in the test runner.

**Comment by lmiller1990** [comment]
Hm interesting - I've got dozens of tests using Test Utils (via `cypress/vue`) that work fine with `withDefaults`, eg: https://github.com/cypress-io/cypress/blob/03a263d37b6e0632935a1dff9d1a7f4057d5d61e/packages/app/src/components/FileMatchButton.cy.tsx

It does look like everything works correctly, sans the warning. I think we need to track down where the warning gets printed in Vue and see where/how it's triggered, and why that'd be different here. 🤔

**Comment by lmiller1990** [comment]
Goes here: https://github.com/vuejs/core/blob/4e2607a3d316b6d8784c1af5f6e96cc495b74416/packages/runtime-core/src/componentProps.ts#L626

**Comment by freakzlike** [comment]
Hi @conorhooley,
AFAIK you need to set the prop as optional with `message?: string`.

From vue.js docs:
> ... and ensures the returned props type has the optional flags removed for properties that do have default values declared.
https://vuejs.org/api/sfc-script-setup.html#typescript-only-features

**Comment by conorhooley** [comment]
> Hi @conorhooley, AFAIK you still need to set the prop as optional with `message?: string`.
> 
> From vue.js docs:
> 
> > ... and ensures the returned props type has the optional flags removed for properties that do have default values declared.
> > https://vuejs.org/api/sfc-script-setup.html#typescript-only-features

Thanks! This works fine as a workaround. It would be really nice, however, to not have to compromise the type definitions. We treat them as pretty strict sources of truth, so defining `message` as optional when we want it to be the complete opposite seems like a quirk that will definitely invite some confusion.

But that also seems to be feedback that should go to the core Vue team.

**Comment by freakzlike** [comment]
Well, that's not a workaround it's by design, I guess. With the type definition in `defineProps` you define the interface for the component. In this case `message` is not required to pass from the parent component. However the type of `props` will be non-optional as mentioned in the docs the optional flag is removed when a default value is defined.

**Comment by conorhooley** [comment]
Yup, no argument or confusion on any of those points. The concern remains, however, that the type definition will still be misleading in the abstract at the very least. I'm a proponent of, as much of possible, representing things as what they actually are in the code. So in this case, is `message` optional? Will our team be treating it as such? No, not really. So representing it as such just feels a bit odd to me.

I believe Vue will also soon support imported prop definitions as well. So we may encounter use cases where we want to re-use some of our types, and want the prop to be required always but maybe _not_ always provide a default.

Obviously there's ways to make all of that work I'm just being a bit of a purist :slightly_smiling_face:. And again this is also probably far outside the realm of VTU's concerns.
