### ISSUE TITLE
Feature request: Vue 3.3 compatibility

### ISSUE THREAD

**Issue by dacoto97** [vuejs/test-utils#2042]
**Is your feature request related to a problem? Please describe.**
The dependencies link to vue 3.2 and the new version 3.3 is already out

**Describe the solution you'd like**
Update dependencies to vue 3.3

![CleanShot 2023-05-11 at 11 51 38](https://github.com/vuejs/test-utils/assets/16915053/995eb69c-62a5-45f1-be41-70298bdd22e6)

**Comment by dacoto97** [comment]
https://github.com/vuejs/test-utils/pull/2043

**Comment by cexbrayat** [comment]
Done by Renovate in #2046
