### ISSUE TITLE
Feature request: Add support for `app.runWithContext()`

### ISSUE THREAD

**Issue by posva** [vuejs/test-utils#2059]
This feature was introduced [here](https://github.com/vuejs/core/pull/7451) and it's now used by vue router and pinia. Adding this will help people use the new feature

Here is a currently failing test using only vue test utils

```ts
  it('runWithContext', () => {
    let app: App
    const wrapper = mount(
      {
        template: `<HasInjection />`,
        setup() {
          provide('hello', 'component')
          return {}
        },
        components: {
          HasInjection: {
            setup() {
              const globalInjection = app!.runWithContext(() =>
                inject('hello', 'fallback')
              )
              const parentInjection = inject('hello', 'fallback')
              return { parentInjection, globalInjection }
            },
            template: `<div>{{ parentInjection }};{{ globalInjection }}</div>`,
          },
        },
      },
      {
        global: {
          provide: {
            hello: 'global',
          },
          plugins: [
            (a) => {
              app = a
            },
          ],
        },
      }
    )

    expect(wrapper.text()).toBe('component;global')
  })
```

**Comment by posva** [comment]
I added the failing test at https://github.com/vuejs/test-utils/tree/feat/runWithContext in case anybody wants to pick up the task

**Comment by cexbrayat** [comment]
I'm not yet familiar with this feature you implemented in core, but looking at 
https://github.com/vuejs/core/commit/869f3fb93e61400be4fd925e0850c2b1564749e2#diff-aba22e928f34a9ced3bf916c54a41b6facdfcb3e2caa18534dfae6d8a7e3cea6R56-R60
I thought this was expected if `runWIthContext` is in a component.

As `instance` will not be null, no? And in that case, the current app context will not be checked. 
Or am I missing something obvious?

**Comment by posva** [comment]
I'm getting a different behavior within pinia but apparently it's [the normal behavior](https://play.vuejs.org/#eNqFU02PmzAQ/SsjLhApgvuKrFTltLdKe+iFCyFD4hZsyx7SrRD/veMvQrL9OAA2fvPmzZvxnH3RurxNmL1kte2M0AQWadIwtPJyaDKyTfbaSDFqZQhm0EbdxBlhgd6oEXIOzdfjoxp1/F9WbuOY+RjAPVUFnRpHlCTkBdREQFdhYRASobtyOrT8B0HI79gRnsGSMhgjTwwf218nfITc2mFC+CmYSYKZ5DdeHZUk/OA6rmoazsAhnZJWWOLMji2WUOSJJd9DrlvDx/kuiK2r4AVXzhvCUQ8tIe8Aal9kxeu6Wg+yfebFlmTZyNWsC9JxMo74TVpqZYf7KH0P2Pf8fe+UfjazkU4vRQQcttCCzIQsspH44ZP0k+xIKAmTxXcnodjB7HQGDhHzMstnMYWvNkHKVutonVuWf7TpMqhTOySbGu9nyhRbkvSW3I6C1Rxeg6AEtL7kx6o8H4DhyTPyr4oe+1uEmIZCDk+7yRn0PKrv22E4td2PMDb5zhlJDfnsi39HBfO9nKWRC7c3TfN/7gnbmZofGJ56uzlPDVsRZZVmaL0ywbEwm293gz/V5rUH8FY6Q+9j8e+p1v4DsGbxWl5g3vKxFw5Tn0xEf/XK1iAPf1IbgurKJdjemOU3R9iO4g==). I think I must be forgetting something though. I wonder if it wouldn't be more consistent to give preference to the app within runWithContext, but that's a core thing anyway. Sorry 😅
