### ISSUE TITLE
Bug: Component is not rendered correctly and I'm getting an Warning in the logging "ResolveComponent can only be used in render() or setup()"

### ISSUE THREAD

**Issue by RALGIE** [vuejs/test-utils#2071]
I have a problem, my test does not render components that are imported from an higher relative path.

What I mean by this: I have a generic package with components for example generic-components. In my component that I want to test I import the button as follows import MyActionButton from '../../../../generic-components/src/components/MyActionButton.vue';

When I execute the vitest run command I get the following warning in the console resolveComponent can only be used in render() or setup(). The snapshot from the component that uses the MyActionButton is not correct and displays a Warning that the component is not rendered correctly. When I build the package it renders the component correctly.

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-71ydw6

**Expected behavior**
I would expect that the component is renders correctly. The test wil fail because the component is not rendered at al.

**Related information:**
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 10.69 GB / 31.21 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @vue/test-utils: ^2.3.2 => 2.3.2 
    vitest: ^0.30.1 => 0.31.0 
    vue: ~3.2.37 => 3.3.2

**Comment by cexbrayat** [comment]
This warning is not from VTU, and usually results from having multiple Vue instances. 

You probably need to fix the Vite/Vitest configurations of the project, but I don't know exactly how. Maybe the imports should not be relative between projects, but maybe it should use the built version, or use something like https://pnpm.io/workspaces.

There are too many things in your reproduction to help. If I were you, I would try to generate a smaller reproduction (just vitest without vitest-jest, no jquery, no generic loader, simple components, etc.) and maybe you'll find the issue in your configuration. When you have a smaller repro, maybe you can ask a question on the Vitest repo and someone will know how to handle this case.
