### ISSUE TITLE
PascalCase not working for stubs `config.global.stubs` and Transition / TransitionGroup / Teleport

### ISSUE THREAD

**Issue by lbineau** [vuejs/test-utils#2072]
## Issue
Here is a sample of my testing code as per the documentation https://test-utils.vuejs.org/api/#global-stubs (**please pay attention to the PascalCase / kebab-case notations**)

Given this simplified Vue component (`v-if="true"` to simplify the logic)
```vue
<Transition>
  <MyComponent v-if="true" />
  <MyOtherComponent v-if="true" />
</Transition>
```

### 1. Following the documentation I put all global stubs in PascalCase:

```js
config.global.stubs = {
  MyComponent: true,
  MyOtherComponent: false
}
const wrapper = shallowMount(Component)
expect(wrapper).toMatchSnapshot()
```
It produces the following result: the Transition `slot` content is removed while it should not.
```html
<transition-stub name="fade" appear="false" persisted="false" css="true"></transition-stub>
```

### 2. By reading another part of the documentation I understood I overrode the `Transition` stub, so it was considered as a regular Stub due to `shallowMount` behavior. I added it back to the stub object, as **PascalCase** as the documentation refers to:
> It stubs Transition and TransitionGroup by **default**.

```js
config.global.stubs = {
  MyComponent: true,
  MyOtherComponent: false,
  Transition: true
}
```

But the snapshot was still showing the same (no `slot` content)
```html
<transition-stub name="fade" appear="false" persisted="false" css="true"></transition-stub>
```

### 3. After reading the source code I found out that the default stubs are in **kebab-case**:
```js
config.global.stubs = {
  transition: true,
  'transition-group': true
}
```

So I needed to convert the transition component to **kebab-case**
```js
config.global.stubs = {
  MyComponent: true,
  MyOtherComponent: false,
  transition: true
}
```

The snapshot is now working and showing the `slot` content
```html
<transition-stub name="fade" appear="false" persisted="false" css="true">
  <my-component-stub></my-component-stub>
  <p>hello from MyOtherComponent</p>
</transition-stub>
```

## Solution
It seems `createStubComponentsTransformer` is testing both kebab-case and PascalCase for some Vue built-in components ([`keep-alive`](https://github.com/vuejs/test-utils/blob/072e936c95b358c7c40f12bb0958750d6b1fb6ec/src/vnodeTransformers/stubComponentsTransformer.ts#L150) / [`KeepAlive`](https://github.com/vuejs/test-utils/blob/072e936c95b358c7c40f12bb0958750d6b1fb6ec/src/vnodeTransformers/stubComponentsTransformer.ts#L151)) but not for others [`transition`](https://github.com/vuejs/test-utils/blob/072e936c95b358c7c40f12bb0958750d6b1fb6ec/src/vnodeTransformers/stubComponentsTransformer.ts#L163), [`transition-group`](https://github.com/vuejs/test-utils/blob/072e936c95b358c7c40f12bb0958750d6b1fb6ec/src/vnodeTransformers/stubComponentsTransformer.ts#L176), [`teleport`](https://github.com/vuejs/test-utils/blob/072e936c95b358c7c40f12bb0958750d6b1fb6ec/src/vnodeTransformers/stubComponentsTransformer.ts#L138) which are only tested against the kebab-case version.

So the solution would be to apply the same logic as `KeepAlive`.

## Side note

I've solved my issue in a more elegant way by extending the default global stubs object.
```js
config.global.stubs = {
  ...config.global.stubs,
  MyComponent: true,
  MyOtherComponent: false
}
```

**Comment by cexbrayat** [comment]
@lbineau Yeah I remember fixing it for KeepAlive when someone opened an issue
Would you like to try and open a PR for the others? That would be a great help. You can do as I did in f69bc37a35aa88606b98c22bbfac79dc0e8072e8
