### ISSUE TITLE
Docs: weird interaction between Vitest `vi.setSystemTime` and VTU `mount`

### ISSUE THREAD

**Issue by aentwist** [vuejs/test-utils#2074]
**Describe the bug**

When using `mount` before `vi.setSystemTime`, the mounted component behaves erratically. When using `mount` after `vi.setSystemTime`, it works as expected. At the very least this needs to be documented prominently. It just cost me 4 hours, and I see numerous other related issues that have been addressed in the past. Ideally, the calls would be order-indifferent.

**To Reproduce**

https://github.com/aentwist/set-system-time-bug

It is minimal so I'll include it here.

Get going with a component.

```vue
<template>
  <div class="home-view">
    <button type="button" @click="showMessage = !showMessage">Toggle</button>
    <div v-if="showMessage">hello, world</div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const showMessage = ref(false);
</script>
```

Add a test.

```typescript
import { describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";
import HomeView from "../HomeView.vue";

describe("HomeView", () => {
  it("shows a message when the button is toggled", async () => {
    vi.useFakeTimers();
    vi.setSystemTime("2000-01-01T00:00Z");

    const wrapper = mount(HomeView);

    const btn = wrapper.find("button");
    expect(btn).toBeTruthy();

    await btn.trigger("click");
    console.log(wrapper.text());
    expect(wrapper.text()).toContain("hello, world");

    vi.useRealTimers();
  });
});
```

The test works, as expected. Now move `vi.setSystemTime` to after `mount`. The test fails. See the console output in both cases.

**Expected behavior**

DOM updates

**Actual**

DOM doesn't update when called in the bugged order

**Comment by cexbrayat** [comment]
I think I know what's going on, and I think this is expected.

Vue (core) compares the timestamp of the events to workaround an edge bug: https://github.com/vuejs/core/blob/main/packages/runtime-dom/src/modules/events.ts#L100-L104

So when you mount the component, the current date is used for `invoker.attached`.
When you set the system time after that, all the date comparisons are going to return false.

I don't think we can do much in VTU to workaround that.
Would you like to open a PR to add a note about this in the documentation? We would greatly appreciate the help!

**Comment by lmiller1990** [comment]
I was about to post the same thing - I think this is tied to Vue core.

It's not clear what `setSystemTime` actually does in Vitest: https://vitest.dev/api/vi.html#vi-setsystemtime. 

I strongly doubt it actually changes the time on the OS level. I wonder what it's doing 🤔  

As an aside, relying on the system time in any test is not a great idea, changing that can mess up a lot of libraries (not just Vue). I learned this the hard way. What kind of test are you writing?

**Comment by cexbrayat** [comment]
@aentwist The issues you mention are vaguely related, but not exactly: your case is in fact a pure issue with how Vue works, not how VTU or Vitest work.
I confirm that we won't be able to help on VTU side, and the best we can do is to add a warning in the documentation 👍

**Comment by cexbrayat** [comment]
@aentwist Are you still willing to update the docs to add a mention of the problem so we can close the issue?

**Comment by aentwist** [comment]
Yes, after a quick look where do we want it (besides in the API docs)? It feels wrong to put it on the [front page](https://test-utils.vuejs.org/guide/#what-is-vue-test-utils) but that is really the only place it fits in the guide since it is learn by example and each page is hyper-specific. Would feel way better in the [Vitest docs](https://vitest.dev/guide/mocking.html#dates) but unfortunately that doesn't make sense.

**Comment by lmiller1990** [comment]
Maybe FAQ? https://test-utils.vuejs.org/guide/faq/

We could rename the page "Common Issues" perhaps?

**Comment by aentwist** [comment]
I didn't even look at that page because it is "FAQ". But based on the current content it's a perfect fit! Thanks! Maybe "Troubleshooting" or something.

> It might be good to find out what the function actually does

Yeahhh not sure how generic I should make the note either. Already extended it to similarly mocking timers with Vitest even though I very specifically saw this when mocking dates with Vitest. I did this because they both use `vi.setSystemTime`. I wonder whether this goes beyond Vitest. Ah well.
