### ISSUE TITLE
Bug: Testing component with onBeforeRouteLeave hook raising "No active route record was found" warning

### ISSUE THREAD

**Issue by Ujemny** [vuejs/test-utils#2083]
**Describe the bug**
Whenever i want to test component, which is using `onBeforeRouteLeave` (or `onBeforeRouteUpdate`) - i'm getting a warning:

```
[Vue Router warn]: No active route record was found when calling `onBeforeRouteLeave()`. Make sure you call this function inside of a component child of <router-view>. Maybe you called it inside of App.vue?
```

That happen when we want to use real router - issue do not exists while using mocked router.

**To Reproduce**
https://stackblitz.com/edit/github-docpnd?file=src%2Fmain.ts

In provided example above - there is simple test, route configuration and two components.

`TestComponent` is simple component, which is rendered under `Stepper` component.

Whenever we mount in tests component, which is using `onBeforeRouteLeave` - warning is raised.

**Expected behavior**
No warning is raised.

**Related information:**
```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @vue/test-utils: ^2.3.2 => 2.3.2 
    vitest: ^0.31.0 => 0.31.4 
    vue: ^3.3.2 => 3.3.4 
```
**Additional context**

- I can see that mocking router works

Thank you!

**Comment by cexbrayat** [comment]
Hi @Ujemny 

Thanks for the repro, but I think you forgot to add your test.

Anyway, the warning comes from vue-router, and indicates that you did not mount your component inside a `RouterView`.
If you do so, then your test will not have a warning (my team uses this a lot).

If that does not fix the warning, then update the repro test and ping me, we'll take a look!

**Comment by cexbrayat** [comment]
Yes, you can do something like this:

```ts
describe('How test component is working', async () => {
  const App = defineComponent({
    template: '<RouterView />',
  });
  testRouter = createRouter({
    history: createWebHistory(),
    routes: [{ path: '/', component: TestComponent }],
  });
  beforeEach(async () => {
    wrapper = mount(App, {
      global: {
        plugins: [testRouter],
      },
    });
    await router.push('/');
  });

  it('Should render a text', async () => {
    expect(wrapper.text()).toBe('aaa');
  });
});
```

Of course, this is only necessary if you want to test onBeforeRouteLeave, or if you don't want to see the warning (you can also just ignore the warning).

**Comment by Ujemny** [comment]
Thank you! 
I hoped that there is a way to not use second component, but that's fine. I will refactor my tests.

Many thanks for help!
