### ISSUE TITLE
Error: Cannot call classes on an empty DOMWrapper.

### ISSUE THREAD

**Issue by lixiaofa** [vuejs/test-utils#2095]
**Describe the bug**
Error: Cannot call classes on an empty DOMWrapper.
![image](https://github.com/vuejs/test-utils/assets/23230215/ebbef468-9bd4-494f-a896-fc9bcfcc6c8b)
![image](https://github.com/vuejs/test-utils/assets/23230215/a06c8d21-7308-493d-9b2a-f53491618e88)

Unable to obtain elements

**To Reproduce**
https://github.com/lixiaofa/fast-plus

**Expected behavior**
no error

**Related information:**
  "vitest": "^0.32.0",

**Comment by freakzlike** [comment]
Hi @lixiaofa,
can you provide a minimal online reproduction here: https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts. Therefore it's much easier for use to understand your issue and help much quicker.

**Comment by lixiaofa** [comment]
> Hi @lixiaofa, can you provide a minimal online reproduction here: https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts. Therefore it's much easier for use to understand your issue and help much quicker.

@freakzlike  see https://stackblitz.com/edit/github-8rjg3t?file=src%2Fcomponents%2Fsku%2Fsku.vue,src%2Fcomponents%2F__tests__%2Fsku.spec.ts,package.json

I can write like this？
const wrapper = mount(() => <Sku modelValue={true} />)

**Comment by freakzlike** [comment]
Our default reproduction link does not support JSX syntax, but you can simply write the default syntax instead:
```typescript
const wrapper = mount(Sku, {
  props: {
    modelValue: true
  }
});
```

There seem to be some more issues in your reproduction and I don't know the `vant` package aswell. However it seems the component is using `<teleport>` which requires some additional setup for testing. Please take a look here: https://test-utils.vuejs.org/guide/advanced/teleport.html

**Comment by lixiaofa** [comment]
> However it seems the component is using `<teleport>` which requires some additional setup for testing

see https://stackblitz.com/edit/github-8rjg3t?file=src%2Fcomponents%2Fsku%2Fsku.vue,src%2Fcomponents%2F__tests__%2Fsku.spec.ts,vitest.config.ts,package.json

Vant is a public component library
@freakzlike

**Comment by lixiaofa** [comment]
> @lixiaofa The test in the repro doesn't do much and succeeds. Can you complete it to reproduce the issue you have?

sorry
see  https://stackblitz.com/edit/github-8rjg3t?file=src%2Fcomponents%2Fsku%2Fsku.vue,src%2Fcomponents%2F__tests__%2Fsku.spec.ts,package.json,src%2Fcomponents%2FHelloWorld.vue

I just want to do a render test, 
how should I write it.
 it doesn't seem to get the dom element
@cexbrayat

**Comment by lixiaofa** [comment]
Thanks, I solved it. @cexbrayat @freakzlike
