### ISSUE TITLE
Feature request: send keyboard input strings

### ISSUE THREAD

**Issue by aentwist** [vuejs/test-utils#2105]
**Is your feature request related to a problem? Please describe.**

Currently, we can set input values with `input.setValue("arst")` or although I am not sure it is supported, send keyboard input with e.g. `input.trigger("keydown.a")` for each character.

- `setValue` is not natural as it is not what users do. See also https://github.com/vuejs/vue-test-utils/issues/960
  - Undefined behavior for inputs that have special characters - must be aware of implementation details - e.g. chip/tag inputs?
- `keydown` must be called for each character and is undesirable for long strings

**Describe the solution you'd like**

What I am really looking for here is something closer to [Selenium `sendKeys`](https://www.selenium.dev/documentation/webdriver/actions_api/keyboard/#send-keys). This is a more E2E type feature, but component tests are already encouraged to be mini-E2E tests, not relying on implementation details.

**Describe alternatives you've considered**

1. `setValue`, but this is unnatural and sketchy for chip inputs. Could work
1. Using very short strings via several `trigger("keydown")` calls
1. maybe something like

```typescript
aysnc function sendKeys(s: string): Promise<void> {
  const chars = s.split();
  await Promise.resolveAll(chars.map(async char => await input.trigger(`keydown.${char}`)));
}
```

**Additional context**

**Comment by cexbrayat** [comment]
I personally don't think we need such a specific feature, but maybe I'm not understandingg correctly your use-case.

What are you trying to test?

**Comment by aentwist** [comment]
Can't say I'm the best at explaining my ideas. Let me give the user story instead.

I want to test interactions with a Vuetify VCombobox with chips. It is a text input where users type terms, then press tab or enter to turn the term into a chip. This allows them to input multiple freeform text terms, and they are delimited clearly in a modern way. Like a multi-select but with freeform text instead of pre-defined options.

Now, I do not know the implementation details of this component - although I could figure them out. But VTU advertises that good tests are black-box and should come from a user's perspective. Users do not set input values, they type keys.

I am basically worried that setting an input value won't trigger the correct events and such because it isn't how the thing was intended to be used. On the other hand I *know* that typing terms following by tab or enter does work.

So maybe I am being lazy, but I found myself wishing I could test by typing keys programmatically instead of setting input values. Years ago I used Selenium pretty heavily, and I recalled their `sendKeys` method where I can 'type arbitrary strings on a keyboard', e.g. `sendKeys("search term 1\tsearch term 2\t")`.

What do you think about this idea?

**Comment by cexbrayat** [comment]
I understand, but I'm not sure it's worth adding another API to VTU for this use case. You can already do what you want, although you indeed need a bit more code.

Maybe you should take a look at Vue Testing Libray, or Playwright or Cypress component testing support: they may be what you're looking for and they all use VTU under the hood.

Or you could make a plugin https://test-utils.vuejs.org/fr/guide/extending-vtu/plugins.html to extend VTU with a helper that does exactly what you want.

**Comment by aentwist** [comment]
Sounds good. It would be something along the lines of the above for loop using `trigger("keydown.a")` right?

**Comment by cexbrayat** [comment]
Maybe yes. You can also check how Vuetify tests VCombobox. If I remember correctly, they use VTU to do so, so it could be a good inspiration.
