### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by skeezrxcco** [vuejs/test-utils#2106]
**Describe the bug**
After updating npm all my tests using vue test utils broke
(updating from 2.3.2 => 2.4.0)

**To Reproduce**
run tests

**Expected behavior**
to have tests passing but now i have a lot of errors pertaining to the `VueWrapper` and  `DOMWrapper.`
eg:

```bash
 ❯ Object.get node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.mjs:1517:27
    1515|                     return function () { return false; };
    1516|                 default:
    1517|                     throw new Error("Cannot call ".concat(String(prop), " on an empty ").concat(wrapperType, "."));

```

`package.json `
```json
  "dependencies": {
  etc..
    "happy-dom": "^8.9.0",
},
"devDependencies":{
        "vitest": "^0.29.3",
         "vue": "^3.2.41",
        "vite": "^3.1.8",
         "@vue/test-utils": "^2.4.0",
         etc...
}

```

To bandage this we downgraded the version. Could someone give advice on this situation?

**Comment by cexbrayat** [comment]
We had no answer from the OP. If the issue persists, feel free to ping me with a repro and I'll take a look
