### ISSUE TITLE
Updating dependency to js-beautify

### ISSUE THREAD

**Issue by Ericlm** [vuejs/test-utils#2112]
The package `js-beautify` recently fixed a moderate vulnerability (see [this issue](https://github.com/beautify-web/js-beautify/issues/2160)). 
It would be great if this package could upgrade the dependency, or allow patch versions or js-beautify inside `package.json`. 
Thank you!

**Comment by cexbrayat** [comment]
Sadly we can't, see https://github.com/vuejs/test-utils/pull/1834
