### ISSUE TITLE
Bug: PascalCase components are being rendered as kebab-case when using shallowMount in Vue 3 / VTU 2.4.0

### ISSUE THREAD

**Issue by bconnes** [vuejs/test-utils#2126]
**Describe the bug**
When using `shallowMount` to mount a component that uses components with PascalCase naming (e.g. `HelloWorld.vue`, the template is being rendered with the components in kebab-case instead of keeping their original name, making them difficult to find via `wrapper.find()`.

**To Reproduce**
I reproduced this issue using the default Vue 3 project created via vue-cli.

Vue 3 project with failing test: https://github.com/bconnes/vue3-find-stub-component

Vue 2 project with identical yet passing test: https://github.com/bconnes/vue2-find-stub-component

1. Create a new Vue 3 project using Vue Test Utils (version 2.4.0 in the above Vue 3 project)
2. Wrap a component that has child components that are named with `PascalCase` casing (e.g. `HelloWorld.vue`)
3. Attempt to find the child component using `wrapper.find()` (e.g. `wrapper.find('helloworld-stub');`
4. The stubbed out component is in the wrapper's HTML as `hello-world-stub`, not `helloworld-stub`. Attempting to run the same test that worked in Vue 2 produces the following error:

```
Uncaught Error Error: Cannot call html on an empty DOMWrapper.
```

```vue
> wrapper.html()
'<img alt="Vue logo" src="">
<hello-world-stub msg="Welcome to Your Vue.js App"></hello-world-stub>'
```

**Expected behavior**

The stubbed out component should be found in the wrapper's HTML with the element `helloworld-stub`;

```vue
> wrapper.html()
'<div id="app"><img alt="Vue logo" src="./assets/logo.png">
  <helloworld-stub msg="Welcome to Your Vue.js App"></helloworld-stub>
</div>'
```

**Related information:**

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 3.70 GB / 31.84 GB
  npmPackages:
    @vue/test-utils: ^2.0.0-0 => 2.4.0
    jest: ^27.0.5 => 27.5.1
    vue: ^3.2.13 => 3.3.4
```

**Additional context**
Please provide a mechanism to preserve the naming convention for stubbed out components to support projects upgrading from Vue 2 to Vue 3.

**Comment by freakzlike** [comment]
Hi @bconnes,

VTU has a possibility to customize the generation of each stub with [`config.plugins.createStubs`](https://test-utils.vuejs.org/guide/extending-vtu/plugins.html#stubs-plugin). You can implement your own stub logic inside this function. I've created a small repro and was able to achive your requirements

```typescript
it('renders properly', () => {
  config.plugins.createStubs = undefined;

  const wrapper = shallowMount(App);
  expect(wrapper.find('hello-world-stub').exists()).toBe(true);
  expect(wrapper.find('helloworld-stub').exists()).toBe(false);
});

it('renders without dash', () => {
  config.plugins.createStubs = ({ name, component }) => {
    return defineComponent({
      render: () => h(`${name}-stub`)
    });
  };

  const wrapper = shallowMount(App);
  expect(wrapper.find('helloworld-stub').exists()).toBe(true);
  expect(wrapper.find('hello-world-stub').exists()).toBe(false);
});
```

https://stackblitz.com/edit/github-d4p9ge?file=src%2F__tests__%2FApp.spec.ts&view=editor

**Comment by G-Rath** [comment]
@freakzlike it looks like this was a breaking change that didn't get documented - are you ok if I submit a pull request adding it to the [list of changes in the migration guide](https://test-utils.vuejs.org/migration/#Changes)?
