### ISSUE TITLE
Feature request: Rewrite some of the functionality of VueWrapper and align the vue API.

### ISSUE THREAD

**Issue by jason-chang** [vuejs/test-utils#2136]
**Is your feature request related to a problem? Please describe.**

In the process of fixing #2116, I've come to realize that VueWrapper.vm's position is to enable testers to debug and modify setupState. If that's correct, then it's probably not a good idea to require VueWrapper.vm to exercise the ExposeProxy function.

**Describe the solution you'd like**

In reading the vue/core sources, I found that Evan You implements ref reflection by assigning an ExposeProxy to the ref if the component has exposed properties, and a ComponentPublicInstance to the ref otherwise. code:[@vue/core/rendererTemplateRef](https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/packages/runtime-core/src/rendererTemplateRef.ts#L49)

Maybe we need to add a new property such as: exposed / exposeProxy. to easily access the exposed properties of the component.
An implementation of exposeProxy can be aligned to [@vue/core/component](https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/packages/runtime-core/src/component.ts#L1036).

If it's okay with you guys, maybe I'll try to do it.

**Comment by lmiller1990** [comment]
I wouldn't say we've got a specific position. The general development lifecycle for this library is just to assess and add things on a case by case basis, depending on what people want.

What I've seen historically is something like

1. User asks for feature to do X
2. Other users suggest alternative ways to do X
3. If the proposed solution is adequate, go with that
4. If it's not, discuss new / alternative / changes

In general, I think we want to avoid adding new features unless they solve a unique use case. If you think you have a use case for something like a `exposeProxy`, it might  be worth sharing it before writing too much code.

In my opinion tampering with the component isn't good, it's better to just interact like a user does (click, etc) but happy to discuss more!

**Comment by cexbrayat** [comment]
@jason-chang We can already access everything that is exposed (and not exposed) by the component on the VM, so I don't think we need to add another property. 

If you have a specific use case that can't be done currently, feel free to ping us with a repro and we'll gladly reopen and discuss!
