### ISSUE TITLE
Feature request: Add a note to migration guide where enableAutoDestroy is gone

### ISSUE THREAD

**Issue by daniilgri** [vuejs/test-utils#2147]
Could not find `enableAutoDestroy` feature in the VTU2 and also there is no note on the migration guide about that. 
I guess it is renamed to `enableAutoUnmount`?

**Comment by cexbrayat** [comment]
@daniilgri Yes, it is https://test-utils.vuejs.org/api/#enableautounmount

Could you open a PR to add a note to the migration guide? It would be a great help.

**Comment by cexbrayat** [comment]
@strokirk Feel free to open a PR, we would really appreciate it 👍
