### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'row')

### ISSUE THREAD

**Issue by black927** [vuejs/test-utils#2156]
访问scope里面的row属性报类型错误，为什么？怎么解决呢？类似这种类型错误还有很多：
![image](https://github.com/vuejs/test-utils/assets/48709663/e6a4662e-df7f-46ef-9124-7faf2f6d92dc)

**Comment by cexbrayat** [comment]
Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by cexbrayat** [comment]
We did not hear back from the OP, so I'm going to close the issue.

@black927 feel free to ping me with a repro and we'll reopen it if necessary!
