### ISSUE TITLE
Bug: Asynchronous data in options api leaks or is inconsistent between tests

### ISSUE THREAD

**Issue by akatakritos** [vuejs/test-utils#2179]
**Describe the bug**

I'm using the Vue 3 options API with vitest

We have a property returned by the `data()` callback that starts out as `undefined`. On mount, we kick of an API call to load the data and then store it into the property. 

```js
import { defineComponent } from 'vue';

function fakeApiCall() {
  return new Promise((resolve) =>
    setTimeout(() =>
      resolve({
        name: 'Fred',
      })
    )
  );
}
export default defineComponent({
  data() {
    return {
      model: undefined,
    };
  },
  async mounted() {
    this.model = await fakeApiCall();
  },
  methods: {
    updateName() {
      this.model.name = 'BamBam';
    },
  },
});
```

Thus in my first test I `mount` the component and then call `flushPromises()` to wait for that API call to finish before asserting facts about the text on screen. 

```ts
  it('loads and shows Fred', async () => {
    const wrapper = mount(UpdateExample);
    await flushPromises();

    expect(wrapper.vm.model.name).toBe('Fred');
    expect(wrapper.text()).toContain('name: Fred');
  });
```
This test passes consistently.

I want to change the state of the component after loaded and check that vue updates the UI, so I wrote three more tests trying to mutate the state in various ways. 

### deep mutation from outside the component: `wrapper.vm.model.name = 'Barney'`
```ts
it('loads Frank but can switch to Barney via deep mutation', async () => {
    const wrapper = mount(UpdateExample);
    await flushPromises();

    wrapper.vm.model.name = 'Barney';
    await nextTick();

    expect(wrapper.vm.model.name).toBe('Barney');
    expect(wrapper.text()).toContain('name: Barney');
  });
```

This one often fails with `wrapper.vm.model` being undefined

### full model replacement from outside the component: `wrapper.vm.model = { name: 'Barney' }`

```ts
it('loads Frank but can switch to Barney via full assignment', async () => {
    const wrapper = mount(UpdateExample);
    await flushPromises();

    wrapper.vm.model = { name: 'Barney' };
    await nextTick();

    expect(wrapper.vm.model.name).toBe('Barney');
    expect(wrapper.text()).toContain('name: Barney');
  });
```

this usually passes

### deep mutation from a method inside the component: `wrapper.vm.updateName()`

```ts
it('loads Frank but can switch to BamBam via a method on the component', async () => {
    const wrapper = mount(UpdateExample);
    await flushPromises();

    wrapper.vm.updateName();
    await nextTick();

    expect(wrapper.vm.model.name).toBe('BamBam');
    expect(wrapper.text()).toContain('name: BamBam');
  });
```
This test is hit or miss

You can mark the first test as `it.skip` and the later three tests will start passing more frequently.

Further more, I can press `a` in the terminal to run all tests, and different combinations of them pass on different runs. 

There seems to be some bleed-through between tests causing state to be inconsistent. 

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-867xyb?file=test%2Fupdate-example.test.ts

**Expected behavior**
Each test passes consistently

**Related information:**
```
❯ npx envinfo --system --npmPackages vue,@vue/test-utils,vitest,jest
Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  npmPackages:
    @vue/test-utils: 2.4.1 => 2.4.1 
    vitest: latest => 0.33.0 
    vue: latest => 3.3.4 
```

**Additional context**
In my real project I see a slightly different symptom: I don't crash on accessing `undefined` but vue is not detecting updates. That led me to making a stackblitz to narrow down.

Could this be an issue with vitest?

**Comment by freakzlike** [comment]
Hi @akatakritos,
when using `setTimeout` or `setInterval` in a unit test you should mock the timers https://vitest.dev/guide/mocking.html#timers.
I was able to make your tests work by adding `vi.useFakeTimers()` before all and `vi.runOnlyPendingTimers()` within every test.
Here is the repro with my fix: https://stackblitz.com/edit/vitest-dev-vitest-dszwz8?file=test%2Fupdate-example.test.ts
