### ISSUE TITLE
Bug: VTU not recognizing props object passed to the mount() function

### ISSUE THREAD

**Issue by Achraffawzi** [vuejs/test-utils#2199]
When mounting a component with props object, VTU does not read props from the options object passed to the mount() function and therefore the test always fails.

**Comment by cexbrayat** [comment]
Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by lmiller1990** [comment]
Closing until reproduction is provided.
