### ISSUE TITLE
Bug: Cannot find module '@vue/server-renderer'

### ISSUE THREAD

**Issue by chrisjbrown** [vuejs/test-utils#2218]
**Describe the bug**
I'm using these dependencies for testing
`
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/vue": "^6.6.1",
    "@vue/test-utils": "^2.2.6",
    "@vue/vue3-jest": "^29.2.2",
    "jest": "^29.3.1",
    "jest-environment-jsdom": "^29.3.1",
`

When running `yarn test` I'm receiving this error

`
Test suite failed to run

    Cannot find module '@vue/server-renderer' from '/project_path/.yarn/__virtual__/@vue-test-utils-virtual-7528046424/0/cache/@vue-test-utils-npm-2.4.1-9433e5afe3-901b6a5170.zip/node_modules/@vue/test-utils/dist'

    Require stack:
      /project_path/.yarn/__virtual__/@vue-test-utils-virtual-7528046424/0/cache/@vue-test-utils-npm-2.4.1-9433e5afe3-901b6a5170.zip/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js
      /project_path/.yarn/__virtual__/@testing-library-vue-virtual-9373cb4b8b/0/cache/@testing-library-vue-npm-6.6.0-6f4ee0052f-3e89e05ca1.zip/node_modules/@testing-library/vue/dist/render.js
      /project_path/.yarn/__virtual__/@testing-library-vue-virtual-9373cb4b8b/0/cache/@testing-library-vue-npm-6.6.0-6f4ee0052f-3e89e05ca1.zip/node_modules/@testing-library/vue/dist/index.js
      jest.setup.js

      4 | import "@testing-library/jest-dom";
      5 |
    > 6 | import { configure } from "@testing-library/vue";
        | ^
      7 | import { config } from "@vue/test-utils";
      8 | import { lazyLoadImages } from "src/js/helpers/lazyLoadImages";
`

**To Reproduce**
working on creating minimum stack blitz repo

**Expected behavior**
I'm not doing any server side rendering or testing. I would not expect '@vue/server-renderer' to be referenced at all

**Comment by davidmatter** [comment]
Have you installed the following packages?

```
   "@vue/compiler-sfc": ">= 3",
   "vue": ">= 3"
```

**Comment by chrisjbrown** [comment]
> Have you installed the following packages?
> 
> ```
>    "@vue/compiler-sfc": ">= 3",
>    "vue": ">= 3"
> ```

yes
`
    "vue": "^3.2.45",
    "@vue/compiler-sfc": "^3.2.39"
`

**Comment by cexbrayat** [comment]
Which version of Yarn do you use?

I think it's probably the same issue than https://github.com/vuejs/test-utils/issues/2107
We have a PR in progress to solve this, see https://github.com/vuejs/test-utils/pull/2197

In the meantime you can add `@vue/server-renderer` to your dev dependencies

**Comment by chrisjbrown** [comment]
> Which version of Yarn do you use?
3.5.0

**Comment by chrisjbrown** [comment]
> In the meantime you can add @vue/server-renderer to your dev dependencies

oddly tests still fail with the same error
