### ISSUE TITLE
Bug: `Wrapper.setValue(str)` not working

### ISSUE THREAD

**Issue by msm-tomlonghurst** [vuejs/test-utils#2236]
**Describe the bug**
The `setValue` method isn't updating the value on my input.

This code:
```typescript
    const elem = wrapper.find<HTMLInputElement>(selector);

    const oldValue = elem.element.value;
    console.log(oldValue);

    await elem.setValue(value);

    const newValue = wrapper.find<HTMLInputElement>(selector).element.value;
    console.log(newValue);

    wrapper.find<HTMLInputElement>(selector).element.value = value;

    const newValue2 = wrapper.find<HTMLInputElement>(selector).element.value;
    console.log(newValue2);
```

Produces this output if I use the debug console:
![image](https://github.com/vuejs/test-utils/assets/130671542/17101fb1-e680-47ae-827f-4ef426fc954a)

As you can see, if I try to access the element manually and set the value, it sets the value. But if I use the `Wrapper.setValue` method, then nothing happens.

**Expected behavior**
The value is updated.

**Related information:**
>   System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.23 GB / 31.85 GB
  npmPackages:
    @vue/compat: ^3.1.0 => 3.3.8
    @vue/test-utils: ^2.0.0 => 2.4.1
    jest: ^29.0.0 => 29.7.0
    vue: ^3.1.0 => 3.3.8

**Comment by cexbrayat** [comment]
Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by msm-tomlonghurst** [comment]
Actually seems to be an issue our side. We upgraded Vue 2 to 3 at the same time. Looks like we were two-way binding a prop, which is only one-way binding and it breaks things in Vue 3 but not 2 apparently. Will close this.
