### ISSUE TITLE
Bug: `setData()` incorrectly sets object prototype methods as keys

### ISSUE THREAD

**Issue by MetRonnie** [vuejs/test-utils#2257]
**Describe the bug**

Using `setData()` with an object is causing Object prototype methods to be set as keys on the object.

**To Reproduce**

Stackblitz isn't loading for me. But here is hopefully a clear example:

```js
const wrapper = mountFunction()
expect(wrapper.vm.filters).toEqual({
  'workflow state': [],
  'task state': [],
}) // ✔
expect(Object.keys(wrapper.vm.filters)).toEqual([
  'workflow state',
  'task state',
]) // ✔

await wrapper.setData({
  filters: {
    'workflow state': [],
    'task state': [],
  }
})
expect(Object.keys(wrapper.vm.filters)).toEqual([
  'workflow state',
  'task state',
]) // ✖
```

```diff
- Expected
+ Received

  Array [
    "workflow state",
    "task state",
+   "constructor",
+   "__defineGetter__",
+   "__defineSetter__",
+   "hasOwnProperty",
+   "__lookupGetter__",
+   "__lookupSetter__",
+   "isPrototypeOf",
+   "propertyIsEnumerable",
+   "toString",
+   "valueOf",
+   "toLocaleString",
```

**Expected behavior**

Object prototype methods should not be set as keys on objects.

**Related information:**

```
    "vue": "3.3.4",
    "@vue/test-utils": "2.4.2",
    "vitest": "0.34.6"
```

**Additional context**

I think this was introduced by #2166

**Comment by cexbrayat** [comment]
Hi @MetRonnie 

Interesting. You're probably right that this is a regression from #2166

Would you like to open a PR to fix this? We would gladly review and merge it.

**Comment by MetRonnie** [comment]
I'm afraid I don't have a lot of time on my hands

**Comment by cexbrayat** [comment]
No worries, maybe someone will pick it up.

**Comment by Haberkamp** [comment]
I'll create a PR for that issue during next days.
