### ISSUE TITLE
Bug: input setValue trigger no more works after upgrade from 2.3.2 to 2.4.3... 

### ISSUE THREAD

**Issue by sosog** [vuejs/test-utils#2283]
I have test where use setValue in vitest (Vue app), it was always worked, but after upgrade version from 2.3.2 to 2.4.3...  **setValue** no more triggers input change, so Vue component can't process  instance update of input ref. https://github.com/vuejs/test-utils/pull/2019

**Comment by cexbrayat** [comment]
Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by cexbrayat** [comment]
@sosog Didi you manage to make a reproduction or did you solve your issue?

**Comment by cexbrayat** [comment]
We had no answer from the OP so I'm going to close this.

If someone encounters the same issue, feel free to ping me with a repro and I'll re-open it.
