### ISSUE TITLE
Bug:  ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by Suryadeep-bhujel** [vuejs/test-utils#2287]
**Bug Detail**
 I am writting test cases using vue3 version `^3.3.4` but  its throwing error on run test
**ReferenceError: Vue is not defined** in` Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.browser.js:8418:8)`
`import { shallowMount } from "@vue/test-utils";`

case code 
` const wrapper = shallowMount(Mycomponent);`
 
 

 

**Related information:**
vue: 3.3.4, 
vue/utils : 2.4.3
vue/vue3-jest

**Comment by cexbrayat** [comment]
Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by Suryadeep-bhujel** [comment]
I resolved the problem, thank you for your immediate response.

**Comment by shubhangchourasia** [comment]
@Suryadeep-bhujel Can you please specify how you solved this issue ?

**Comment by fullMooth** [comment]
> I resolved the problem, thank you for your immediate response.

Can you please specify how you solved this issue? thank you
