### ISSUE TITLE
Does it work with "Vue 2.7.16"？

### ISSUE THREAD

**Issue by baboon-king** [vuejs/test-utils#2289]
hi！
I doing this https://github.com/vuejs/create-vue/issues/408

Does it work with "Vue 2.7.16".

However, I tested some and he works fine.

**Comment by baboon-king** [comment]
if it worked with Does it work with "Vue 2.7.16".
then add to vue@2.7.16 in peerDependencies

![image](https://github.com/vuejs/test-utils/assets/63645337/b4adb376-6f5f-48dd-9151-6c53e84e0cac)

**Comment by cexbrayat** [comment]
No it doesn't work with Vue 2, this is the repository for Vue 3 (check the readme for more info)
