### ISSUE TITLE
Bug: References to objects are lost when emitting events from child component

### ISSUE THREAD

**Issue by ElVisPL** [vuejs/test-utils#2301]
**Describe the bug**

If component code relies on comparing references to objects that come from emited events then those references are not persisted in unit tests
(It worked in vue test utils v1)

```
<HelloWorld @test="test" />
...
methods: {
    test(obj) {
      if (!this.obj) {
        this.obj = obj;
      } else {
        console.log(this.obj === obj); //returns false even if in test I emit  the same object
      }
    },
  },
  ```
  Test:

  ```
  const sharedObj = { id: 1 };
    wrapper.findComponent('hello-world-stub').vm.$emit('test', sharedObj);
    wrapper.findComponent('hello-world-stub').vm.$emit('test', sharedObj);
  ```

**To Reproduce**

https://stackblitz.com/edit/github-d2za9l?file=src%2Fcomponents%2F__tests__%2FApp.spec.ts

`yarn test:unit App.spec`

**Expected behavior**

It shouldn't break references

**Comment by cexbrayat** [comment]
Hi @ElVisPL 

Thanks for the repro. i'm wondering something though: ain't that the same in a real app?

I changed the repro in Stackblitz, to actually emit the same object from HelloWorld https://stackblitz.com/edit/github-d2za9l-v9nivo?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue
Take a look in the console, it is false as well.

So I think the test has an accurate behavior?

**Comment by cexbrayat** [comment]
@ElVisPL As the runtilme behavior seems to be the same as the one in the test, I'm going to close this issue.
If you have other informations, feel free to ping with a repro and I'll re-open and take a look.
