### ISSUE TITLE
Return type confusing, generics not working

### ISSUE THREAD

**Issue by philly-vanilly** [vuejs/test-utils#2314]
const wrapper: ReturnType<typeof mount<SomeComponent>> = mount(SomeComponent);

This is giving me the error _ComponentPublicInstance<{}, Omit<{   value: string; }, never>> **is not assignable to type**
ComponentPublicInstance<NonNullable<Partial<{}> & Omit<{} & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<ExtractPropTypes<{}>>, never>>, { ...; } & ... 6 more ... & Omit<...>>_

What am I doing wrong? The type can of course be resolved automatically, but only if you directly assing it to. constant. if you want to have a wrapper defined but not immediately assigned (which happens later in beforeEach), this leads to type errors.

I guess the best practices are to not create the wrapper in beforeEach but in each test (?), but I have over 300 test-suites in a project I did not set up myself and I need to improve the type-safety without refactoring them all. I do not want ot use "any" for this.

**Comment by cexbrayat** [comment]
Hi @philly-vanilly 

Yes this is something we hope to improve. There is a WIP PR that you can track : see #2242 Some things need to change in Vue itself as well.

I usually don't use a shared wrapper between my tests. I create it in each test, and let TS infer the return type.

```ts
function navbarWrapper() {
  return mount(Navbar, {
    // options
  });
}

describe('Navbar.vue', () => {
  test('something', () => {
    const wrapper = navbarWrapper();
  })
});
```

**Comment by philly-vanilly** [comment]
@cexbrayat Ok thank you, I figured this is the best way, good to hear it from a pro too. I will keep track of the issue
