### ISSUE TITLE
Bug: Submit event from form does not get caught in unit test

### ISSUE THREAD

**Issue by BeatsuDev** [vuejs/test-utils#2318]
**Describe the bug**
Submit events captured by form elements do not run their handles in unit tests.

**To Reproduce**
https://stackblitz.com/edit/github-6e7sez?file=src%2Fcomponents%2FHelloWorld.vue
```
npm create vue@latest
```
Add this to `HelloWorld.spec.ts`:
```ts
  it('emits submit event', () => {
    const wrapper = mount(HelloWorld)
    wrapper.find('button').trigger('click')

    expect(wrapper.emitted()).toHaveProperty("submit");  // THIS FAILS
  });
```
This to `HelloWorld.vue`:
```ts
import { ref } from 'vue';

const text = ref('');

const emit = defineEmits<{
  submit: [formData: string];
}>();

function handleSubmit() {
  emit('submit', text.value);
}
```
```html
    <form @submit.prevent="handleSubmit">
      <input v-model="text" type="text" />
      <button type="submit">Submit</button>
    </form>
```

`App.vue`:
```html
      <HelloWorld @submit="text => console.log('Submitted:', text)" msg="You did it!" />
```
Finally run:
```
npx vitest
```

**Expected behavior**

Submit event is supposed to be fired and `wrapper.emitted()` should have the `submit` property. 

**Related information:**
Here is the same issue for vue 2: https://github.com/vuejs/vue-test-utils/issues/2018

**Comment by cexbrayat** [comment]
Hi @BeatsuDev 

Thanks for the repro.

The easiest way to make your test succeed is to attach the element to the DOM:

```ts
    const wrapper = mount(HelloWorld, {
      attachTo: document.body
    })
```

Or you can trigger the `submit` event instead of `click`:

```ts
wrapper.find('form').trigger('submit')
```

And then it should work.

**Comment by cexbrayat** [comment]
See https://test-utils.vuejs.org/guide/essentials/forms.html#Native-form-submission
