### ISSUE TITLE
Bug: Errors during $setup are hidden and cause the template to be rendered with undefined properties

### ISSUE THREAD

**Issue by voidus** [vuejs/test-utils#2319]
**Describe the bug**

When an error is thrown in the setup, it is silently ignored and the template is rendered with all variables set to undefined.

I cannot confidently exclude that this is a misconfiguration, so if there's anything I should check please let me know. Either way, this is very confusing and cost me quite some time, so if we can prevent this from happening that would be great.

**To Reproduce**

```vue
<template>
  <p>{{ x.y }}</p>
</template>

<script setup lang="ts">
const x = { y: 42 };
const props = defineProps<{ shouldFail: boolean }>();
if (props.shouldFail) throw new Error('rip');
</script>
```

```typescript
import { mount } from '@vue/test-utils'
import TestComponent from './TestComponent.vue'
import { expect, it } from 'vitest'

it('works usually (this one works)', async () => {
  const wrapper = mount(TestComponent, {
    props: { shouldFail: false }
  })
  expect(wrapper.text()).toContain('42')
})
it('shows the error (this one does not)', async () => {
  const wrapper = mount(TestComponent, {
    props: { shouldFail: true }
  })
  expect(wrapper.text()).toContain('42')
})
```

**Expected behavior**

The error should be presented to the developer

**Actual output**

```
yarn workspace v1.22.19
yarn run v1.22.19
$ vitest TestComponent
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

 DEV  v0.34.6 /home/voyd/Coding/cannahaus/casoma/frontend

 ❯ src/pages/TestComponent.vitest.test.ts (2)
   ✓ works usually (this one works)
   × shows the error (this one does not)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/pages/TestComponent.vitest.test.ts > shows the error (this one does not)
TypeError: Cannot read properties of undefined (reading 'y')
 ❯ Proxy._sfc_render src/pages/TestComponent.vue:2:11
      1| <template>
      2|   <p>{{ x.y }}</p>
       |           ^
      3| </template>
      4| 
 ❯ renderComponentRoot ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:830:16
 ❯ ReactiveEffect.componentUpdateFn [as fn] ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5745:46
 ❯ ReactiveEffect.run ../node_modules/@vue/reactivity/dist/reactivity.cjs.js:182:19
 ❯ instance.update ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5858:51
 ❯ setupRenderEffect ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5866:5
 ❯ mountComponent ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5656:5
 ❯ processComponent ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5609:9
 ❯ patch ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5095:11
 ❯ ReactiveEffect.componentUpdateFn [as fn] ../node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5752:11

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed | 1 passed (2)
   Start at  21:44:53
   Duration  425ms (transform 60ms, setup 0ms, collect 96ms, tests 18ms, environment 100ms, prepare 61ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

**Related information:**

envinfo is doing weird things, here's my versions though

- vue: 3.3.12
- @vue/test-utils: 2.4.3
- vitest: 0.34.6
- jest: 29.7.0

This is in a recently set up quasar 2.14.1 project.

**Additional context**

**Comment by lmiller1990** [comment]
I am getting the expected error when using both `setup` and `<script setup>`

## `setup()`
![image](https://github.com/vuejs/test-utils/assets/19196536/dd1cb0e6-031b-43f0-834e-171083340f5d)

## `<script setup>`

![image](https://github.com/vuejs/test-utils/assets/19196536/22c78753-7564-4da6-ad4d-1aa67960e694)

**Comment by lmiller1990** [comment]
I reproduced with your example

![image](https://github.com/vuejs/test-utils/assets/19196536/961a71f6-1d20-45d7-ae60-ffbf82d2ea9b)

**Comment by lmiller1990** [comment]
Related? https://github.com/vuejs/core/issues/7020

**Comment by lmiller1990** [comment]
It looks like this can be 'fixed' by removing https://github.com/vuejs/test-utils/blob/bd21a8ea895351f97849bed02c4791577a3dd55e/src/mount.ts#L77-L82

Not sure if we still need this or not... I forgot what this does.

**Comment by voidus** [comment]
Thank you so much for your swift response. I'll try to find some time to look into it, but if anyone else is curious don't let that stop you.

**Comment by lmiller1990** [comment]
Don't everyone submit a PR at once!

**Comment by voidus** [comment]
I can confirm that removing that block fixes the problem, but I don't know vue enough to understand https://github.com/vuejs/core/issues/7020 so I'm not sure if it's a good idea?
