### ISSUE TITLE
Vue Warn, Error Handlers

### ISSUE THREAD

**Issue by rodhoward** [vuejs/test-utils#2326]
Hi,
We are trying to migrate from vue2 to vue3 and have been using the bootstrap-vue library. I'm trying to find ways to suppress error messages from there while continuing to display error/warning messages from our own code.

It seems like vue warning handler could be what I'm looking for:
https://vuejs.org/api/application.html#app-config-warnhandler

I can't see how/if this is exposed when unit testing using test-utils though. Hoping this could be added to config so that we could globablly define a handler that filtered out some warnings. Something like this:

jest.setup.js:
```js
import { config } from "@vue/test-utils";

config.global.warnHandler = (msg, instance, trace) => {
  if (msg.includes("Vue warn") {
      if (trace.includes(.. "bootstrap-vue" .. ) return;
  }
  console.warn(msg);
}
```

Not confident that trace will actually be a string also not sure how to spit out the normal warning message with correct trace etc once you capture it in this handler.. Couldn't see examples.  In any case that's out side the scope. If this is simply exposed as is from vue into vue/test-utils that would be great.

Cheers
Rod

**Comment by cexbrayat** [comment]
Hi @rodhoward 

As it is a niche use case, I'm not sure it's worth adding this to VTU (we're trying to keep the API as simple as possible).

When I want to do something like this, I usually spy on `console.warn` in my test.

```ts
const warn = vi.spyOn(console, 'warn')
// test...
const warnings = warn.mock.calls.filter(/* remove bootstrap-vue warning */)
expect(warnings).toEqual([]);
```

Would that be enough for you use-case?

**Comment by rodhoward** [comment]
Hi,

Thanks for you're fast response! I'd push back a little in that exposing features of the underlying vue application seems like almost a simplification in that you don't need to explain why they aren't available. Further I don't think its so niche as test warnings have been an issue for a while. This is not specific to the vue-bootstrap library but any library that is trying to migrate from vue2, basically anyone with a large codebase ;). 

Regarding your spy yes thats a good work around however it doesn't expose the trace which would allow me hopefully to filter based on an external package. It also then effectivly hides traces for errors that I would like exposed. Basically its a bit heavy handed. 

Regards
Rod

**Comment by cexbrayat** [comment]
I understand, that's why I kept the issue open: if there is a lot of interest in this, we may consider adding it to VTU.

But IIRC, what Vue does is that it logs the msg and the trace (formatted) with `console.warn` if there is no `warnHandler`, so you should be able to do the same

**Comment by rodhoward** [comment]
You're right this is basically working as required:

```javascript
const warn = jest.spyOn(console, "warn").mockImplementation(msg => {
  const err = new Error("trace");
  const { stack } = err;
  if (stack.includes("/node_modules/bootstrap-vue")) {
    console.info("bootstrap-vue warning");
  } else {
    console.info(msg, stack);
  }
});
```
Creating the extra error wouldn't be required if we where getting the original vue errors but this is probably fine for us.

**Comment by cexbrayat** [comment]
Thanks for the feedback @rodhoward 
I'll close this issue for now then.
