### ISSUE TITLE
Bug: type inference for components is not on par with `defineComponent`

### ISSUE THREAD

**Issue by danielroe** [vuejs/test-utils#2332]
**Describe the bug**

This is likely a duplicate of https://github.com/vuejs/test-utils/issues/972 but I'm not 100% sure so thought I would raise separately. Please feel free to close if it doesn't add anything separately.

**To Reproduce**

https://stackblitz.com/edit/stackblitz-starters-qp1pxh

**Expected behavior**

I expect the `$data` type to be inferred based on the provided object. If wrapped in `defineComponent` this issue is worked around.

related downstream issue: https://github.com/formkit/formkit/pull/1194

**Comment by cexbrayat** [comment]
Hi @danielroe 

I don't think we can do much about this, the type inference is already quite complex as it is, so I would recommend using `defineComponent`. I see the downstream issue has been fixed, so I'll close this one 👍
