### ISSUE TITLE
Bug: execute imports code in a component's children despite being stubbed

### ISSUE THREAD

**Issue by oleksandrnechaiev** [vuejs/test-utils#2334]
**Describe the bug**

A component's children, stubbed and containing imports where code operates in the global scope, execute that code within the imports despite being stubbed, while the code within the children's components remains unexecuted.

**To Reproduce**

```vue
// AComponent.vue
<script setup lang="ts">
    import BComponent from './BComponent.vue';
</script>

<template>
    <div>
        AComponent 
        <BComponent />
    </div>
</template>
```
```vue
// BComponent.vue
<script setup lang="ts">
    import { getSomething } from './someImport.ts';
    function startFetch() {
        getSomething({ someParam: 'sds' });
    }
    // This is not executed
    console.log('run in BComponent');
</script>

<template>
    <div>
        BComponent
        <button @click="startFetch">Click me</button>
    </div>
</template>
```
```ts
// someImport.ts

// This is executed
const { config1, config2 } = JSON.parse(import.meta.env.PUBLIC_CONFIG);

// This is executed
console.log({ config1, config2 }, 'in the someImport.ts');

export const getSomething = (params) => {
    return apiClient.get('/somepath', { params });
};
```
```ts
// AComponent.test.ts
import { describe, it, expect } from 'vitest';
import { mount, shallowMount } from '@vue/test-utils';
import AComponent from './AComponent.vue';

describe('AComponent', () => {
    it('should render', () => {
        // const aComponent = shallowMount(AComponent)
        const aComponent = mount(AComponent, {
            shallow: true,
            // global: {
            //     stubs: {
            //         BComponent: true,
            //     },
            // },
        });
        console.log(aComponent.html());
        expect(true).toBe(true);
    });
});
```
This is the result of the test run

<img width="1026" alt="image" src="https://github.com/vuejs/test-utils/assets/23580068/86cc45a2-3701-4c37-8488-74606d23c726">

Here's the [repository](https://github.com/oleksandrnechaiev/vue-test-utils-issue-example-repo) with a code example. In README.md the info on how to run.

**Expected behavior**

The code within the imports remains dormant; in other words, the contents of the imported file are not executed.
```ts
// This is executed
const { config1, config2 } = JSON.parse(import.meta.env.PUBLIC_CONFIG);

// This is executed
console.log({ config1, config2 }, 'in the someImport.ts');
```

**Additional context**

Is it expected behavior or we can change(fix) it?

**Comment by cexbrayat** [comment]
Hi @oleksandrnechaiev 

Yes this is expected, because VTU does not change the imports, it simply overrides the component.
If you're using vitest, you can probably mock the module if you want to replace the imported code by something else.
See https://vitest.dev/api/vi.html#mock-modules

**Comment by oleksandrnechaiev** [comment]
Thank @cexbrayat  for the confirmation.
