### ISSUE TITLE
Bug: wrapper.findComponent no longer working after upgrading to 2.4.2

### ISSUE THREAD

**Issue by SimonHawesome** [vuejs/test-utils#2343]
**Describe the bug**

Ever since we updated to v2.4.2, we've been experiencing an error with `wrapper.find` and `wrapper.findComponent`.

`Error: Cannot call vm on an empty VueWrapper.`

The find and findComponent methods no longer return a VueWrapper.

**To Reproduce**

```
// .vue file
<component data-attribute-handle @close="handleClose"></component>

// test file
wrapper.findComponent('[data-attribute-handle]').vm.$emit('close')
```

**Expected behavior**

We are expecting the component to be returned so we can call methods on the component's vm.

`wrapper.findComponent('[data-attribute-handle]').vm.$emit('close')`
or 
`wrapper.findComponent('[data-attribute-handle]').vm.selected`

**Related information:**

Vue test utils v2.4.2
Vue 3.2.37

**Additional context**

**Comment by cexbrayat** [comment]
Hi @SimonHawesome 

Have you tried with the latest version of Vue (v3.4.15) and VTU (v2.4.4) as well?

If it doesn't work, can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by cexbrayat** [comment]
Hi @SimonHawesome 

Did you manage to build a repro or did you fix your issue and we can close this?

**Comment by chrismooreajbell** [comment]
Hi are you using vitest? If so you may need to add
```
    server: {
      deps: {
        inline: ['@vue/test-utils'],
      },
    },
```
to your vitest config.

**Comment by cexbrayat** [comment]
Hi @SimonHawesome 

Let me know if you have a repro or if we can close the issue (we can't look into it otherwise). I suspect that using both the later versions of VTU and Vue should be enough to solve it, but I'll wait for your answer before closing.

**Comment by cexbrayat** [comment]
Let's close the issue as we had no repro from the OP author.

**Comment by SimonHawesome** [comment]
I was finally able to pick this back up today and I found what the problem was.

Seems like I was stubbing transitions in earlier versions and removing the stub fixed all the things.

I appreciate you following up on this issue, I have been quite busy with other things.

```
const transitionStub = () => ({
  render: function (h) {
    return this.$options._renderChildren
  },
})

wrapper = mount(Component, {
    global: {
      stubs: {
        // transition: transitionStub(),
      }
    },
})
```
