### ISSUE TITLE
Bug: can't pass a prop to a stubbed custom element using a `.prop` modifier

### ISSUE THREAD

**Issue by wassim-ben-amor** [vuejs/test-utils#2355]
**Describe the bug**
When I try to stub a custom element, I can not read its props when it's using a `.prop` modifier in the template as mentioned in the docs: https://vuejs.org/guide/extras/web-components.html#passing-dom-properties

**To Reproduce**
https://stackblitz.com/edit/github-pttnmy-snzfka?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

**Expected behavior**
Props are readable even with `.prop` modifier

**Comment by cexbrayat** [comment]
Hi @wassim-ben-amor 

I think this is expected: if you use `.prop` then you set the property as a DOM property, so it won't be accessible via `wrapper.prop()`. Instead you will find it on the DOM element:

```ts
  it('should read custom elemnt props with .prop modifier', () => {
    const customComponent = wrapper.findComponent(customComponentStub);
    // 👇 access the property on the DOM element directly
    expect(customComponent.element.positionWithPropModifier).toStrictEqual({
      '2': '2',
    });
  });
```
