### ISSUE TITLE
Feature request: mount should accept a partial that describes local properties on component

### ISSUE THREAD

**Issue by cory-baker** [vuejs/test-utils#2366]
**Is your feature request related to a problem? Please describe.**
I'd like my tests to be typesafe.

**Describe the solution you'd like**
The option to pass a partial to describe component data
`mount<Component<{...myComponentDataTypes}>>` 
or 
`mount<Component, {...myComponentDataTypes}>`

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/vuejs/test-utils/assets/29523975/939be6ff-1a2b-4c95-a7ee-48469e737f5a)

**Comment by cexbrayat** [comment]
Hi @cory-baker 

I think you are running into https://github.com/vuejs/test-utils/issues/972 which needs some changes in Vue itself to have proper types.

In the meantime, you need to manually cast `vm` as showed in the issue.

I'm going to close this one as a duplicate, feel free to ping me with a repro if this is not the case.
