### ISSUE TITLE
Bug: Circular references in props cause "Maximum call stack size exceeded" since v2.4.5

### ISSUE THREAD

**Issue by JeppeKnockaert** [vuejs/test-utils#2370]
**Describe the bug**
When a property contains a circular reference, vue-test-utils gets stuck in a loop, resulting in a "Maximum call stack size exceeded" error.

**To Reproduce**
Failing example (2.4.5): https://stackblitz.com/edit/github-mhdk9j-cpr5hr?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts&view=editor&startScript=test:unit
Working example (2.4.4): https://stackblitz.com/edit/github-mhdk9j-gdhwv2?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts&view=editor&startScript=test:unit

**Expected behavior**
The test should not crash on circular references, because Vue itself also doesn't crash on this.

**Related information:**
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh

  npmPackages:
    @vue/test-utils: ^2.4.4 => 2.4.5 
    vitest: ^1.3.1 => 1.3.1 
    vue: ^3.4.21 => 3.4.21 

**Additional information:**

Caused by the deep ref check in https://github.com/vuejs/test-utils/pull/2356/files

**Comment by cexbrayat** [comment]
Hi @JeppeKnockaert 

Thanks for the repro.

`isDeepRef` has been introduced in https://github.com/vuejs/test-utils/pull/2356

@Evobaso-J would you mind taking a look to see if you can fix the regression?

**Comment by Evobaso-J** [comment]
Sure! I'll try ASAP

**Comment by Evobaso-J** [comment]
@cexbrayat the fixes are done, but I'd rather take some more time to add several unit tests to `isDeepRef`. 
However, since this looks urgent, I can mark the PR as ready and open a follow-up to add said tests

**Comment by cexbrayat** [comment]
@Evobaso-J We're not in a rush, take your time to add tests and ping me when it's ready to review 👍 Thanks for taking a look!

**Comment by Evobaso-J** [comment]
@cexbrayat ready! ✌🏻

**Comment by murilobd** [comment]
I'm using [vue testing library](https://github.com/testing-library/vue-testing-library/tree/main) and I'm getting the error reported here (I tested with version 2.4.4 and it was working fine)

**Comment by liqueurdetoile** [comment]
@cexbrayat When can we expect this fix to be released ?
