### ISSUE TITLE
DOMWrapper giving different return than createWrapper.

### ISSUE THREAD

**Issue by steven-twerdochlib** [vuejs/test-utils#2387]
**Describe the bug**

I am currently upgrading my project from vue2 to vue3 including test-utils. I have a child class that uses `this.$parent.$emits('xxxxx');`
For Vue2 I had a test class that used `const parentWrapper = createWrapper(wrapper.vm.$parent);` and then `expect(parentWrapper.emitted('xxxxx')).toBeTruthy();` to check that emit was done correctly.
In the migration guide it says to use new DOMWrapper instead of createWrapper but after putting in console.log()'s I noticed the response was different to before and I get the error TypeError: parentWrapper.emitted is not a function.

**To Reproduce**

**Expected behavior**

Test should pass.

**Related information:**

**Additional context**

Note, I also changed to Vite and Vitest. Not sure if that affected it.

**Comment by cexbrayat** [comment]
Hi @steven-twerdochlib 

Can you provide us a small repro online of what you're trying to do using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by steven-twerdochlib** [comment]
Hi @cexbrayat,
Is something like this what you're expecting:
https://stackblitz.com/edit/github-pecnhz?file=src%2Fcomponents%2F__tests__%2FChildComponent.spec.ts

**Comment by cexbrayat** [comment]
Thanks for the repro (and thanks @renatodeleao for spotting the issues in it).

Yes, `emitted` only exists on `VueWrapper` not on `DOMWrapper`.
But I agree with @renatodeleao , your test would be much better using a wrapper component so I'll close this one 👍

**Comment by steven-twerdochlib** [comment]
> @steven-twerdochlib There's a couple of issue with your demo (some typos).
> 
> ```diff
> - let childButton = wrapper.find('.childButton');
> + let childButton = wrapper.find('#childButton');
> 
> - .emitted('tabClose')
> + .emitted('buttonClicked')
> ```
> 
> But if you allow me to suggest, would be easier — and arguably a more future proof spec, as it resembles a real app scenario — you could literally wrap you component in another to mock the scenario
> 
> ```js
> describe('ChildComponent.vue', () => {
>   it('Check tabClose parent event emitted on close button click', async () => {
>     const wrapper = mount({
>       components: { ChildComponent },
>       template: `
>         <div id="the-parent">
>           <ChildComponent />
>         </div>
>       `,
>     });
> 
>     let childButton = wrapper.find('#childButton');
> 
>     await childButton.trigger('click');
> 
>     expect(wrapper.emitted('buttonClicked')).toBeTruthy();
>   });
> });
> ```
> 
> Here's a fork of your demo with the tests passing https://stackblitz.com/edit/github-pecnhz-jsdmto?file=src%2Fcomponents%2F__tests__%2FChildComponent.spec.ts

@renatodeleao Thanks for the speedy response, quick question though: if the childComponent had a prop, how would I change this? Before I could use `wrapper.vm.propToChange = false;` but obviously now wrapper is the parent.

**Comment by renatodeleao** [comment]
> @renatodeleao Thanks for the speedy response, quick question though: if the childComponent had a prop, how would I change this? Before I could use wrapper.vm.propToChange = false; but obviously now wrapper is the parent.

@steven-twerdochlib, as always it depends™. But there's a few ways to do it, but I would say that generic aporoach would be to the "transparent wrapper™"  where you forward wrapper props to the child. Something along these lines:

```diff
 const wrapper = mount({
      components: { ChildComponent },
+      props: ChildComponent.props,
      template: `
        <div id="the-parent">
-          <ChildComponent />
+          <ChildComponent v-bind="$props" />
        </div>
      `,
    });
```

You can now use `setProps()` as if you were setting on the Child. But of course, **only if you need to**, ideally if you need to test props outcomes then you don't need to wrap the subject `ChildComponent` in a parent wrapper.
