### ISSUE TITLE
Docs: afterEach in teleport section causes issues on happy-dom

### ISSUE THREAD

**Issue by brc-dd** [vuejs/test-utils#2402]
Currently https://test-utils.vuejs.org/guide/advanced/teleport documents:

```ts
afterEach(() => {
  // clean up
  document.body.outerHTML = ''
})
```

This removes whole body and `document.body` becomes `null` when using `happy-dom` (in `jsdom` it remains fine), resulting in errors like these:

```
TypeError: Cannot set properties of null (setting 'outerHTML')
 ❯ tests/components/STooltip.spec.ts:12:17
     10| 
     11| afterEach(() => {
     12|   document.body.outerHTML = ''
       |                 ^
     13| })
     14| 
```

Will it be better to use `document.body.innerHTML = ''` instead? It works on both happy-dom and jsdom. (Though happy-dom's behavior seems non-standard.)

**Comment by cexbrayat** [comment]
happy-dom has indeed quite a few differences. If `innerHTML` works for both, feel free to open a PR to update the docs 👍
