### ISSUE TITLE
Bug: Event declared via $attrs in mount not establishing prop prefixed with `on`

### ISSUE THREAD

**Issue by chrismooreajbell** [vuejs/test-utils#2405]
According to this thread and example, the workaround for checking the presence of an event listener using `this.$listeners` in Vue 2 is to use a prop with the same name as the event being emitted, prefixed with on: https://github.com/vuejs/core/issues/5319#issuecomment-1020535738

I've created a repo to essentially clone this example and create a test against the functionality;

The repo is: https://github.com/chrismooreajbell/vtu-listeners/
The relevant test file is: https://github.com/chrismooreajbell/vtu-listeners/blob/main/src/Badge.spec.ts

This app code works in the browser, as you can test by running npm run dev in the repo - the `delete` button is conditionally rendered and when an event listener called `delete` is present on the child component.

To my mind, the way to test the rendering of the conditional content would be to set the relevant listener in the $attrs during mount. However this doesn't work; the onDelete prop is undefined. This is shown in the first test.

A way that does work is to assign the prop, but this doesn't reflect real-world usage. This is shown in the second test.

I believe the test should work when the event is declared in attrs; please could you look in to this?

**Comment by cexbrayat** [comment]
Hi @chrismooreajbell 
I'm not sure I understand your example: `<Badge @delete="..." />` uses an event listener (or an onDelete props), but not an attribute. `<Badge delete` would be an attribute. As your badge component relies on the onDelete props, it makes sense that you need to set the props when you mount your component.

Or you can test with a "test component", which is closer to what you're looking for maybe:

```ts
  it('renders the correct contents (with attrs)', async () => {
    const deleteListener = vi.fn()
    const Test = defineComponent({
      template: `<Badge @delete="deleteListener()" />`,
      components: { Badge },
      setup() {
        return { deleteListener }
      }
    })
    const wrapper = mount(Test)

    const button = wrapper.find('button')

    expect(button.exists()).toBe(true)
    await button.trigger('click');

    expect(deleteListener).toHaveBeenCalled();
  })
```

**Comment by chrismooreajbell** [comment]
Hi @cexbrayat thanks for your reply.

I just checked out your code sample in the demo repo and it does indeed work. Thanks for the clarification.

I think this may be a case of my misunderstanding of the similarity and differences between props and `v-on` events are under the hood, coming from Vue 2 and a slightly different way of doing things. For example, `v-on:delete` and `onDelete` are interchangeable.

I feel that writing the test in the way that you have provided is a more 'explicit' way to indicate the intention, if that makes sense, so we'll use that moving forwards.

This clears things up so thanks, I appreciate your time and help.
