### ISSUE TITLE
Using useSlots will report a warning

### ISSUE THREAD

**Issue by Jevin0** [vuejs/test-utils#2409]
**Describe the bug**
When using useSlots hook in the component. And when executing the slot.default() function. vue will throw a warning.

I know this may be a problem with vue. But how do I adjust? I would like to ask the author for help.

![image](https://github.com/vuejs/test-utils/assets/69580637/917f8e45-2c8c-4941-b675-913acd7e0793)

**To Reproduce**
https://stackblitz.com/edit/vitejs-vite-mohak4?terminal=dev

**Comment by cexbrayat** [comment]
Hi @Jevin0 

Yes, I think you're running into https://github.com/vuejs/core/issues/3257

What I usually do when I wan't to hide these warnings in tests is to spy the console.warn method:
```ts
vi.spyOn(console, 'warn').mockImplementation(() => {});
const wrapper = mount(...)
```

I'll close this as we can't do much in VTU to avoid it, and I'll let you watch https://github.com/vuejs/core/issues/3257.
