### ISSUE TITLE
Bug: Stubs broken in `vue@3.4.22`

### ISSUE THREAD

**Issue by alecgibson** [vuejs/test-utils#2411]
**Describe the bug**

`vue@3.4.22` added [stricter type checking for event handlers](https://github.com/vuejs/core/pull/8953), enforcing that they're either a `Function` or `Function[]`, and **not** a `string`.

`@vue/test-utils` [actively sets](https://github.com/vuejs/test-utils/blob/a0e0e68b8c0b9737682771e1a034bd0fcfeb0015/src/vnodeTransformers/stubComponentsTransformer.ts#L52-L53) handlers to the `string` `"[Function]"`, resulting in a warning:

```
      Error: Wrong type passed as event handler to onLeave - did you forget @ or : in front of your prop?
      Expected function or array of functions, received type string.at <Transition>
```

**To Reproduce**

https://stackblitz.com/edit/github-tyybbg?file=src%2Fcomponents%2FWelcomeItem.vue

```
npm i && npm run test:unit
```

**Expected behavior**

No warnings.

**Related information:**

```
  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.61 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @vue/test-utils: ^2.4.5 => 2.4.5 
    vue: ^3.4.22 => 3.4.22 
```

**Additional context**

**Comment by cexbrayat** [comment]
Thanks @alecgibson for the repro.
I think I have a possible fix in #2413

**Comment by alecgibson** [comment]
The fix has been merged, but not released yet.

**Comment by andrewbrennanfr** [comment]
Ah ok perfect 👍
