### ISSUE TITLE
Bug: Maximum call stack size exceeded, only happen on version 2.4.5

### ISSUE THREAD

**Issue by meidikawardana** [vuejs/test-utils#2425]
**Describe the bug**

When I run a unit test using vitest, the bug happen:
![image](https://github.com/vuejs/test-utils/assets/2024380/d7ee4585-139a-4c8f-979e-27333f5f0e3d)

**To Reproduce**

I can't provide a sample because it is a part of a private repo source code. I will provide screenshots, instead:
![image](https://github.com/vuejs/test-utils/assets/2024380/39277f78-dbfb-4595-aef1-932c382a918d)
![image](https://github.com/vuejs/test-utils/assets/2024380/f6204794-7bd2-4dcd-8658-e49e9daebabc)
![image](https://github.com/vuejs/test-utils/assets/2024380/89639cde-602a-4451-aeeb-347df7dc3c6c)
![image](https://github.com/vuejs/test-utils/assets/2024380/ec242e6d-6937-4bb9-8f9a-4919bc1164fd)

**Expected behavior**

The vitest test should pass

**Related information:**

```
% npx envinfo --system --npmPackages vue,@vue/test-utils,vitest,jest
Need to install the following packages:
envinfo@7.12.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 36.32 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @vue/test-utils: ^2.4.5 => 2.4.5 
    vitest: ^1.5.1 => 0.34.6 
    vue: ^3.4.25 => 3.4.25 
```

**Additional context**

When we mount a class which extends another class (parent class) and the parent class also extends another class, the issue could happen

**Comment by cexbrayat** [comment]
Hi @meidikawardana 

I think this might be the same issue as #2394 which we already fixed but have not yet released.

If you can't provide a small reproduction, I'll close this issue, and feel free to ping me if the upcoming v2.4.6 release doesn't fix your issue.
