### ISSUE TITLE
Feature request: setProvide

### ISSUE THREAD

**Issue by BBoehm** [vuejs/test-utils#2456]
**Is your feature request related to a problem? Please describe.** 
Testing different values for inject/provide currently needs a complete new wrapper to be defined: 

```js
  it('should do option A, if provided with "A"), () => {
    wrapper = shallowMount(VCommercialInfo, {
      props: myProps,
      global: {
        provide: {
          myProvide: ref('A'),
        },
      },
    });
    
    expect(...);
  });
  
  it('should do option B, if provided with "B"), () => {
    props: myProps,
    wrapper = shallowMount(VCommercialInfo, {
      global: {
        provide: {
          myProvide: ref('B'),
        },
      },
    });
    
    expect(...);
  });
```

This would get even more tedious when there is other data to be passed in, such as props/stubs/plugins/mocks/slots/... which would all lead to duplicate code.

**Describe the solution you'd like**
Would be great if we could have a setProvide function similar to setProps:
```js
  it('should do option C, if provided with "C"), async () => {
    await wrapper.setProvide({
      myProvide: ref('C'),
    });
    
    expect(...);
  });
```

**Comment by lmiller1990** [comment]
Could you could just create a function that reduces the duplication?

We used to have many things like `setMethods`, `setComputed` etc, the problem is the introduce something in your tests (changing the provided value) that cannot happen in a production environment. It led to many difficult to solve bugs, which is why `setComputed` does not exist anymore.

**Comment by BBoehm** [comment]
Hi @lmiller1990, 
thanks for the explanation. I was not aware of that, if those other functions were removed specifically, then it probably does not make sense to introduce this one - I will go for a local solution instead.

**Comment by lmiller1990** [comment]
Great, please share what you come up with!
