### ISSUE TITLE
Bug: Documentation for extending Vue Test Utils has outdated configuration for TypeScript?

### ISSUE THREAD

**Issue by ajuvonen** [vuejs/test-utils#2465]
**Describe the bug**
Following the instructions in https://test-utils.vuejs.org/guide/extending-vtu/plugins.html#Using-the-plugin-with-TypeScript does not seem to create a working solution that would both build and work in VSCode.

**To Reproduce**
https://stackblitz.com/edit/github-vpqsdt?file=src%2Fcomponents%2F__tests__%2Fvue-test-utils.d.ts&view=editor

Try pnpm build in Stackblitz with the vue-test-utils.d.ts file as suggested by the documentation. The build fails while tests run correctly. Then change the vue-test-utils.d.ts file configuration to the suggestion and retry build. Build should go through.

**Additional context**
Changing the contents of vue-test-utils.d.ts from the one suggested in the documentation to the following seems to fix the issue.
```
import {DOMWrapper} from '@vue/test-utils';

declare module '@vue/test-utils' {
  interface VueWrapper {
    findByTestId(testId: string): DOMWrapper<Element>;
  }
}
```

**Comment by starkovsky** [comment]
update is here

https://github.com/vuejs/test-utils/pull/2466

**Comment by TheDutchCoder** [comment]
> update is here
> 
> #2466

That fix is missing the `<Element>` part instead of `[]`. The example still doesn't work because TS infers the returned type as `any` currently.

The current docs tell you to do this:
```ts
import { DOMWrapper } from '@vue/test-utils';

declare module '@vue/test-utils' {
  interface VueWrapper {
    findByTestId(testId: string): DOMWrapper[];
  }
}
```

But it should be:
```ts
import { DOMWrapper } from '@vue/test-utils';

declare module '@vue/test-utils' {
  interface VueWrapper {
    findByTestId(testId: string): DOMWrapper<Element>;
  }
}
```
