### ISSUE TITLE
Docs: incorrect checkbox value check

### ISSUE THREAD

**Issue by bmulholland** [vuejs/test-utils#2475]
It's not impossible I'm missing something, but isn't this code incomplete and thus broken?

https://github.com/vuejs/test-utils/blob/main/docs/api/index.md?plain=1#L1694

`wrapper.find('div')` will return a DOMWrapper, not a boolean, right?

Looks like it's been like that for years. It's the only reference for how to check the value of a checkbox, though.

There's also a reference to `element.checked`, but TS flags that the property doesn't exist on VueNode. Of course, it probably just needs to be casted. (The docs should probably say something about that, for those new to TS.) For me, I prefer to check with the docs for correctness before just forcing Typescript to be tautologically correct. The lack of actual docs on the expected way to check this value really slowed me down today.

**Comment by cexbrayat** [comment]
Yeah, it doesn't look correct. It should probably be `expect(wrapper.find('div').exists()).toBe(true)`.
Would you mind opening a PR to fix this? (it's probably the same in the french version of the docs).

To check if a checkbox is checked, you can use `expect(wrapper.get('input').element.checked).toBe(true);`. I don't think you need a cast to make it work though.

**Comment by Psingh132** [comment]
Hi, I've submitted a PR #2495 that addresses this issue. Could you please review it when you have a chance?
https://github.com/vuejs/test-utils/pull/2495
