### ISSUE TITLE
Bug: @vue/test-utils doesn't require a specific vue version as peer dependency

### ISSUE THREAD

**Issue by Gi11i4m** [vuejs/test-utils#2507]
**Describe the bug**
@vue/test-utils doesn't require a specific vue version as peer dependency. In a monorepo with multiple vue versions (possible with `pnpm` (and probably `yarn` as well) this caused @vue/test-utils to import the wrong vue version when using `mount`.

The problem was fixed when adding vue `3.x` as peerDependency to @vue/test-utils using pnpm's `packageExtensions`.

**To Reproduce**
I can't share our code and since I'm not exactly sure what dependency structure is needed I can't take the time to set up a reproduction. 

We have a monorepo library with `vue2` packages, `vue3` packages and `shared` packages (with code that can be shared between the two versions).

It seems to me that declaring peer dependencies is a good practice in general.

**Expected behavior**
I expect @vue/test-utils to always depend on the correct vue version by declaring peer dependencies.

**Comment by cexbrayat** [comment]
Hi @Gi11i4m 

The peer dependency has been removed in https://github.com/vuejs/test-utils/pull/2364 by @qmonmert 

@qmonmert @lmiller1990 can you explain why this was necessary?

**Comment by cexbrayat** [comment]
@Gi11i4m Yes, feel free to open a PR 👍

**Comment by qmonmert** [comment]
@Gi11i4m the reason was in this ticket https://github.com/jhipster/jhipster-lite/issues/9030

**Comment by Gi11i4m** [comment]
@qmonmert I see. Well, I'm pretty sure the issue could've been fixed as well by setting the peer dependency range to `3.x` instead of `3.0.1`. Peer dependencies shouldn't be so strict, but we also shouldn't nuke them 😅

Here's a PR with peer dependencies re-added but with a wide range to assure everyone can still update within their own `Vue 3` version.

https://github.com/vuejs/test-utils/pull/2511
