### ISSUE TITLE
Bug: findComponent() without a wrapper no longer works with version >= 2.4.5

### ISSUE THREAD

**Issue by Louis-Stekhoven-Smith** [vuejs/test-utils#2543]
**Describe the bug**

using findComponent(Test) without a wrapper no longer works after upgrading version  >=2.4.5 

**To Reproduce**
```
import { h } from 'vue';
import { mount } from '@vue/test-utils';

function Test(props, context) {
    return h('div', {
        ...props,
        innerHTML: 'This is a test',
    });
}

describe('Mounting component', () => {
    test('with wrapper', () => {
        const Wrapper = {
            components: { Test },
            template: `<Test />`,
        };

        const wrapper = mount(Wrapper, {});
        const item = wrapper.findComponent(Test);
        expect(item.exists()).toBe(true);
    });

    // this test fails now, findComponent returns [Object: null prototype] {} 
    test('without wrapper', () => {
        const wrapper = mount(Test, {});
        const item = wrapper.findComponent(Test);
        expect(item.exists()).toBe(true);
        expect(item.html()).toStrictEqual('<div>This is a test</div>');
    });
});
```

Finding components by querySelector seems to still work though
```
        wrapper.findComponent('.foo')
        wrapper.findComponent('[data-test="foo"]')
```

**Expected behavior**
Both tests should pass.

**Comment by cexbrayat** [comment]
(and if you know which version introduced the regression, you can probably pinpoint the culprit commit by adding a unit test that reproduces your issue. You'll then have a good idea how to fix it)

**Comment by Louis-Stekhoven-Smith** [comment]
This issue is introduced in version 2.4.4

That said I discovered this while trouble shooting an issue which ended up being unrelated to this particular finding.
Thus this is no longer an issue for me and am happy to have this ticket closed. 

Cheers.
