### ISSUE TITLE
Bug: use composition API in vue2.7 wrapper undefined

### ISSUE THREAD

**Issue by karlsbeard** [vuejs/test-utils#2553]
**Describe the bug**

I am experiencing an issue where the wrapper cannot be instantiated in my current testing environment. I use Vue 2.7 with the Composition API and the `<script setup>` syntax. I want guidance on how to use @vue/test-utils to test components under these conditions effectively.

**To Reproduce**

will add the link later

**Expected behavior**

shallowMount or mount can be use correctly

**Related information:**

vue version: vue2.7.x
vue/test-utils: 1.x
components: ant-design-vue 1.x

**Additional context**

**Comment by cexbrayat** [comment]
Hi @karlsbeard 

This is the repository for VTU v2 and Vue v3.
If you have an issue with VTU v1, which is maintained by a different team, open it on https://github.com/vuejs/vue-test-utils/ (with a reproduction, otherwise they won't be able to help)
