### ISSUE TITLE
Bug: PR 2327 introduces regression in vm

### ISSUE THREAD

**Issue by davidnixon** [vuejs/test-utils#2557]
**Describe the bug**

This change
https://github.com/vuejs/test-utils/pull/2327
broke my test case.

**To Reproduce**

Pull this PR
https://github.com/carbon-design-system/carbon-components-vue/pull/1662
Run
`yarn test src/components/CvAccordion/__tests__/CvAccordion.spec.js`

The change in the PR #2327 removes the visibility of componentRef in the vm. It maybe related to the component using `defineExpose({ state });` which is not used elsewhere in our components.

Reverting the change on #2327 fixes the test case.

**Expected behavior**

```
    const acc = wrapper.findComponent(`.${carbonPrefix}--accordion`);
    expect(Boolean(acc.vm.componentRef)).toBe(true);
```

**Related information:**

**Additional context**

**Comment by freakzlike** [comment]
I'm not quite sure if I understand correctly, but what I see in your test case, that it's working correctly now and it was wrong previously:

https://github.com/carbon-design-system/carbon-components-vue/blob/main/src/components/CvAccordion/__tests__/CvAccordion.spec.js#L60
```vue
<template>
  <cv-accordion @change="handleChange" ref="componentRef">
  // ...
```
```js
// finds the instance of CvAccordion.vue
const acc = wrapper.findComponent(`.${carbonPrefix}--accordion`);
// But this expects `acc.vm` to be the parent component
expect(acc.vm.componentRef.state).toEqual(expectedState);
```


So you should do now
```js
expect(acc.vm.state).toEqual(expectedState);
// or
expect(wrapper.vm.componentRef.state).toEqual(expectedState);
```

I'm sorry for the regression, but this is how it should be in my opinion.

**Comment by davidnixon** [comment]
I agree that it looked a bit off before. This works.
```js
expect(acc.vm.state).toEqual(expectedState);
```
Thanks!
