### ISSUE TITLE
Bug: `find element` quēshī yuánsù 20 / 5,000 `find element` missing element

### ISSUE THREAD

**Issue by RSS1102** [vuejs/test-utils#2560]
https://github.com/vuejs/test-utils/issues/2555 continuation tracking

### To Reproduce:
https://stackblitz.com/~/github.com/RSS1102/tdesign-vue-test-utils

### Describe the bug:
After the last question, I tried to solve it on the actual project, but still failed. This time I copied the actual project.
When I click on the input area, a `popup` panel will appear below. I tried to get this `popup` panel but failed.

I found through debug vitest that there is no popup related element in `wrapperElement` (by the way, this is an element generated by js and then `position: absolute;` here).

<img width="1202" alt="17328667877100" src="https://github.com/user-attachments/assets/6aad35dc-b8ba-4715-bcb8-d9ce236e4e4a">

**Comment by cexbrayat** [comment]
Hi @RSS1102 

The popup will not be found on the wrapper: it is probably appended somewhere in the document, maybe using a teleport target that has to be created somewhere.

You should search the tests in the tdesign source code repository to see how they test it, or ask them about how to test the datepicker/popup.

I don't think this is an issue with VTU, so I'm going to close the issue.
