### ISSUE TITLE
Feature request: allow extending of `.find`

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/test-utils#2566]
**Is your feature request related to a problem? Please describe.**

Not really a problem, but I would like to setup helpers like `.findByTestId`.

**Describe the solution you'd like**

Some way to extend the VueWrapper to accept custom find implementations.

**Describe alternatives you've considered**

Creating global function, but they always need to pass in the wrapper, so the API isn't as clean and "native".

**Comment by freakzlike** [comment]
That's already supported
https://test-utils.vuejs.org/guide/extending-vtu/plugins.html#Data-Test-ID-Plugin

**Comment by TheDutchCoder** [comment]
Facepalm... Thanks!
