### ISSUE TITLE
Bug: find() lacks full support for combinators -- e.g. child combinator ">" inside :has

### ISSUE THREAD

**Issue by hugovdm** [vuejs/test-utils#2577]
**Describe the bug**
find() does not (fully?) support the child combinator.

**To Reproduce & Expected Behaviour**
(Pardon me: I could not figure out how to run unit tests in stackblitz.)

_Good:_ this works fine:

> wrapper.find(".ancestorClass:has(#descendantId)")

_Good:_ This finds the root element as expected

> wrapper.find(":has(#descendantId)")

_Bug:_ Here's the problem, this should find the immediate parent of the id=descendantId element, but instead, it also finds the root element:

> wrapper.find(":has(>#descendantId)")

**Related information:**

```
$ npx envinfo --system --npmPackages vue,@vue/test-utils,vitest,jest

  System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 15.52 GB / 31.07 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @vue/test-utils: ^2.4.6 => 2.4.6 
    vitest: ^2.1.5 => 2.1.8 
    vue: ^3.5.13 => 3.5.13 
```

**Comment by hugovdm** [comment]
From https://test-utils.vuejs.org/api/#find :

> You can use the same syntax querySelector implements. find is basically an alias for querySelector. In addition you can search for element refs.

If it makes sense to keep VueWrapper and DOMWrapper faster and/or simpler, fhat's fair too, but then the docs should perhaps metnion there is only partial support for querySelector?

I've also noticed the `:scope` CSS pseudo-classes is not implemented (or didn't work as I expected it to) and wondered whether to file a separate bug for "full CSS pseudo-classes" support.

**Comment by cexbrayat** [comment]
I'm not really surprised that this doesn't work. jsdom (that I assume you use) or happy-dom have a limited support for this kind of selectors. 

Vue test Utils doesn't do anything special for selectors, so we can't improve the situation on our side.

You can try using another dom implementation (like happy-dom maybe) or running your tests in a real browser if this kind of selector is really important for you (see https://vitest.dev/guide/browser/ for example). Or you can watch the numerous issues in the jsdom repo that references similar problems (see https://github.com/jsdom/jsdom/issues/3067 for example) and avoid these selectors in the meantime (which I would recommend).
