### ISSUE TITLE
DOMWrapper: setValue

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/test-utils#29]
combines `setSelected`, setChecked` etc as per  https://github.com/vuejs/vue-test-utils-next/issues/17#issuecomment-604367645

**Comment by dospunk** [comment]
This does not seem to be documented on the Migrating page https://next.vue-test-utils.vuejs.org/migration/

**Comment by lmiller1990** [comment]
This should have been backported to VTU v1 and include deprecation messages. Is that not the case?
