### ISSUE TITLE
Testing with HappyDOM

### ISSUE THREAD

**Issue by nandi95** [vuejs/test-utils#513]
By default jest uses JSDOM. I wanted to try out [HappyDOM](https://github.com/capricorn86/happy-dom) for the [sick performance gainz](https://github.com/capricorn86/happy-dom/blob/master/packages/jest-environment/README.md#performance), but unfortunately I'm getting an error:
```shell
TypeError: Reflect.ownKeys called on non-object
```
The error is coming from https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts#L451
Now, I don't know if this is an incorrect [implementation](https://github.com/capricorn86/happy-dom/blob/8295c6bfe1f6a6d40c903d103ca7767a234a15d4/packages/happy-dom/src/window/Window.ts#L171) on HappyDOM's part altough this seems to work as expected:
```js
const obj = { hi: 1 };

console.log(Reflect.ownKeys(obj)); // [ 'hi' ]
```
but can we perhaps also test with other jest environments?

I imagine this would could work something like
```js
// package.json
"test:happy-dom": "JEST_ENV=happy-dom jest",

// jest.config.js
testEnvironment: process.env.JEST_ENV === 'happy-dom' ? '@happy-dom/jest-environment' : 'jsdom',
```

I understand if this isn't desired as this would add additional time to gh actions and if testing another implementation, then where does the list of implementations to test stops...

**Comment by lmiller1990** [comment]
The GH actions run so fast, I think it's fine to add another step. I didn't know there was a jsdom alternative, that's cool.

I'd like to know why this isn't working, if you do find a fix, we can definitely add HappyDOM testing to CI in the manner you proposed (or something similar, whatever is fine).

**Comment by cexbrayat** [comment]
I tried again and we still have 10% of the tests failing with happy-dom (but there are no errors with VTU code as far as I can see).

There are issues with the way HappyDOM handles the visibility, selected options are not iterable, etc. We also had some issues opened by developers on VTU that were in fact from happy-dom

So I don't think we can add this to our CI, but feel free to use in project if that works for you
