### ISSUE TITLE
setData function with class components returns TypeError

### ISSUE THREAD

**Issue by Evertvdw** [vuejs/test-utils#572]
Hi there,

I got vue-jest to work so I continued to see if I could get unit tests working in my codebase. I stumbled upon the next issue, I saw this was also reported when using the Composition api but I get the same error with class components: 

I'm doing this inside a test:
`await wrapper.setData({ hovered: true });`

Which results in this error: 
`TypeError: Cannot add property hovered, object is not extensible`

Component looks like (simplified):
```ts
import { Vue } from 'vue-class-component';

export default class Test extends Vue {
     hovered = false;
}
```

So `hovered` is equivalent to what in the Options API would be data. So I would expect this to work. 

## Reproduce

You can reproduce this in the `vue-test-utils` codebase by adding these two lines: 
```ts
await wrapper.setData({dataText: 'Test'})
expect(wrapper.get('[data-methods]').text()).toBe('Test')
```
at the end of the `works with shallow mount and SFC` test in `classComponent.spec.ts`.

**Comment by Evertvdw** [comment]
A quick dive into this learn that with class components the `vm.$data` which is accessed in the `setData` method is empty. The data properties are just present on the `vm` object itself with a getter and setter. 

Just doing this in the code works instead of using `setData`
```ts
(wrapper.vm as any).hovered = true;
await (wrapper.vm as any).$nextTick();
```

It's not very nice and clean but for class components it seems that everything is just placed on the `vm` object and not in the `vm.$data` object. 

What you could do is check in `setData` for each property passed if `vm.hasOwnProperty()` is true, and if so update it. This might be needed for Composition api components also, see https://github.com/vuejs/vue-test-utils-next/issues/539

**Comment by lmiller1990** [comment]
Thanks for the issue report.

There are a number of known problems with class component. Another one is mocks not working correctly, [see here](https://github.com/vuejs/vue-test-utils/issues/1767). The main problem is `setData` assumes you are using an object component with a `data` property. As you pointed out, the way class components store data is a bit different (makes sense, classes have a built in way to store data).

If we can get class component to work correctly using `setData`, that would be great. 

```
@Component
export default class App extends Vue {
  someData = this.$t("message");
}
```

Should `this.$` properties be configurable with `setData`, too?

Could we just have a check in `setData`? Kind of like you suggested? Maybe not the cleanest but class component is already a bit of a dirty hack anyway.

```js
if (this.isClassComp) {
  this.vm[key] = value
  await this.vm.$nextTick()
} else {
  // usual stuff
}
```

**Comment by lmiller1990** [comment]
More or less dup: https://github.com/vuejs/test-utils/issues/1058

Going to merge all class component issues.
