### ISSUE TITLE
BUG: <img src="@/file.png"> Throws error (images using WebPack alias)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/test-utils#695]
```html
<template>
  <div id="app">
    <img src="@/assets/logo.png" alt="Vue.js logo" />
  </div>
</template>
```

The `@/` in the `src` causes an error when ran with VTU/Jest.

![](https://user-images.githubusercontent.com/4629794/123502219-b938d200-d618-11eb-9690-ad1bd4310ea1.png)

Removing the `@` fixes it, however then the images fail to load in the app when actually ran.

Not sure if this is in VTU (RC12), Vue 3, or something weird with my setup.

Reproduction:

* https://github.com/nwutils/nw-vue-cli-example/pull/20/files

**Comment by freakzlike** [comment]
Closed, because of same issue as #1400
