### ISSUE TITLE
Cannot extend class components when using SFC

### ISSUE THREAD

**Issue by nc-csl** [vuejs/test-utils#744]
Hi,
I have a very simple App.vue that imports a few components:
![image](https://user-images.githubusercontent.com/722375/124885613-bd2f0180-dfd3-11eb-8543-ee44fefd6aca.png)

Here is my test:
![image](https://user-images.githubusercontent.com/722375/124886503-96bd9600-dfd4-11eb-8ad4-105f967f4204.png)

I get a warning for each component when I shallowMount (or mount).
`console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: Failed to resolve component: Broedkrumme
      at <Anonymous ref="VTU_COMPONENT" >
      at <VTUROOT>`

Why is it necessary to stub all components when using shallowMount?

**Comment by cexbrayat** [comment]
Hi @nc-csl 

Are you using the latest version of VTU (2.0.0-rc.10)? If no please give a try, as it contains a lot of bugfixes. Make sure you're using the latest Vue version as well.

If you still have the issue, it would be great to give a small reproduction (we can't do much with screenshots).
You can do this by either:
- creating a github repo with vue-cli for example, all the latest versions and a unit test to reproduce your problem
- adding a unit test directly to VTU that repoduces the issue

**Comment by nc-csl** [comment]
Thanks for the reply. I found out what the reason was. As you can see I have a BaseVue class that is extended by App.vue. My BaseVue.vue is just another component that extends Vue. 
As soon as I change my App.vue to extend Vue instead of my BaseVue, I don't get the warnings anymore. Is it necessary to define my BaseVue in my test?

**Comment by lmiller1990** [comment]
What is `VueBase`?

If you can share your repo, that'll help.

**Comment by nc-csl** [comment]
Here is a repo where I have reproduced the issue. VueBase is just a Vue component that extends Vue. Run `npm run test:unit App` to see the warning.
https://github.com/nc-csl/vue-test-utils-demo

**Comment by nc-csl** [comment]
Did you have time to look at the repo?

**Comment by standbyoneself** [comment]
@nc-csl,
you don't need `VueBase` properly.

For Vue 3 you must use this imports:

```vue
<script lang="ts">
  import { Vue, Options } from 'vue-class-component';
  import Header from '@/components/global/Header.vue';

  @Options({
    components: {
      Header,
    },
  })
  export default class App extends Vue {}
</script>
```

**Comment by lmiller1990** [comment]
I had a look. The problem is that `VueBase` is basically just a class that `extends Vue`, so it should work the same. I guess something about how `vue-jest` compiles the code is messing with `vue-class-component`.

There are actually a number of bugs with class component and `vue-jest`. I will need to investigate this more deeply, but I am sure the problem is in `vue-jest`, not Test Utils.

As of right now I do not have a great work around - I generally recommend against class component in general, while it is officially supported it's not the most popular way to write Vue components.

**Comment by lmiller1990** [comment]
I get a different error when I reproduce this in Vue Jest only:

```
TypeError: Class extends value [object Object] is not a constructor or null
```

Repro:

VueBase.vue

```html
<script lang="ts">
import { Vue } from "vue-class-component";
export default class VueBase extends Vue {}
</script>
```

App.vue

```html
<template>
  <div />
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import VueBase from "./VueBase.vue";

export default class App extends VueBase {}
</script>
```

Spec

```
import { createApp }  from "vue";
// @ts-ignore
import App from "./App.vue"

// @ts-ignore
it("might work", () => {
  const el = document.createElement("div");
  const app = createApp(App).mount("#app");
});
```

tsconfig.json

```json
{
  "compilerOptions": {
    "module": "commonjs",                           /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                                 /* Enable all strict type-checking options. */
    /* Experimental Options */
    "experimentalDecorators": true,              /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,               /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                           /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true        /* Disallow inconsistently-cased references to the same file. */
  }
}
```

jest.config.js

```
const path = require('path')

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.vue$': 'vue3-jest'
    // '^.+\\js$': 'babel-jest'
  },
  moduleFileExtensions: ['vue', 'js', 'json', 'jsx', 'ts', 'tsx', 'node']
}
```

package.json

```
{
  "name": "vue-jest-class-component",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vue/compiler-sfc": "^3.1.4",
    "jest": "^27.0.6",
    "ts-jest": "^27.0.3",
    "typescript": "^4.3.5",
    "vue": "^3.1.4",
    "vue-class-component": "^8.0.0-rc.1",
    "vue3-jest": "^27.0.0-alpha.1"
  }
}
```

**Comment by nc-csl** [comment]
Hi @lmiller1990 
Thanks for the reply. I have tried to convert VueBase to a ts file, but I still get errors. 
I think we will have to consider removing vue-class-component.

I was recently on another project where we used vue2 with vue-class-component, where we had no issues in unit tests when extending classes in vue components.

**Comment by lmiller1990** [comment]
I'll do some more exploration in my free time but from what I can tell class component for Vue 3 is not production ready so it's hard to recommend using it.

We will keep this issue open, since I'd like to fix it eventually, but the solution is not immediately clear. If you value TS (like I do), try using the `defineComponent` syntax and Composition API - it's working great for me, everything is type safe, and with the VS Code extension called Volar you can get type checking in your templates, too!
