### ISSUE TITLE
Unable to stub transition component

### ISSUE THREAD

**Issue by Thomasan1999** [vuejs/test-utils#929]
I've tried to stub the Vue Transition component but was unable to do so. I was able to unstub the component with `transition: false` (since it is stubbed by default) but if I want to provide a custom stub, e.g. `transition: {template: '<p></p>'}`, it gets ignored.

Here is a repo with a custom transition stub: https://github.com/Thomasan1999/vue-test-utils-next-transition.

**Comment by lmiller1990** [comment]
I had a quick look at getting this one to work but no luck. I am not sure this is something we will be able to support - internally, Vue has some specific logic for `<transition>`, `<suspense>` etc that we may not be able to override.

I can look into this more, but before I spend too much time on it, what is your use case? Any reason to provide a custom stub for `<transition>`?

**Comment by Thomasan1999** [comment]
I have a toast message component which emits a `close` event after the close button is clicked. I want to test that the event is emitted after leave transition. I've tried both waiting for real timers and running fake timers but the event was still not fired.

Simplified template:
```
<template lang="pug">
transition(name="fade" @after-leave="$emit('close')")
    div.toast(v-if="opened")
        button.toast-close-button(@click="opened = false") X
</template>
```

**Comment by lmiller1990** [comment]
If you were to stub that component, you'd lose the `after-leave` event hook, too.

Can you just test against the real transition by opting out? Then it should trigger the correct hook, and you'd make your assertion.

**Comment by Thomasan1999** [comment]
I would lose the hook but I was thinking about some simple implementation like checking whether the slot exists on update lifecycle hook after it was mounted and if it does not exist, the component would trigger the `after-leave` hook. It's not the ideal solution but it should behave the same way. What do you mean by opting out?

**Comment by lmiller1990** [comment]
You should be able to do

```ts
mount(Comp, {
  global: {
    stubs: {
      transition: false
    }
  }
})
```

And then VTU will use a real `<transition>` component for you tests. That will give you the life cycle hook, and that should help with your test.

Can you share the exact component and test you are trying to write? Maybe there's a way to do it already.
