### ISSUE TITLE
findComponent not working with stubbed component

### ISSUE THREAD

**Issue by dospunk** [vuejs/test-utils#957]
I have a component I'm trying to test that uses router-link, and I'm trying to stub it out with my own component. 
My test looks like this:

```ts
test('Displays a normal router link when the route is not hidden and behavior is set to hide', () => {
  const wrapper = mount(HidableRouterLink, {
    global: {
      stubs: { 'router-link': MyRouterLinkStub },
      provide: { store: reactive(new Store()) },
    },
    props: {
      behavior: 'hide',
      to: currentRoute,
    },
    slots: {
      default: 'hello',
    },
  })
  expect(wrapper.findComponent(MyRouterLinkStub).text()).toBe('hello')
})
```

My expected outcome is that the test passes, but instead it fails with "Cannot call text on an empty VueWrapper."

If I use `console.log(wrapper.html())` it contains the contents of the MyRouterLinkStub component, so I know it's being inserted

**Comment by xanf** [comment]
@dospunk could you please show implementation of `MyRouterLinkStub` ?

Also could you try adding a `name` to your `MyRouterLinkStub`?

**Comment by dospunk** [comment]
Here is my implementation,
```vue
<template>
  <a><slot v-bind="slotProps" /></a>
</template>

<script>
import { defineComponent } from 'vue'
import { useLink } from 'vue-router'

export default defineComponent({
  props: {
    to: {
      type: [Object, String],
      required: true,
    },
  },
  setup() {
    const slotProps = useLink()
    return { slotProps }
  },
})
</script>
```

Adding the name property makes it work

**Comment by cexbrayat** [comment]
@dospunk Can you give it a try with VTU v2.0.0-rc.20, please? There have been a lot of changes since you opened this issue, so I'm wondering if this is still a problem or if we can close it.

**Comment by cexbrayat** [comment]
I think this should no longer be an issue with the latest VTU releases, I'll close this. Feel free to reopen with a repro if that's not the case
